import type { LearningItem } from "./lessonTypes";

export const ITEM_REGISTRY = {
  "chunk-bonjour": {
    id: "chunk-bonjour",
    type: "chunk",
    text: "Bonjour",
    status: "active",
    fr: "Bonjour",
    en: "Hello",
    meaning: "Greeting used from morning through late afternoon.",
    exampleFr: "Bonjour, je voudrais un café.",
    exampleEn: "Hello, I would like a coffee.",
  },
  "chunk-je-voudrais": {
    id: "chunk-je-voudrais",
    type: "chunk",
    text: "je voudrais",
    status: "active",
    fr: "je voudrais",
    en: "I would like",
    meaning: "Soft, polite request frame. More natural than 'I want' in French.",
    exampleFr: "Je voudrais un café, s'il vous plaît.",
    exampleEn: "I would like a coffee, please.",
    weakPointTags: ["politeness", "conditional-softness"],
  },
  "noun-cafe": {
    id: "noun-cafe",
    type: "noun",
    text: "café",
    status: "active",
    fr: "café",
    en: "coffee",
    meaning: "Coffee, or by extension, a café.",
    exampleFr: "un café",
    exampleEn: "a coffee",
    weakPointTags: ["gender", "articles"],
  },
  "chunk-sil-vous-plait": {
    id: "chunk-sil-vous-plait",
    type: "chunk",
    text: "s'il vous plaît",
    status: "active",
    fr: "s'il vous plaît",
    en: "please (formal)",
    meaning: "Formal please. Tied to vous register.",
    exampleFr: "Un café, s'il vous plaît.",
    exampleEn: "A coffee, please.",
    weakPointTags: ["politeness", "elision"],
  },
  "chunk-merci": {
    id: "chunk-merci",
    type: "chunk",
    text: "merci",
    status: "active",
    fr: "merci",
    en: "thank you",
    meaning: "Thank you. Closes a polite exchange.",
    exampleFr: "Merci !",
    exampleEn: "Thank you!",
    weakPointTags: ["politeness"],
  },
  "chunk-je-suis": {
    id: "chunk-je-suis",
    type: "chunk",
    text: "je suis",
    status: "active",
    fr: "je suis",
    en: "I am",
    meaning: "First-person 'to be' — identity, state, location.",
    exampleFr: "Je suis ici.",
    exampleEn: "I am here.",
    relatedItemIds: ["verb-etre", "pronoun-je", "chunk-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis"],
  },
  "chunk-j-ai": {
    id: "chunk-j-ai",
    type: "chunk",
    text: "j'ai",
    status: "active",
    fr: "j'ai",
    en: "I have",
    meaning: "First-person 'to have'. Sits in contrast with 'je suis'.",
    exampleFr: "J'ai une idée.",
    exampleEn: "I have an idea.",
    relatedItemIds: ["chunk-je-suis", "micro-je-suis-vs-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis", "elision"],
  },
  // R4 (L1-L15 audit, 2026-07): pronoun-je/tu/vous, verb-etre,
  // chunk-tu-es(-pret), chunk-vous-etes(-pret), sound-liaison,
  // grammar-etre-identity and noun-idee are registered but unused by any
  // v1 lesson surface. Retained for future register/etre lessons; see
  // docs/audits/L1_L15_CHIP_INVENTORY_AUDIT_2026_07.md (risk R4).
  "pronoun-je": {
    id: "pronoun-je",
    type: "pronoun",
    text: "je",
    status: "active",
    fr: "je",
    en: "I",
    meaning: "First-person singular subject pronoun. Elides to j' before a vowel.",
    exampleFr: "Je suis ici. J'ai une idée.",
    exampleEn: "I am here. I have an idea.",
    weakPointTags: ["elision"],
  },
  "pronoun-tu": {
    id: "pronoun-tu",
    type: "pronoun",
    text: "tu",
    status: "active",
    fr: "tu",
    en: "you (informal singular)",
    meaning: "Singular informal you. Used with friends, family, peers.",
    exampleFr: "Tu es prêt.",
    exampleEn: "You are ready.",
    weakPointTags: ["politeness"],
  },
  "pronoun-vous": {
    id: "pronoun-vous",
    type: "pronoun",
    text: "vous",
    status: "active",
    fr: "vous",
    en: "you (formal or plural)",
    meaning: "Formal singular or any plural you.",
    exampleFr: "Vous êtes prêt ?",
    exampleEn: "Are you ready?",
    weakPointTags: ["politeness", "liaison"],
  },
  "verb-etre": {
    id: "verb-etre",
    type: "verb",
    text: "être",
    status: "active",
    fr: "être",
    en: "to be",
    meaning: "Core identity verb. Architectural anchor of v1 L1.",
    exampleFr: "Je suis. Tu es. Il est. Vous êtes.",
    exampleEn: "I am. You are. He is. You are (formal).",
    relatedItemIds: [
      "chunk-je-suis",
      "chunk-tu-es",
      "chunk-vous-etes",
      "chunk-c-est",
      "grammar-etre-identity",
    ],
    weakPointTags: ["avoir-vs-etre"],
  },
  "chunk-tu-es": {
    id: "chunk-tu-es",
    type: "chunk",
    text: "tu es",
    status: "active",
    fr: "tu es",
    en: "you are (informal)",
    meaning: "Second-person informal of être.",
    exampleFr: "Tu es prêt.",
    exampleEn: "You are ready.",
    relatedItemIds: ["verb-etre", "pronoun-tu"],
  },
  "chunk-vous-etes": {
    id: "chunk-vous-etes",
    type: "chunk",
    text: "vous êtes",
    status: "active",
    fr: "vous êtes",
    en: "you are (formal/plural)",
    meaning: "Formal or plural être with liaison: 'vous-z-êtes'.",
    exampleFr: "Vous êtes ici.",
    exampleEn: "You are here.",
    relatedItemIds: ["verb-etre", "pronoun-vous"],
    weakPointTags: ["liaison"],
  },
  "chunk-c-est": {
    id: "chunk-c-est",
    type: "chunk",
    text: "c'est",
    status: "supported",
    fr: "c'est",
    en: "it is / that is",
    meaning: "Highly frequent identity/pointing chunk. Elides ce + est.",
    exampleFr: "C'est une idée.",
    exampleEn: "That's an idea.",
    relatedItemIds: ["verb-etre"],
    weakPointTags: ["elision"],
  },
  "sound-elision": {
    id: "sound-elision",
    type: "sound-pattern",
    text: "elision (j' / c' / l' / d' / s')",
    status: "recognition",
    meaning:
      "Vowel drop before a word starting with a vowel sound: je → j', ce → c', le/la → l', etc.",
    exampleFr: "je + ai → j'ai · ce + est → c'est · le + idée → l'idée",
    exampleEn: "I have · it is · the idea",
    weakPointTags: ["elision"],
  },
  "sound-liaison": {
    id: "sound-liaison",
    type: "sound-pattern",
    text: "liaison (vous_êtes, nous_avons)",
    status: "recognition",
    meaning:
      "A normally silent final consonant pronounced before a vowel-initial word.",
    exampleFr: "vous êtes → 'vou-z-êtes'",
    exampleEn: "you are (with linked 'z' sound)",
    weakPointTags: ["liaison", "silent-letters"],
  },
  "micro-je-suis-vs-j-ai": {
    id: "micro-je-suis-vs-j-ai",
    type: "micro-contrast",
    text: "je suis vs j'ai",
    status: "recognition",
    meaning:
      "French uses 'avoir' (j'ai) where English uses 'to be' for age, hunger, fear, etc. 'Je suis' = identity/state; 'j'ai' = possession or sensation.",
    exampleFr: "Je suis fatigué. (state) · J'ai faim. (sensation)",
    exampleEn: "I am tired. · I am hungry. (lit. 'I have hunger')",
    relatedItemIds: ["chunk-je-suis", "chunk-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis"],
  },
  "grammar-etre-identity": {
    id: "grammar-etre-identity",
    type: "grammar-nugget",
    text: "être = identity, state, location",
    status: "recognition",
    meaning:
      "Être names what or where something is. It does not express possession (use avoir).",
    exampleFr: "Je suis étudiant. Je suis ici. Je suis fatigué.",
    exampleEn: "I am a student. I am here. I am tired.",
    relatedItemIds: ["verb-etre", "micro-je-suis-vs-j-ai"],
    weakPointTags: ["avoir-vs-etre"],
  },
  "chunk-je-suis-ici": {
    id: "chunk-je-suis-ici",
    type: "chunk",
    text: "je suis ici",
    status: "active",
    fr: "je suis ici",
    en: "I am here",
    meaning:
      "L0 recognition chunk: learner meets the phrase whole, no verb-paradigm unpacking. Architecture target moves to v1 L1.",
    exampleFr: "Bonjour, je suis ici.",
    exampleEn: "Hello, I am here.",
    relatedItemIds: ["chunk-je-suis"],
    acquisitionComponents: ["chunk-je-suis", "word-ici"],
  },
  "word-ici": {
    id: "word-ici",
    type: "adverb",
    text: "ici",
    status: "supported",
    fr: "ici",
    en: "here",
    meaning:
      "Here. Produced as a chip since L2; registry identity added in the R3 hygiene pass so mastery events attach to an item.",
    exampleFr: "Je suis ici.",
    exampleEn: "I am here.",
    relatedItemIds: ["chunk-je-suis-ici", "adverb-ou-where"],
  },
  "chunk-tu-es-pret": {
    id: "chunk-tu-es-pret",
    type: "chunk",
    text: "tu es prêt",
    status: "supported",
    fr: "tu es prêt",
    en: "you are ready (informal)",
    meaning: "Informal readiness check.",
    exampleFr: "Tu es prêt ?",
    exampleEn: "Are you ready?",
    relatedItemIds: ["chunk-tu-es"],
  },
  "chunk-vous-etes-pret": {
    id: "chunk-vous-etes-pret",
    type: "chunk",
    text: "vous êtes prêt",
    status: "supported",
    fr: "vous êtes prêt",
    en: "you are ready (formal)",
    meaning: "Formal readiness check. Carries the vous-êtes liaison.",
    exampleFr: "Vous êtes prêt ?",
    exampleEn: "Are you ready?",
    relatedItemIds: ["chunk-vous-etes"],
    weakPointTags: ["liaison", "politeness"],
  },
  "noun-idee": {
    id: "noun-idee",
    type: "noun",
    text: "idée",
    status: "supported",
    fr: "idée",
    en: "idea",
    meaning: "Feminine noun, vowel-initial → triggers elision: l'idée, une idée.",
    exampleFr: "J'ai une idée.",
    exampleEn: "I have an idea.",
    weakPointTags: ["gender", "articles", "elision"],
  },
  "noun-question": {
    id: "noun-question",
    type: "noun",
    text: "question",
    status: "supported",
    fr: "question",
    en: "question",
    meaning: "Feminine noun.",
    exampleFr: "J'ai une question.",
    exampleEn: "I have a question.",
    weakPointTags: ["gender", "articles"],
  },
  "chunk-non": {
    id: "chunk-non",
    type: "chunk",
    text: "non",
    status: "active",
    fr: "non",
    en: "no",
    meaning: "No. The direct answer, and the start of a polite refusal.",
    exampleFr: "Non, merci.",
    exampleEn: "No, thank you.",
    relatedItemIds: ["chunk-non-merci", "chunk-oui"],
    weakPointTags: ["negation"],
  },
  "chunk-oui": {
    id: "chunk-oui",
    type: "chunk",
    text: "oui",
    status: "active",
    fr: "oui",
    en: "yes",
    meaning:
      "Yes, as an ANSWER word. Scope note (audit R2, Payload Economy): never slotted inside questions or statements (wrong-slot trap in L8/L13/L14 fills); producible-answer rehabilitation lands with the L1-L5 enrichment canon.",
    exampleFr: "Oui, merci.",
    exampleEn: "Yes, thank you.",
    relatedItemIds: ["chunk-non"],
  },
  "chunk-je-ne-suis-pas": {
    id: "chunk-je-ne-suis-pas",
    type: "chunk",
    text: "je ne suis pas",
    status: "active",
    fr: "je ne suis pas",
    en: "I am not",
    meaning: "The negative of je suis. ne and pas wrap the verb.",
    exampleFr: "Je ne suis pas ici.",
    exampleEn: "I am not here.",
    relatedItemIds: ["chunk-je-suis", "grammar-ne-pas-sandwich"],
    weakPointTags: ["negation", "ne-pas"],
  },
  "chunk-ce-n-est-pas": {
    id: "chunk-ce-n-est-pas",
    type: "chunk",
    text: "ce n'est pas",
    status: "active",
    fr: "ce n'est pas",
    en: "it is not / that is not",
    meaning: "The negative of c'est. Used to say that something is not the case.",
    exampleFr: "Ce n'est pas ici.",
    exampleEn: "It is not here.",
    relatedItemIds: ["chunk-c-est", "grammar-ne-pas-sandwich"],
    weakPointTags: ["negation", "ne-pas", "elision"],
  },
  "chunk-non-merci": {
    id: "chunk-non-merci",
    type: "chunk",
    text: "non merci",
    status: "supported",
    fr: "non merci",
    en: "no thank you",
    meaning:
      "A soft, complete refusal. Non on its own can feel blunt; non merci stays polite.",
    exampleFr: "Non merci.",
    exampleEn: "No thank you.",
    relatedItemIds: ["chunk-non", "chunk-merci"],
    weakPointTags: ["politeness", "negation"],
    acquisitionComponents: ["chunk-non", "chunk-merci"],
  },
  "grammar-ne-pas-sandwich": {
    id: "grammar-ne-pas-sandwich",
    type: "grammar-nugget",
    text: "ne ... pas wraps the action",
    status: "recognition",
    meaning:
      "French negation comes in two pieces: ne before the action, pas after it. They sit around the verb like a sandwich.",
    exampleFr: "Je suis ici. Je ne suis pas ici.",
    exampleEn: "I am here. I am not here.",
    relatedItemIds: ["chunk-je-ne-suis-pas", "chunk-ce-n-est-pas"],
    weakPointTags: ["negation", "ne-pas"],
  },
  "chunk-j-ai-faim": {
    id: "chunk-j-ai-faim",
    type: "chunk",
    text: "j'ai faim",
    status: "active",
    fr: "j'ai faim",
    en: "I am hungry",
    meaning:
      "I am hungry, literally 'I have hunger'. French puts this feeling on have.",
    exampleFr: "J'ai faim.",
    exampleEn: "I am hungry.",
    relatedItemIds: ["chunk-j-ai", "micro-je-suis-vs-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis"],
    acquisitionComponents: ["chunk-j-ai", "noun-faim"],
  },
  "noun-faim": {
    id: "noun-faim",
    type: "noun",
    text: "faim",
    status: "supported",
    fr: "faim",
    en: "hunger",
    meaning:
      "Hunger, the thing you HAVE in French (j'ai faim). Produced as a chip since L4; registry identity added in the R3 hygiene pass.",
    exampleFr: "J'ai faim.",
    exampleEn: "I am hungry.",
    relatedItemIds: ["chunk-j-ai-faim", "chunk-j-ai"],
    weakPointTags: ["avoir-vs-etre"],
  },
  "chunk-j-ai-une-question": {
    id: "chunk-j-ai-une-question",
    type: "chunk",
    text: "j'ai une question",
    status: "active",
    fr: "j'ai une question",
    en: "I have a question",
    meaning: "I have a question. j'ai used for plain possession.",
    exampleFr: "Bonjour, j'ai une question.",
    exampleEn: "Hello, I have a question.",
    relatedItemIds: ["chunk-j-ai", "noun-question"],
    weakPointTags: ["j-ai-vs-je-suis"],
    acquisitionComponents: ["chunk-j-ai", "chunk-une-question"],
  },
  "chunk-un-cafe": {
    id: "chunk-un-cafe",
    type: "chunk",
    text: "un café",
    status: "active",
    fr: "un café",
    en: "a coffee",
    meaning: "A coffee, as one package. Café travels with un.",
    exampleFr: "Je voudrais un café.",
    exampleEn: "I would like a coffee.",
    relatedItemIds: ["noun-cafe", "chunk-une-question"],
    weakPointTags: ["articles", "gender"],
  },
  "chunk-une-question": {
    id: "chunk-une-question",
    type: "chunk",
    text: "une question",
    status: "active",
    fr: "une question",
    en: "a question",
    meaning: "A question, as one package. Question travels with une.",
    exampleFr: "J'ai une question.",
    exampleEn: "I have a question.",
    relatedItemIds: ["noun-question", "chunk-un-cafe"],
    weakPointTags: ["articles", "gender"],
  },
  "grammar-un-une-package": {
    id: "grammar-un-une-package",
    type: "grammar-nugget",
    text: "un and une are little packages",
    status: "recognition",
    meaning:
      "Many French words come with a little word in front. Learn the package, not a rule: un café, une question.",
    exampleFr: "un café, une question",
    exampleEn: "a coffee, a question",
    relatedItemIds: ["chunk-un-cafe", "chunk-une-question"],
    weakPointTags: ["articles", "gender"],
  },
  "chunk-au-revoir": {
    id: "chunk-au-revoir",
    type: "chunk",
    text: "au revoir",
    status: "active",
    fr: "au revoir",
    en: "goodbye",
    meaning: "Goodbye. The polite way to close a moment and leave.",
    exampleFr: "Merci, au revoir.",
    exampleEn: "Thank you, goodbye.",
    relatedItemIds: ["chunk-bonjour", "chunk-merci"],
    weakPointTags: ["politeness"],
  },
  // -- Unit 2 pilot (L7-L9): compact doorway items ---------------------------
  "chunk-je-vais": {
    id: "chunk-je-vais",
    type: "chunk",
    text: "je vais",
    status: "active",
    fr: "je vais",
    en: "I'm going",
    meaning:
      "Frozen chunk: I'm going / I'm heading off. Taken whole, no conjugation yet.",
    exampleFr: "Je vais à la maison.",
    exampleEn: "I'm going home.",
    relatedItemIds: ["chunk-je-suis"],
  },
  "chunk-a-la-maison": {
    id: "chunk-a-la-maison",
    type: "chunk",
    text: "à la maison",
    status: "supported",
    fr: "à la maison",
    en: "home",
    meaning:
      "Frozen destination unit: (to) home. One piece. The à/au/à la rule comes much later.",
    exampleFr: "Je vais à la maison.",
    exampleEn: "I'm going home.",
    relatedItemIds: ["chunk-je-vais"],
  },
  "chunk-c-est-ou": {
    id: "chunk-c-est-ou",
    type: "chunk",
    text: "c'est où ?",
    status: "active",
    fr: "c'est où ?",
    en: "where is it?",
    meaning:
      "Frozen everyday question: where is it? Literally \"it's where?\", the natural spoken shape.",
    exampleFr: "Le café, c'est où ?",
    exampleEn: "The café, where is it?",
    relatedItemIds: ["chunk-c-est", "adverb-ou-where"],
  },
  "adverb-ou-where": {
    id: "adverb-ou-where",
    type: "adverb",
    text: "où",
    status: "supported",
    fr: "où",
    en: "where",
    meaning:
      "Where. The question word inside c'est où ?, owned as part of the frame first.",
    exampleFr: "C'est où ?",
    exampleEn: "Where is it?",
    relatedItemIds: ["chunk-c-est-ou"],
  },
  "chunk-faire-une-pause": {
    id: "chunk-faire-une-pause",
    type: "chunk",
    text: "faire une pause",
    status: "active",
    fr: "faire une pause",
    en: "to take a break",
    meaning:
      "Small-action package: take a pause. One piece; the wider faire universe comes much later.",
    exampleFr: "Je voudrais faire une pause.",
    exampleEn: "I'd like to take a break.",
    relatedItemIds: ["chunk-je-voudrais", "noun-pause"],
  },
  "noun-pause": {
    id: "noun-pause",
    type: "noun",
    text: "pause",
    status: "supported",
    fr: "pause",
    en: "a break",
    meaning: "A pause, a break. Feminine: une pause.",
    exampleFr: "une pause",
    exampleEn: "a break",
    relatedItemIds: ["chunk-faire-une-pause"],
    weakPointTags: ["gender", "articles"],
  },
  // -- Unit 2 batch (L10-L12): pouvoir-light + est-ce que wrapper -----------
  "chunk-je-peux": {
    id: "chunk-je-peux",
    type: "chunk",
    text: "je peux",
    status: "active",
    fr: "je peux",
    en: "I can",
    meaning:
      "Frozen ability/permission chunk: I can. Ask by rising intonation; no pouvoir paradigm yet.",
    exampleFr: "Je peux faire une pause ?",
    exampleEn: "Can I take a break?",
    relatedItemIds: ["chunk-je-voudrais", "chunk-faire-une-pause"],
  },
  "chunk-vous-pouvez": {
    id: "chunk-vous-pouvez",
    type: "chunk",
    text: "vous pouvez",
    status: "supported",
    fr: "vous pouvez",
    en: "you can",
    meaning:
      "Pouvoir piece for requests: you can. Used to ask others, with a rising voice; no pouvoir paradigm yet.",
    exampleFr: "Vous pouvez m'aider ?",
    exampleEn: "Can you help me?",
    relatedItemIds: ["chunk-je-peux"],
  },
  "verb-aider": {
    id: "verb-aider",
    type: "verb",
    text: "aider",
    status: "supported",
    fr: "aider",
    en: "to help",
    meaning: "To help, in its dictionary shape. Reusable after vous pouvez.",
    exampleFr: "Vous pouvez aider ?",
    exampleEn: "Can you help?",
    relatedItemIds: ["chunk-vous-pouvez", "chunk-m-aider"],
  },
  "chunk-m-aider": {
    id: "chunk-m-aider",
    type: "chunk",
    text: "m'aider",
    status: "supported",
    fr: "m'aider",
    en: "to help me",
    meaning:
      "Elision chunk: me + aider becomes m'aider (to help me). Only this frozen form for now; the wider object-pronoun family (t'aider, l'aider, me/te/lui) is deliberately deferred.",
    exampleFr: "Vous pouvez m'aider ?",
    exampleEn: "Can you help me?",
    relatedItemIds: ["verb-aider", "chunk-vous-pouvez"],
  },
  "chunk-est-ce-que": {
    id: "chunk-est-ce-que",
    type: "chunk",
    text: "est-ce que",
    status: "active",
    fr: "est-ce que",
    en: "question wrapper (is it that...)",
    meaning:
      "Yes/no question wrapper. Put it in front of a sentence you own and it becomes a question. No inversion, no question words yet.",
    exampleFr: "Est-ce que c'est ici ?",
    exampleEn: "Is it here?",
    relatedItemIds: ["chunk-c-est", "chunk-je-peux"],
  },
  // -- Unit 3 batch (L13-L15): y-light + obligation-light --------------------
  "word-y-place": {
    id: "word-y-place",
    type: "pronoun",
    text: "y",
    status: "active",
    fr: "y",
    en: "there (the place you named)",
    meaning:
      "Place pronoun, one sense only: stands in for a place already named (a + place) and sits BEFORE the verb. Other uses of y (il y a, j'y pense) are separate, later doorways.",
    exampleFr: "J'y vais.",
    exampleEn: "I'm going there.",
    relatedItemIds: ["chunk-je-vais", "chunk-j-y-vais"],
  },
  "chunk-j-y-vais": {
    id: "chunk-j-y-vais",
    type: "chunk",
    text: "j'y vais",
    status: "active",
    fr: "j'y vais",
    en: "I'm off / I'm going there",
    meaning:
      "Near-fixed expression: je + y + vais, with je squeezed to j' in front of y. Owned as a whole; the productive replacement rule comes later.",
    exampleFr: "J'y vais.",
    exampleEn: "I'm off.",
    relatedItemIds: ["word-y-place", "chunk-je-vais"],
    acquisitionComponents: ["chunk-je-vais", "word-y-place"],
  },
  "chunk-on-y-va": {
    id: "chunk-on-y-va",
    type: "chunk",
    text: "on y va",
    status: "active",
    fr: "on y va",
    en: "let's go",
    meaning:
      "Near-fixed high-utility expression: let's go / we're going there. Frozen as a whole; NOT a general on + y + verb pattern. On (= we) lives only inside this chunk for now.",
    exampleFr: "On y va ?",
    exampleEn: "Shall we go?",
    relatedItemIds: ["word-y-place", "chunk-j-y-vais"],
  },
  "chunk-il-faut": {
    id: "chunk-il-faut",
    type: "chunk",
    text: "il faut",
    status: "active",
    fr: "il faut",
    en: "one must / it's necessary to",
    meaning:
      "Impersonal necessity opener, invariable: il faut + a plain verb. Faut only ever rides with il; no paradigm, no il faut que clause yet.",
    exampleFr: "Il faut faire une pause.",
    exampleEn: "We need to take a break.",
    relatedItemIds: ["chunk-je-dois", "chunk-faire-une-pause"],
  },
  "chunk-je-dois": {
    id: "chunk-je-dois",
    type: "chunk",
    text: "je dois",
    status: "supported",
    fr: "je dois",
    en: "I have to",
    meaning:
      "Personal obligation, one person-form only: I have to + a plain verb. The je peux sibling; the devoir paradigm and the owe sense come later.",
    exampleFr: "Je dois aller à la maison.",
    exampleEn: "I have to go home.",
    relatedItemIds: ["chunk-je-peux", "chunk-il-faut"],
  },
  "verb-aller": {
    id: "verb-aller",
    type: "verb",
    status: "supported",
    text: "aller",
    fr: "aller",
    en: "to go",
    meaning:
      "To go, in its dictionary shape. Reusable after il faut / je dois; je vais stays the moving engine for saying you are going.",
    exampleFr: "Je dois aller à la maison.",
    exampleEn: "I have to go home.",
    relatedItemIds: ["chunk-je-vais", "chunk-a-la-maison"],
  },

  // ── PR-07: L1 pilot registrations (founder-waived provisional French QA) ──
  // Four acquisition concepts, five runtime ids ("un thé" carries a primary +
  // linked pair). No named-human French approval exists for these surfaces;
  // they are internally reachable ONLY under the founder's explicit risk
  // acceptance, and the final comprehensive human QA pass remains mandatory
  // before any public / content-complete release.
  "chunk-excusez-moi": {
    id: "chunk-excusez-moi",
    type: "chunk",
    text: "excusez-moi",
    status: "supported",
    fr: "excusez-moi",
    en: "excuse me",
    meaning:
      "Attention-getting excuse me. One whole polite formula for opening contact with a stranger; never decomposed at L1.",
    exampleFr: "Excusez-moi, je voudrais un café.",
    exampleEn: "Excuse me, I would like a coffee.",
    frenchQa: "founder_waived_provisional",
  },
  "chunk-je-ne-comprends-pas": {
    id: "chunk-je-ne-comprends-pas",
    type: "chunk",
    text: "je ne comprends pas",
    status: "supported",
    fr: "je ne comprends pas",
    en: "I don't understand",
    meaning:
      "Closed survival formula: I don't understand. Owned as one whole; the ne…pas negation system is never split out of it at L1.",
    exampleFr: "Je ne comprends pas.",
    exampleEn: "I don't understand.",
    frenchQa: "founder_waived_provisional",
  },
  "chunk-vous-pouvez-repeter": {
    id: "chunk-vous-pouvez-repeter",
    type: "chunk",
    text: "vous pouvez répéter ?",
    status: "supported",
    fr: "vous pouvez répéter ?",
    en: "can you say that again?",
    meaning:
      "Rescue request in the locked non-inverted shape. Only this statement-shaped question form is learned at L1; the formal inverted variant stays out of learner content.",
    exampleFr: "Vous pouvez répéter ?",
    exampleEn: "Can you say that again?",
    frenchQa: "founder_waived_provisional",
  },
  "chunk-un-the": {
    id: "chunk-un-the",
    type: "chunk",
    text: "un thé",
    status: "supported",
    fr: "un thé",
    en: "a tea",
    meaning:
      "A tea, owned as one article+noun package. Primary acquisition identity of the tea concept; all L1 evidence flows here.",
    exampleFr: "Je voudrais un thé, s'il vous plaît.",
    exampleEn: "I would like a tea, please.",
    frenchQa: "founder_waived_provisional",
    acquisitionLink: { role: "primary", linkedItemIds: ["noun-the"] },
  },
  "noun-the": {
    id: "noun-the",
    type: "noun",
    text: "thé",
    status: "supported",
    fr: "thé",
    en: "tea",
    meaning:
      "Tea, the bare noun. Linked sub-identity of chunk-un-the; not an L1 evidence target — no L1 event may name it.",
    exampleFr: "un thé",
    exampleEn: "a tea",
    frenchQa: "founder_waived_provisional",
    acquisitionLink: { role: "linked", primaryItemId: "chunk-un-the" },
  },

  // ── L17 batch: social check-in + the first two state adjectives ───────────
  // Three identities, three acquisition demands. Deliberately NOT created:
  // `chunk-ca-va-question` (the rising-intonation ask is a USE of the frozen
  // chunk, exactly as `Je peux faire une pause ?` is a use of chunk-je-peux —
  // punctuation does not mint an identity); `chunk-ca-ne-va-pas` (composed from
  // this chunk plus the owned ne...pas operation, per the je-ne-peux-pas canon);
  // and any `chunk-je-suis-fatigue` / `chunk-je-suis-content` composite (the
  // adjectives compose with the owned chunk-je-suis, exactly as chunk-je-vais
  // composes with chunk-a-la-maison). Feminine forms are authored surfaces of
  // one identity each, never separate ids (PRJ-015 IC-005).
  "chunk-ca-va": {
    id: "chunk-ca-va",
    type: "chunk",
    text: "ça va",
    status: "active",
    fr: "ça va",
    en: "how's it going? / I'm okay",
    meaning:
      "Frozen social check-in, taken whole. One unit with two uses: asked with a rising voice (Ça va ?) and answered with a falling one (Ça va.). It is NOT productive aller and NOT futur proche — va rides only with ça here, and the aller of je vais à la maison stays a separate, movement-only engine. The negative answer, Ça ne va pas., is built with the ne...pas you already own.",
    exampleFr: "Ça va ?",
    exampleEn: "How's it going?",
    relatedItemIds: ["chunk-bonjour", "chunk-je-suis"],
    weakPointTags: ["aller-future"],
  },
  "adj-fatigue": {
    id: "adj-fatigue",
    type: "adjective",
    text: "fatigué",
    status: "active",
    fr: "fatigué",
    en: "tired",
    meaning:
      "Tired. Two written forms shown as a fixed pair — fatigué when a man says it, fatiguée when a woman does — never taught as an agreement rule. It drops into the je suis ___ frame you already own; the adjective-agreement system stays closed.",
    exampleFr: "Je suis fatigué.",
    exampleEn: "I'm tired.",
    relatedItemIds: ["chunk-je-suis", "adj-content"],
    weakPointTags: ["gender"],
  },
  "adj-content": {
    id: "adj-content",
    type: "adjective",
    text: "content",
    status: "active",
    fr: "content",
    en: "glad, pleased",
    meaning:
      "Glad, pleased — the first good thing you can say about how you are. A fixed pair like fatigué: content (m) / contente (f), shown, not ruled. Same je suis ___ frame; no agreement system, and no wider feelings vocabulary yet.",
    exampleFr: "Je suis content.",
    exampleEn: "I'm glad.",
    relatedItemIds: ["chunk-je-suis", "adj-fatigue"],
    weakPointTags: ["gender"],
  },
} as const satisfies Record<string, LearningItem>;

export type ItemId = keyof typeof ITEM_REGISTRY;

export function getItem(id: ItemId): LearningItem {
  return ITEM_REGISTRY[id];
}

export function hasItem(id: string): id is ItemId {
  return id in ITEM_REGISTRY;
}

export function getItems(ids: ItemId[]): LearningItem[] {
  return ids.map((id) => ITEM_REGISTRY[id]);
}
