import type { LearningItem } from "./lessonTypes";

export const ITEM_REGISTRY = {
  "chunk-bonjour": {
    id: "chunk-bonjour",
    type: "chunk",
    text: "Bonjour",
    status: "active",
    fr: "Bonjour",
    en: "Hello",
    meaning: "Greeting used from morning through late afternoon.",
    exampleFr: "Bonjour, je voudrais un café.",
    exampleEn: "Hello, I would like a coffee.",
  },
  "chunk-je-voudrais": {
    id: "chunk-je-voudrais",
    type: "chunk",
    text: "je voudrais",
    status: "active",
    fr: "je voudrais",
    en: "I would like",
    meaning: "Soft, polite request frame. More natural than 'I want' in French.",
    exampleFr: "Je voudrais un café, s'il vous plaît.",
    exampleEn: "I would like a coffee, please.",
    weakPointTags: ["politeness", "conditional-softness"],
  },
  "noun-cafe": {
    id: "noun-cafe",
    type: "noun",
    text: "café",
    status: "active",
    fr: "café",
    en: "coffee",
    meaning: "Coffee, or by extension, a café.",
    exampleFr: "un café",
    exampleEn: "a coffee",
    weakPointTags: ["gender", "articles"],
  },
  "chunk-sil-vous-plait": {
    id: "chunk-sil-vous-plait",
    type: "chunk",
    text: "s'il vous plaît",
    status: "active",
    fr: "s'il vous plaît",
    en: "please (formal)",
    meaning: "Formal please. Tied to vous register.",
    exampleFr: "Un café, s'il vous plaît.",
    exampleEn: "A coffee, please.",
    weakPointTags: ["politeness", "elision"],
  },
  "chunk-je-suis": {
    id: "chunk-je-suis",
    type: "chunk",
    text: "je suis",
    status: "active",
    fr: "je suis",
    en: "I am",
    meaning: "First-person 'to be' — identity, state, location.",
    exampleFr: "Je suis ici.",
    exampleEn: "I am here.",
    relatedItemIds: ["verb-etre", "pronoun-je", "chunk-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis"],
  },
  "chunk-j-ai": {
    id: "chunk-j-ai",
    type: "chunk",
    text: "j'ai",
    status: "supported",
    fr: "j'ai",
    en: "I have",
    meaning: "First-person 'to have'. Sits in contrast with 'je suis'.",
    exampleFr: "J'ai une idée.",
    exampleEn: "I have an idea.",
    relatedItemIds: ["chunk-je-suis", "micro-je-suis-vs-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis", "elision"],
  },
  "pronoun-je": {
    id: "pronoun-je",
    type: "pronoun",
    text: "je",
    status: "active",
    fr: "je",
    en: "I",
    meaning: "First-person singular subject pronoun. Elides to j' before a vowel.",
    exampleFr: "Je suis ici. J'ai une idée.",
    exampleEn: "I am here. I have an idea.",
    weakPointTags: ["elision"],
  },
  "pronoun-tu": {
    id: "pronoun-tu",
    type: "pronoun",
    text: "tu",
    status: "active",
    fr: "tu",
    en: "you (informal singular)",
    meaning: "Singular informal you. Used with friends, family, peers.",
    exampleFr: "Tu es prêt.",
    exampleEn: "You are ready.",
    weakPointTags: ["politeness"],
  },
  "pronoun-vous": {
    id: "pronoun-vous",
    type: "pronoun",
    text: "vous",
    status: "active",
    fr: "vous",
    en: "you (formal or plural)",
    meaning: "Formal singular or any plural you.",
    exampleFr: "Vous êtes prêt ?",
    exampleEn: "Are you ready?",
    weakPointTags: ["politeness", "liaison"],
  },
  "verb-etre": {
    id: "verb-etre",
    type: "verb",
    text: "être",
    status: "active",
    fr: "être",
    en: "to be",
    meaning: "Core identity verb. Architectural anchor of v1 L1.",
    exampleFr: "Je suis. Tu es. Il est. Vous êtes.",
    exampleEn: "I am. You are. He is. You are (formal).",
    relatedItemIds: [
      "chunk-je-suis",
      "chunk-tu-es",
      "chunk-vous-etes",
      "chunk-c-est",
      "grammar-etre-identity",
    ],
    weakPointTags: ["avoir-vs-etre"],
  },
  "chunk-tu-es": {
    id: "chunk-tu-es",
    type: "chunk",
    text: "tu es",
    status: "active",
    fr: "tu es",
    en: "you are (informal)",
    meaning: "Second-person informal of être.",
    exampleFr: "Tu es prêt.",
    exampleEn: "You are ready.",
    relatedItemIds: ["verb-etre", "pronoun-tu"],
  },
  "chunk-vous-etes": {
    id: "chunk-vous-etes",
    type: "chunk",
    text: "vous êtes",
    status: "active",
    fr: "vous êtes",
    en: "you are (formal/plural)",
    meaning: "Formal or plural être with liaison: 'vous-z-êtes'.",
    exampleFr: "Vous êtes ici.",
    exampleEn: "You are here.",
    relatedItemIds: ["verb-etre", "pronoun-vous"],
    weakPointTags: ["liaison"],
  },
  "chunk-c-est": {
    id: "chunk-c-est",
    type: "chunk",
    text: "c'est",
    status: "supported",
    fr: "c'est",
    en: "it is / that is",
    meaning: "Highly frequent identity/pointing chunk. Elides ce + est.",
    exampleFr: "C'est une idée.",
    exampleEn: "That's an idea.",
    relatedItemIds: ["verb-etre"],
    weakPointTags: ["elision"],
  },
  "sound-elision": {
    id: "sound-elision",
    type: "sound-pattern",
    text: "elision (j' / c' / l' / d' / s')",
    status: "recognition",
    meaning:
      "Vowel drop before a word starting with a vowel sound: je → j', ce → c', le/la → l', etc.",
    exampleFr: "je + ai → j'ai · ce + est → c'est · le + idée → l'idée",
    exampleEn: "I have · it is · the idea",
    weakPointTags: ["elision"],
  },
  "sound-liaison": {
    id: "sound-liaison",
    type: "sound-pattern",
    text: "liaison (vous_êtes, nous_avons)",
    status: "recognition",
    meaning:
      "A normally silent final consonant pronounced before a vowel-initial word.",
    exampleFr: "vous êtes → 'vou-z-êtes'",
    exampleEn: "you are (with linked 'z' sound)",
    weakPointTags: ["liaison", "silent-letters"],
  },
  "micro-je-suis-vs-j-ai": {
    id: "micro-je-suis-vs-j-ai",
    type: "micro-contrast",
    text: "je suis vs j'ai",
    status: "recognition",
    meaning:
      "French uses 'avoir' (j'ai) where English uses 'to be' for age, hunger, fear, etc. 'Je suis' = identity/state; 'j'ai' = possession or sensation.",
    exampleFr: "Je suis fatigué. (state) · J'ai faim. (sensation)",
    exampleEn: "I am tired. · I am hungry. (lit. 'I have hunger')",
    relatedItemIds: ["chunk-je-suis", "chunk-j-ai"],
    weakPointTags: ["avoir-vs-etre", "j-ai-vs-je-suis"],
  },
  "grammar-etre-identity": {
    id: "grammar-etre-identity",
    type: "grammar-nugget",
    text: "être = identity, state, location",
    status: "recognition",
    meaning:
      "Être names what or where something is. It does not express possession (use avoir).",
    exampleFr: "Je suis étudiant. Je suis ici. Je suis fatigué.",
    exampleEn: "I am a student. I am here. I am tired.",
    relatedItemIds: ["verb-etre", "micro-je-suis-vs-j-ai"],
    weakPointTags: ["avoir-vs-etre"],
  },
  "chunk-je-suis-ici": {
    id: "chunk-je-suis-ici",
    type: "chunk",
    text: "je suis ici",
    status: "active",
    fr: "je suis ici",
    en: "I am here",
    meaning:
      "L0 recognition chunk: learner meets the phrase whole, no verb-paradigm unpacking. Architecture target moves to v1 L1.",
    exampleFr: "Bonjour, je suis ici.",
    exampleEn: "Hello, I am here.",
    relatedItemIds: ["chunk-je-suis"],
  },
  "chunk-tu-es-pret": {
    id: "chunk-tu-es-pret",
    type: "chunk",
    text: "tu es prêt",
    status: "supported",
    fr: "tu es prêt",
    en: "you are ready (informal)",
    meaning: "Informal readiness check.",
    exampleFr: "Tu es prêt ?",
    exampleEn: "Are you ready?",
    relatedItemIds: ["chunk-tu-es"],
  },
  "chunk-vous-etes-pret": {
    id: "chunk-vous-etes-pret",
    type: "chunk",
    text: "vous êtes prêt",
    status: "supported",
    fr: "vous êtes prêt",
    en: "you are ready (formal)",
    meaning: "Formal readiness check. Carries the vous-êtes liaison.",
    exampleFr: "Vous êtes prêt ?",
    exampleEn: "Are you ready?",
    relatedItemIds: ["chunk-vous-etes"],
    weakPointTags: ["liaison", "politeness"],
  },
  "noun-idee": {
    id: "noun-idee",
    type: "noun",
    text: "idée",
    status: "supported",
    fr: "idée",
    en: "idea",
    meaning: "Feminine noun, vowel-initial → triggers elision: l'idée, une idée.",
    exampleFr: "J'ai une idée.",
    exampleEn: "I have an idea.",
    weakPointTags: ["gender", "articles", "elision"],
  },
  "noun-question": {
    id: "noun-question",
    type: "noun",
    text: "question",
    status: "supported",
    fr: "question",
    en: "question",
    meaning: "Feminine noun.",
    exampleFr: "J'ai une question.",
    exampleEn: "I have a question.",
    weakPointTags: ["gender", "articles"],
  },
} as const satisfies Record<string, LearningItem>;

export type ItemId = keyof typeof ITEM_REGISTRY;

export function getItem(id: ItemId): LearningItem {
  return ITEM_REGISTRY[id];
}

export function hasItem(id: string): id is ItemId {
  return id in ITEM_REGISTRY;
}

export function getItems(ids: ItemId[]): LearningItem[] {
  return ids.map((id) => ITEM_REGISTRY[id]);
}
