/**
 * L1 practice seeds — the polite counter.
 *
 * Quarry note: `data/pools/pool1.ts` is the old Survival Kit pool and its
 * SITUATIONS are genuinely good (a waiter waiting, a shop owner rattling off
 * prices, a stranger who walked you three blocks). Its ANSWERS mostly are not:
 * they reach for `bonsoir`, `salut`, `pardon`, `beaucoup`, `comment allez-vous`
 * and `pouvez-vous répéter` — the last being the inverted form current canon
 * does not own (`chunk-vous-pouvez-repeter` is "Vous pouvez répéter ?"). So the
 * scenes are ADAPTED here and the French is current canon throughout.
 */
import { fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-001";

export const L1_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l1-retrieve-merci",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-merci"],
    targets: ["chunk-merci"],
    weaveType: "mid",
    prompt: "Thank them.",
    context: "The coffee is set down in front of you.",
    answers: ["Merci."],
    alternatives: ["Merci"],
    ifCorrect: "The whole of politeness, in one word.",
  }),
  weaveSeed({
    id: "p-l1-retrieve-bonjour",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-bonjour"],
    targets: ["chunk-bonjour"],
    weaveType: "mid",
    prompt: "Greet them.",
    context: "You step inside and they look up at you.",
    answers: ["Bonjour."],
    alternatives: ["Bonjour"],
    ifCorrect: "That is the word that opens the door.",
  }),
  fillSeed({
    id: "p-l1-repair-opener-back-turned",
    operation: "repair",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-bonjour"],
    targets: ["chunk-excusez-moi"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "They have their back to you and have not seen you. Which opener reaches them?",
    correct: { id: "o-excusez", text: "Excusez-moi" },
    traps: [
      {
        id: "o-bonjour",
        text: "Bonjour",
        why: "Bonjour greets someone already looking at you. Here you have to reach them first.",
        tag: "wrong_item",
      },
      {
        id: "o-merci",
        text: "Merci",
        why: "Merci closes a moment. It cannot open one.",
        tag: "wrong_item",
      },
    ],
    short: "Excusez-moi",
    explanation: "Excusez-moi buys attention you do not have yet.",
  }),
  fillSeed({
    id: "p-l1-repair-polite-request",
    operation: "repair",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-voudrais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You are ordering from someone you have never met. Which keeps the request polite?",
    before: "Je ",
    after: " un café.",
    correct: { id: "o-voudrais", text: "voudrais" },
    traps: [
      {
        id: "o-veux",
        text: "veux",
        why: "Real French, but blunt with a stranger. Je voudrais stays soft.",
        tag: "wrong_register",
      },
      {
        id: "o-suis",
        text: "suis",
        why: "That says where you are, not what you want.",
        tag: "wrong_item",
      },
    ],
    short: "Je voudrais un café.",
    explanation: "Je voudrais softens any request, to anyone.",
  }),
  fillSeed({
    id: "p-l1-retrieve-please-tail",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-sil-vous-plait"],
    tags: ["politeness"],
    prompt: "Which piece closes the request politely?",
    before: "Je voudrais un café, ",
    after: "",
    correct: { id: "o-svp", text: "s'il vous plaît" },
    traps: [
      {
        id: "o-merci-tail",
        text: "merci",
        why: "Merci comes after you get it, not while you are asking.",
        tag: "wrong_item",
      },
      {
        id: "o-bonjour-tail",
        text: "bonjour",
        why: "That opens a moment. It cannot close a request.",
        tag: "wrong_item",
      },
    ],
    short: "Je voudrais un café, s'il vous plaît.",
    explanation: "S'il vous plaît rides on the end of what you want.",
  }),
  weaveSeed({
    id: "p-l1-produce-order-coffee",
    operation: "produce",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    weaveType: "context",
    prompt: "Order a coffee, politely.",
    context: "A terrace café. The server is waiting, and it is your turn.",
    answers: ["Je voudrais un café, s'il vous plaît."],
    alternatives: ["Je voudrais un café s'il vous plaît."],
    hintCloze: "Je ___ un café, ___.",
    ifCorrect: "That is a complete, polite order.",
    ifWrong: "Your meaning lands. Je voudrais opens it, s'il vous plaît closes it.",
  }),
  weaveSeed({
    id: "p-l1-produce-order-tea",
    operation: "produce",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-je-voudrais", "chunk-un-the"],
    weaveType: "context",
    prompt: "Order a tea instead.",
    context: "Same counter, and today you do not want coffee.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Same request, different thing in it. That is how the engine earns its keep.",
  }),
  weaveSeed({
    id: "p-l1-apply-too-fast",
    operation: "apply",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-vous-pouvez-repeter"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "context",
    prompt: "Ask them to say it again.",
    context: "They answered you at full speed and you caught almost none of it.",
    answers: ["Vous pouvez répéter ?"],
    alternatives: ["Vous pouvez répéter?", "Vous pouvez répéter"],
    ifCorrect: "One line, and the conversation keeps going.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-then-order",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: [
      "chunk-excusez-moi",
      "chunk-je-voudrais",
      "noun-cafe",
      "chunk-sil-vous-plait",
    ],
    targets: ["chunk-excusez-moi", "chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Reach them first, then order.",
    context: "Busy counter. Nobody has looked at you yet, and you would like a coffee.",
    answers: ["Excusez-moi, je voudrais un café, s'il vous plaît."],
    alternatives: ["Excusez-moi. Je voudrais un café, s'il vous plaît."],
    ifCorrect: "Attention first, request second. That order is the whole trick.",
    ifWrong: "Your meaning lands. Reach them before you ask for anything.",
  }),
  weaveSeed({
    id: "p-l1-apply-excuse-and-repeat",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Cut in politely, then ask for it again.",
    context: "They are already talking to the next person, and you still did not catch it.",
    answers: ["Excusez-moi, vous pouvez répéter ?"],
    alternatives: ["Excusez-moi, vous pouvez répéter?"],
    ifCorrect: "Polite interruption, then the ask. Nothing about that is rude here.",
  }),
];
