/**
 * L1 practice seeds — the polite counter.
 *
 * Quarry note: `data/pools/pool1.ts` is the old Survival Kit pool and its
 * SITUATIONS are genuinely good (a waiter waiting, a shop owner rattling off
 * prices, a stranger who walked you three blocks). Its ANSWERS mostly are not:
 * they reach for `bonsoir`, `salut`, `pardon`, `beaucoup`, `comment allez-vous`
 * and `pouvez-vous répéter` — the last being the inverted form current canon
 * does not own (`chunk-vous-pouvez-repeter` is "Vous pouvez répéter ?"). So the
 * scenes are ADAPTED here and the French is current canon throughout.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-001";

export const L1_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l1-retrieve-merci",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci"],
    targets: ["chunk-merci"],
    weaveType: "mid",
    prompt: "Thank them.",
    context: "The coffee is set down in front of you.",
    answers: ["Merci."],
    alternatives: ["Merci"],
    ifCorrect: "The whole of politeness, in one word.",
  }),
  weaveSeed({
    id: "p-l1-retrieve-bonjour",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour"],
    targets: ["chunk-bonjour"],
    weaveType: "mid",
    prompt: "Greet them.",
    context: "You step inside and they look up at you.",
    answers: ["Bonjour."],
    alternatives: ["Bonjour"],
    ifCorrect: "That is the word that opens the door.",
  }),
  fillSeed({
    id: "p-l1-repair-opener-back-turned",
    operation: "repair",
    difficulty: "easy",
    surface: "choice",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-bonjour"],
    targets: ["chunk-excusez-moi"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "They have their back to you and have not seen you. Which opener reaches them?",
    correct: { id: "o-excusez", text: "Excusez-moi" },
    traps: [
      {
        id: "o-bonjour",
        text: "Bonjour",
        why: "Bonjour greets someone already looking at you. Here you have to reach them first.",
        tag: "wrong_item",
      },
      {
        id: "o-merci",
        text: "Merci",
        why: "Merci closes a moment. It cannot open one.",
        tag: "wrong_item",
      },
    ],
    short: "Excusez-moi",
    explanation: "Excusez-moi buys attention you do not have yet.",
  }),
  fillSeed({
    id: "p-l1-repair-polite-request",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-voudrais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You are ordering from someone you have never met. Which keeps the request polite?",
    before: "Je ",
    after: " un café.",
    correct: { id: "o-voudrais", text: "voudrais" },
    traps: [
      {
        id: "o-veux",
        text: "veux",
        why: "Real French, but blunt with a stranger. Je voudrais stays soft.",
        tag: "wrong_register",
      },
      {
        id: "o-suis",
        text: "suis",
        why: "That says where you are, not what you want.",
        tag: "wrong_item",
      },
    ],
    short: "Je voudrais un café.",
    explanation: "Je voudrais softens any request, to anyone.",
  }),
  fillSeed({
    id: "p-l1-retrieve-please-tail",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-sil-vous-plait"],
    tags: ["politeness"],
    prompt: "Which piece closes the request politely?",
    before: "Je voudrais un café, ",
    after: "",
    correct: { id: "o-svp", text: "s'il vous plaît" },
    traps: [
      {
        id: "o-merci-tail",
        text: "merci",
        why: "Merci comes after you get it, not while you are asking.",
        tag: "wrong_item",
      },
      {
        id: "o-bonjour-tail",
        text: "bonjour",
        why: "That opens a moment. It cannot close a request.",
        tag: "wrong_item",
      },
    ],
    short: "Je voudrais un café, s'il vous plaît.",
    explanation: "S'il vous plaît rides on the end of what you want.",
  }),
  weaveSeed({
    id: "p-l1-produce-order-coffee",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    weaveType: "context",
    prompt: "Order a coffee, politely.",
    context: "A terrace café. The server is waiting, and it is your turn.",
    answers: ["Je voudrais un café, s'il vous plaît."],
    alternatives: ["Je voudrais un café s'il vous plaît."],
    hintCloze: "Je ___ un café, ___.",
    ifCorrect: "That is a complete, polite order.",
    ifWrong: "Your meaning lands. Je voudrais opens it, s'il vous plaît closes it.",
  }),
  weaveSeed({
    id: "p-l1-produce-order-tea",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-je-voudrais", "chunk-un-the"],
    weaveType: "context",
    prompt: "Order a tea instead.",
    context: "Same counter, and today you do not want coffee.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Same request, different thing in it. That is how the engine earns its keep.",
  }),
  weaveSeed({
    id: "p-l1-apply-too-fast",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-vous-pouvez-repeter"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "context",
    prompt: "Ask them to say it again.",
    context: "They answered you at full speed and you caught almost none of it.",
    answers: ["Vous pouvez répéter ?"],
    alternatives: ["Vous pouvez répéter?", "Vous pouvez répéter"],
    ifCorrect: "One line, and the conversation keeps going.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-then-order",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: [
      "chunk-excusez-moi",
      "chunk-je-voudrais",
      "noun-cafe",
      "chunk-sil-vous-plait",
    ],
    targets: ["chunk-excusez-moi", "chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Reach them first, then order.",
    context: "Busy counter. Nobody has looked at you yet, and you would like a coffee.",
    answers: ["Excusez-moi, je voudrais un café, s'il vous plaît."],
    alternatives: ["Excusez-moi. Je voudrais un café, s'il vous plaît."],
    ifCorrect: "Attention first, request second. That order is the whole trick.",
    ifWrong: "Your meaning lands. Reach them before you ask for anything.",
  }),
  weaveSeed({
    id: "p-l1-apply-excuse-and-repeat",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Cut in politely, then ask for it again.",
    context: "They are already talking to the next person, and you still did not catch it.",
    answers: ["Excusez-moi, vous pouvez répéter ?"],
    alternatives: ["Excusez-moi, vous pouvez répéter?"],
    ifCorrect: "Polite interruption, then the ask. Nothing about that is rude here.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l1-build-reach-and-ask",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter"],
    prompt: "Put the repair back together.",
    context: "They answered too fast, and they are already turning away.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-vous-pouvez-repeter", text: "vous pouvez répéter ?", answerIndex: 1 },
      { itemId: "chunk-merci", text: "merci" },
    ],
    target: "Excusez-moi, vous pouvez répéter ?",
    ifCorrect: "Attention first, then the ask. Two pieces, one move.",
    ifWrong: "Reach them before you ask for anything.",
  }),
  buildSeed({
    id: "p-l1-build-the-whole-order",
    operation: "retrieve",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    prompt: "Assemble the whole order.",
    context: "A terrace café, and it is your turn.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour,", answerIndex: 0 },
      { itemId: "chunk-je-voudrais", text: "je voudrais", answerIndex: 1 },
      { itemId: "noun-cafe", text: "un café,", answerIndex: 2 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît.", answerIndex: 3 },
      { itemId: "chunk-merci", text: "merci" },
    ],
    target: "Bonjour, je voudrais un café, s'il vous plaît.",
    ifCorrect: "Greeting, request, softener. That order is the whole of it.",
    ifWrong: "The polite tail goes at the end, after what you want.",
  }),
  fillSeed({
    id: "p-l1-listen-merci",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-merci"],
    targets: ["chunk-merci"],
    audio: "Merci.",
    prompt: "Listen. What did they say?",
    correct: { id: "o-thanks", text: "Thank you." },
    traps: [
      { id: "o-hello", text: "Hello.", why: "That is how a moment opens, not how it closes.", tag: "wrong_item" },
      { id: "o-excuse", text: "Excuse me.", why: "That reaches for attention. Nothing was being asked for here.", tag: "wrong_item" },
    ],
    short: "Merci.",
    explanation: "One word, and you will hear it every day.",
  }),
  fillSeed({
    id: "p-l1-listen-repeat",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-vous-pouvez-repeter"],
    targets: ["chunk-vous-pouvez-repeter"],
    audio: "Vous pouvez répéter ?",
    prompt: "Listen. What are they asking?",
    correct: { id: "o-again", text: "Can you say that again?" },
    traps: [
      { id: "o-coffee", text: "I would like a coffee.", why: "That is a request for something, not for a repeat.", tag: "meaning_shift" },
      { id: "o-attention", text: "Excuse me.", why: "That opens the moment. This one is asking for something back.", tag: "meaning_shift" },
    ],
    short: "Vous pouvez répéter ?",
    explanation: "The line that keeps a conversation from ending in confusion.",
  }),
  weaveSeed({
    id: "p-l1-dictation-merci",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-merci"],
    targets: ["chunk-merci"],
    audio: "Merci.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci."],
    alternatives: ["Merci", "merci"],
    ifCorrect: "Heard and written. That is a different kind of knowing.",
  }),
  weaveSeed({
    id: "p-l1-dictation-order",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-voudrais", "noun-cafe"],
    audio: "Je voudrais un café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais un café."],
    alternatives: ["je voudrais un café.", "Je voudrais un café"],
    ifCorrect: "You caught the whole request, not just the noun.",
    ifWrong: "Listen again for the two words before the drink.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-order-thank",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-voudrais", "noun-cafe", "chunk-merci"],
    targets: ["chunk-merci"],
    weaveType: "open",
    prompt: "Open it, order, and thank them when it lands.",
    context: "A quiet counter and nobody waiting behind you.",
    answers: ["Bonjour. Je voudrais un café. Merci."],
    alternatives: ["Bonjour, je voudrais un café. Merci.", "Bonjour. Je voudrais un café. Merci !"],
    ifCorrect: "Three moves, and the whole exchange is done politely in five seconds.",
  }),
  weaveSeed({
    id: "p-l1-apply-excuse-then-order",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, then order.",
    context: "They are wiping down the machine with their back to you.",
    answers: ["Excusez-moi. Je voudrais un café."],
    alternatives: ["Excusez-moi, je voudrais un café."],
    ifCorrect: "Excusez-moi reaches somebody who has not seen you. Bonjour would not.",
  }),
  weaveSeed({
    id: "p-l1-apply-polite-repeat-request",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-vous-pouvez-repeter", "chunk-sil-vous-plait"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Ask them to say it again, politely.",
    context: "A formal counter, and they answered faster than you could follow.",
    answers: ["Vous pouvez répéter, s'il vous plaît ?"],
    alternatives: ["Vous pouvez répéter s'il vous plaît ?"],
    ifCorrect: "The tail is what keeps a second ask from sounding like a complaint.",
  }),
  fillSeed({
    id: "p-l1-choice-greet-or-reach",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-bonjour", "chunk-excusez-moi"],
    targets: ["chunk-excusez-moi"],
    prompt: "Their back is turned and they have not seen you. Which one reaches them?",
    correct: { id: "o-exc", text: "Excusez-moi." },
    traps: [
      { id: "o-bon", text: "Bonjour.", why: "Bonjour greets somebody who is already looking at you.", tag: "wrong_register" },
      { id: "o-mer", text: "Merci.", why: "Thanks close something. Nothing has happened yet.", tag: "meaning_shift" },
    ],
    short: "Excusez-moi.",
    explanation: "One opens a moment that has started; the other starts it.",
  }),
  weaveSeed({
    id: "p-l1-dictation-polite-order",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-je-voudrais", "noun-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-sil-vous-plait"],
    audio: "Je voudrais un café, s'il vous plaît.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais un café, s'il vous plaît."],
    alternatives: ["Je voudrais un café s'il vous plaît."],
    ifCorrect: "Four words in the tail, and every one of them is said.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-order-tea",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Greet them, and order the other one.",
    context: "A cold morning and you do not want coffee.",
    answers: ["Bonjour. Je voudrais un thé."],
    alternatives: ["Bonjour, je voudrais un thé."],
    ifCorrect: "Same shape as the coffee. Only the last word moved.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-order-tea-polite",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-sil-vous-plait", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Greet, order the other one, and soften it.",
    context: "A formal counter and an unhurried person behind it.",
    answers: ["Bonjour. Je voudrais un thé, s'il vous plaît."],
    alternatives: ["Bonjour, je voudrais un thé, s'il vous plaît."],
    ifCorrect: "The whole polite frame, and it fits in one breath.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-order-tea",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Reach them, and order the other one.",
    context: "Their back is turned and nobody else is waiting.",
    answers: ["Excusez-moi. Je voudrais un thé."],
    alternatives: ["Excusez-moi, je voudrais un thé."],
    ifCorrect: "Reach first, then ask. That order never changes.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-order-tea-polite",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-sil-vous-plait", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Reach them, order, and soften it.",
    context: "They are clearing tables and have not seen you.",
    answers: ["Excusez-moi. Je voudrais un thé, s'il vous plaît."],
    alternatives: ["Excusez-moi, je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Four moves, one sentence, nobody put out.",
  }),
  weaveSeed({
    id: "p-l1-apply-order-tea-polite",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other one, politely.",
    context: "It is your turn and they are waiting.",
    answers: ["Je voudrais un thé, s'il vous plaît."],
    alternatives: ["Je voudrais un thé s il vous plaît."],
    ifCorrect: "Please before the answer. Thanks comes after it.",
  }),
  weaveSeed({
    id: "p-l1-apply-order-tea-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other one, and close it.",
    context: "A quick stop with a queue behind you.",
    answers: ["Je voudrais un thé. Merci."],
    alternatives: ["Je voudrais un thé, merci."],
    ifCorrect: "Ask, then thank. The shortest complete exchange there is.",
  }),
  weaveSeed({
    id: "p-l1-apply-order-coffee-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "noun-cafe", "chunk-je-voudrais"],
    targets: ["chunk-merci"],
    weaveType: "open",
    prompt: "Order, and close it.",
    context: "You have four minutes and they are fast.",
    answers: ["Je voudrais un café. Merci."],
    alternatives: ["Je voudrais un café, merci."],
    ifCorrect: "Thanking closes the exchange without another word.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-order-tea-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-merci", "chunk-un-the", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Greet, order, and close.",
    context: "The whole thing, start to finish, at a counter.",
    answers: ["Bonjour. Je voudrais un thé. Merci."],
    alternatives: ["Bonjour, je voudrais un thé. Merci."],
    ifCorrect: "Three moves and you have ordered in French.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-then-reach",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-excusez-moi"],
    targets: ["chunk-excusez-moi"],
    weaveType: "mid",
    prompt: "Greet them, then get their attention.",
    context: "A small shop where the owner is in the back.",
    answers: ["Bonjour. Excusez-moi."],
    alternatives: ["Bonjour, excusez-moi."],
    ifCorrect: "Bonjour opens the room. Excusez-moi opens the person.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-and-thank",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-merci"],
    targets: ["chunk-merci"],
    weaveType: "mid",
    prompt: "Get their attention, and thank them.",
    context: "They step aside so you can get past.",
    answers: ["Excusez-moi. Merci."],
    alternatives: ["Excusez-moi, merci."],
    ifCorrect: "Two words that between them handle most of a day.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-and-thank",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-merci"],
    targets: ["chunk-merci"],
    weaveType: "mid",
    prompt: "Greet them, and thank them.",
    context: "They hold the door as you come in.",
    answers: ["Bonjour. Merci."],
    alternatives: ["Bonjour, merci."],
    ifCorrect: "The smallest complete exchange in French.",
  }),
  weaveSeed({
    id: "p-l1-apply-short-order-coffee",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-sil-vous-plait", "noun-cafe"],
    targets: ["chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Order without the full sentence.",
    context: "A busy bar where nobody says more than they need to.",
    answers: ["Un café, s'il vous plaît."],
    alternatives: ["Un café s il vous plaît."],
    ifCorrect: "The short form is not rude here. It is what people say.",
  }),
  weaveSeed({
    id: "p-l1-apply-short-order-tea",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other one, short.",
    context: "Same bar, same queue, different drink.",
    answers: ["Un thé, s'il vous plaît."],
    alternatives: ["Un thé s il vous plaît."],
    ifCorrect: "One word changes and the whole order changes with it.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-short-order",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-sil-vous-plait", "noun-cafe"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Greet them, then order short.",
    context: "The queue moved and it is suddenly your turn.",
    answers: ["Bonjour. Un café, s'il vous plaît."],
    alternatives: ["Bonjour, un café, s'il vous plaît."],
    ifCorrect: "Greeting first is not optional here. It is the order.",
  }),
  weaveSeed({
    id: "p-l1-apply-greet-short-order-tea",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-sil-vous-plait", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Greet them, then order the other one short.",
    context: "Late afternoon, and coffee would keep you up.",
    answers: ["Bonjour. Un thé, s'il vous plaît."],
    alternatives: ["Bonjour, un thé, s'il vous plaît."],
    ifCorrect: "Short does not mean abrupt when bonjour opens it.",
  }),
  weaveSeed({
    id: "p-l1-apply-reach-short-order",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-sil-vous-plait", "noun-cafe"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, then order short.",
    context: "They are talking to someone else and will turn to you.",
    answers: ["Excusez-moi. Un café, s'il vous plaît."],
    alternatives: ["Excusez-moi, un café, s'il vous plaît."],
    ifCorrect: "Reaching first is what makes the short form polite.",
  }),
  weaveSeed({
    id: "p-l1-apply-short-order-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "noun-cafe"],
    targets: ["chunk-merci"],
    weaveType: "open",
    prompt: "Order short, and close it.",
    context: "Two words and a thank you is a whole transaction.",
    answers: ["Un café. Merci."],
    alternatives: ["Un café, merci."],
    ifCorrect: "You can order in French in three words.",
  }),
  weaveSeed({
    id: "p-l1-apply-short-order-tea-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other one short, and close.",
    context: "Same three words, different drink.",
    answers: ["Un thé. Merci."],
    alternatives: ["Un thé, merci."],
    ifCorrect: "The shape holds whatever you put in it.",
  }),
  weaveSeed({
    id: "p-l1-repair-greet-and-ask-again",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Greet them, and ask them to say it again.",
    context: "They answered before you had finished arriving.",
    answers: ["Bonjour. Vous pouvez répéter ?"],
    alternatives: ["Bonjour, vous pouvez répéter ?"],
    ifCorrect: "Greeting first buys you the repeat.",
  }),
  weaveSeed({
    id: "p-l1-repair-ask-again-polite-thanks",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-vous-pouvez-repeter", "chunk-sil-vous-plait", "chunk-merci"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Ask for it again, politely, and thank them.",
    context: "They have already said it twice and you still missed it.",
    answers: ["Vous pouvez répéter, s'il vous plaît ? Merci."],
    alternatives: ["Vous pouvez répéter s il vous plaît ? Merci."],
    ifCorrect: "Asking a third time is fine when you ask it like this.",
  }),
  weaveSeed({
    id: "p-l1-repair-reach-ask-again-polite",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter", "chunk-sil-vous-plait"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Reach them, and ask politely for it again.",
    context: "A formal room where the fast version did not land.",
    answers: ["Excusez-moi. Vous pouvez répéter, s'il vous plaît ?"],
    alternatives: ["Excusez-moi, vous pouvez répéter, s'il vous plaît ?"],
    ifCorrect: "The long polite form is worth its extra syllables here.",
  }),
  weaveSeed({
    id: "p-l1-apply-full-order",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-sil-vous-plait", "chunk-merci", "noun-cafe", "chunk-je-voudrais"],
    targets: ["chunk-merci"],
    weaveType: "open",
    prompt: "Greet, order, soften, and close.",
    context: "The complete counter exchange, with time to say it properly.",
    answers: ["Bonjour. Je voudrais un café, s'il vous plaît. Merci."],
    alternatives: ["Bonjour, je voudrais un café, s'il vous plaît. Merci."],
    ifCorrect: "Four moves. This is the whole of ordering in French.",
  }),
];
