/**
 * L2 practice seeds — being somewhere, and saying so.
 *
 * `word-ici` is a VIA_CARRIER item in the readiness matrix: "ici" alone is not
 * something a beginner says, so it is practised only inside `chunk-je-suis-ici`.
 * No seed here targets it on its own, which is the matrix honoured in content
 * rather than merely asserted in a test.
 *
 * It is also never NAMED in a `required` list, and that is not a style choice.
 * A carried item is never reached on its own, so requiring it made the seed
 * unservable forever. Require the carrier.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-002";

export const L2_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l2-retrieve-je-suis-ici",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "mid",
    prompt: "I'm here.",
    answers: ["Je suis ici."],
    alternatives: ["Je suis ici"],
    ifCorrect: "Two words that place you in a room.",
  }),
  fillSeed({
    id: "p-l2-repair-which-engine",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-suis", "chunk-je-voudrais"],
    targets: ["chunk-je-suis"],
    prompt: "You are saying where you are, not what you want. Which piece fits?",
    before: "Je ",
    after: " ici.",
    correct: { id: "o-suis", text: "suis" },
    traps: [
      {
        id: "o-voudrais",
        text: "voudrais",
        why: "Je voudrais asks for something. Nothing is being requested here.",
        tag: "wrong_item",
      },
      {
        id: "o-merci-eng",
        text: "merci",
        why: "That thanks someone. It cannot carry a sentence.",
        tag: "wrong_item",
      },
    ],
    short: "Je suis ici.",
    explanation: "Je suis states where you are. It is a different engine from je voudrais.",
  }),
  weaveSeed({
    id: "p-l2-produce-arrive-greeting",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici"],
    weaveType: "context",
    prompt: "Greet them, then say you have arrived.",
    context: "You are expected. Someone looks up as you come in.",
    answers: ["Bonjour, je suis ici."],
    alternatives: ["Bonjour. Je suis ici."],
    ifCorrect: "Greeting, then placement. That is a whole arrival.",
  }),
  weaveSeed({
    id: "p-l2-produce-arrive-excuse",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-suis-ici"],
    targets: ["chunk-excusez-moi", "chunk-je-suis-ici"],
    weaveType: "context",
    prompt: "Reach them, then say you have arrived.",
    context: "The room is busy and nobody has noticed you in the doorway.",
    answers: ["Excusez-moi, je suis ici."],
    alternatives: ["Excusez-moi. Je suis ici."],
    ifCorrect: "Same sentence, different way in.",
  }),
  weaveSeed({
    id: "p-l2-apply-called-from-next-room",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Answer so they know where you are.",
    context: "Someone is calling for you from the next room. They cannot see you.",
    answers: ["Je suis ici."],
    alternatives: ["Je suis ici"],
    ifCorrect: "They can find you now. That is the whole job of the sentence.",
  }),
  weaveSeed({
    id: "p-l2-apply-arrive-and-order",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-je-suis-ici",
      "chunk-je-voudrais",
      "noun-cafe",
      "chunk-sil-vous-plait",
    ],
    targets: ["chunk-je-suis-ici", "chunk-je-voudrais", "noun-cafe"],
    weaveType: "open",
    prompt: "Arrive, then ask for what you want.",
    context: "You have just walked in where you were expected, and there is coffee going.",
    answers: ["Bonjour, je suis ici. Je voudrais un café, s'il vous plaît."],
    alternatives: ["Bonjour. Je suis ici. Je voudrais un café, s'il vous plaît."],
    ifCorrect: "Two engines, one moment. Nothing new was needed.",
    ifWrong: "Your meaning lands. Place yourself first, then ask.",
  }),
  weaveSeed({
    id: "p-l2-apply-arrive-and-order-tea",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-je-suis-ici", "chunk-un-the"],
    weaveType: "open",
    prompt: "Arrive, then order the other drink.",
    context: "Same arrival, and today it is tea you want.",
    answers: ["Bonjour, je suis ici. Je voudrais un thé, s'il vous plaît."],
    alternatives: ["Bonjour. Je suis ici. Je voudrais un thé, s'il vous plaît."],
    ifCorrect: "The frame held and only the thing inside it changed.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l2-build-arrive",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici"],
    prompt: "Put the arrival together.",
    context: "You are expected, and someone looks up as you come in.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour,", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "je suis ici.", answerIndex: 1 },
      { itemId: "chunk-merci", text: "merci" },
    ],
    target: "Bonjour, je suis ici.",
    ifCorrect: "Greeting, then placement. A whole arrival in two pieces.",
  }),
  buildSeed({
    id: "p-l2-build-arrive-and-order",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-je-suis-ici",
      "chunk-je-voudrais",
      "noun-cafe",
      "chunk-sil-vous-plait",
    ],
    targets: ["chunk-je-suis-ici", "chunk-je-voudrais", "noun-cafe"],
    prompt: "Arrive, then ask for what you want.",
    context: "You have walked in where you were expected, and there is coffee going.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour,", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "je suis ici.", answerIndex: 1 },
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 2 },
      { itemId: "noun-cafe", text: "un café,", answerIndex: 3 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît.", answerIndex: 4 },
      { itemId: "chunk-merci", text: "merci." },
    ],
    target: "Bonjour, je suis ici. Je voudrais un café, s'il vous plaît.",
    ifCorrect: "Two engines in one moment, and neither one is new.",
    ifWrong: "Place yourself first, then ask.",
  }),
  fillSeed({
    id: "p-l2-listen-je-suis-ici",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    audio: "Je suis ici.",
    prompt: "Listen. What did they say?",
    correct: { id: "o-here", text: "I'm here." },
    traps: [
      { id: "o-question", text: "I have a question.", why: "That is something you have, not where you are.", tag: "meaning_shift" },
      { id: "o-want", text: "I would like a coffee.", why: "That asks for something. Nothing is being asked for here.", tag: "meaning_shift" },
    ],
    short: "Je suis ici.",
    explanation: "Two words that place you in a room.",
  }),
  weaveSeed({
    id: "p-l2-dictation-je-suis-ici",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    audio: "Je suis ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je suis ici."],
    alternatives: ["Je suis ici", "je suis ici."],
    ifCorrect: "Heard, and written back whole.",
  }),
  weaveSeed({
    id: "p-l2-dictation-arrival",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici"],
    audio: "Bonjour, je suis ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Bonjour, je suis ici."],
    alternatives: ["Bonjour. Je suis ici.", "bonjour, je suis ici."],
    ifCorrect: "Both halves of the arrival, caught first time.",
  }),
  fillSeed({
    id: "p-l2-fill-which-piece-places-you",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    prompt: "Which piece says WHERE you are?",
    before: "Je suis ",
    after: ".",
    correct: { id: "o-ici", text: "ici" },
    traps: [
      { id: "o-merci-place", text: "merci", why: "That thanks someone. It is not a place.", tag: "wrong_item" },
      { id: "o-bonjour-place", text: "bonjour", why: "That greets someone. It is not a place either.", tag: "wrong_item" },
    ],
    short: "Je suis ici.",
    explanation: "Ici is the here. It never travels alone.",
  }),
  weaveSeed({
    id: "p-l2-apply-here-not-there",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-suis-ici"],
    targets: ["chunk-excusez-moi", "chunk-je-suis-ici"],
    weaveType: "context",
    prompt: "Reach them, then say you have arrived.",
    context: "They are looking the other way and the room is loud.",
    answers: ["Excusez-moi, je suis ici."],
    alternatives: ["Excusez-moi. Je suis ici."],
    ifCorrect: "The same sentence, a different way in.",
  }),
  weaveSeed({
    id: "p-l2-apply-arrive-and-greet-first",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Greet them, then say you have arrived.",
    context: "You are expected, and the person at the desk has not looked up yet.",
    answers: ["Bonjour. Je suis ici."],
    alternatives: ["Bonjour, je suis ici.", "Bonjour ! Je suis ici."],
    ifCorrect: "The greeting opens the moment; the announcement fills it.",
  }),
  weaveSeed({
    id: "p-l2-apply-arrive-and-order-tea-politely",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-voudrais", "chunk-un-the", "chunk-sil-vous-plait"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Say you have arrived, then order, politely.",
    context: "You said you would meet them here, and today you do not want coffee.",
    answers: ["Je suis ici. Je voudrais un thé, s'il vous plaît."],
    alternatives: ["Je suis ici, je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Two moves, and the polite tail belongs on the second one.",
  }),
  weaveSeed({
    id: "p-l2-apply-thanks-for-waiting",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-merci"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Announce yourself, and thank them for waiting.",
    context: "You are late and they stayed.",
    answers: ["Je suis ici. Merci !"],
    alternatives: ["Je suis ici, merci !", "Je suis ici. Merci."],
    ifCorrect: "Arriving late has a small ceremony, and this is it.",
  }),
  fillSeed({
    id: "p-l2-choice-announce-or-order",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-suis-ici"],
    prompt: "They cannot see you and are waiting. Which do you say first?",
    correct: { id: "o-here", text: "Je suis ici." },
    traps: [
      { id: "o-order", text: "Je voudrais un café.", why: "Ordering before they know you are there skips a step.", tag: "wrong_register" },
      { id: "o-hi", text: "Bonjour.", why: "Not wrong, but it does not tell them where you are.", tag: "meaning_shift" },
    ],
    short: "Je suis ici.",
    explanation: "Being findable comes before being served.",
  }),
  fillSeed({
    id: "p-l2-listen-here-or-ordering",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-suis-ici"],
    audio: "Je suis ici.",
    prompt: "Listen. Are they placing themselves, or asking for something?",
    correct: { id: "o-place", text: "Placing themselves. They are here." },
    traps: [
      { id: "o-want", text: "Asking for something.", why: "That would be je voudrais. Je suis places rather than requests.", tag: "meaning_shift" },
      { id: "o-greet", text: "Greeting you.", why: "A greeting is bonjour. This one carries information.", tag: "meaning_shift" },
    ],
    short: "Je suis ici.",
    explanation: "Je suis is the engine that puts you somewhere.",
  }),
  buildSeed({
    id: "p-l2-build-greet-arrive-order",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-je-voudrais", "noun-cafe"],
    targets: ["chunk-je-suis-ici"],
    prompt: "Assemble the whole arrival.",
    context: "Expected, on time, and there is coffee going.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 2 },
      { itemId: "noun-cafe", text: "un café.", answerIndex: 3 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Bonjour. Je suis ici. Je voudrais un café.",
    ifCorrect: "Greet, announce, order. Three moves that never change order.",
    ifWrong: "Right pieces. The greeting opens it.",
  }),
  weaveSeed({
    id: "p-l2-dictation-greet-and-arrive",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-je-suis-ici"],
    audio: "Bonjour. Je suis ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Bonjour. Je suis ici."],
    alternatives: ["Bonjour, je suis ici."],
    ifCorrect: "The two-move arrival, written out.",
  }),
  weaveSeed({
    id: "p-l2-retrieve-excuse-and-announce",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-suis-ici"],
    targets: ["chunk-excusez-moi"],
    weaveType: "mid",
    prompt: "Reach them, then say you are here.",
    context: "A busy doorway and nobody has noticed you.",
    answers: ["Excusez-moi, je suis ici."],
    alternatives: ["Excusez-moi. Je suis ici."],
    ifCorrect: "Getting their attention is the half people skip.",
  }),
];
