/**
 * L3 practice seeds — saying no, and saying not-here.
 *
 * The negation architecture is the first place a learner can be confidently
 * wrong: `je ne suis pas` and `ce n'est pas` are the same move about different
 * subjects, and choosing between them is the real work. Two seeds here carry
 * `repairsTag: "negation"` so a miss anywhere on that architecture can pull a
 * matching repair into the same session.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-003";

export const L3_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l3-retrieve-je-ne-comprends-pas",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "mid",
    prompt: "I don't understand.",
    answers: ["Je ne comprends pas."],
    alternatives: ["Je ne comprends pas"],
    ifCorrect: "The most useful sentence you own.",
  }),
  fillSeed({
    id: "p-l3-repair-verb-in-sandwich",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-je-suis"],
    targets: ["chunk-je-ne-suis-pas"],
    tags: ["negation", "ne-pas"],
    repairs: "negation",
    prompt: "You want to say you are not there. Which word sits between the two pieces?",
    before: "Je ne ",
    after: " pas ici.",
    correct: { id: "o-suis-neg", text: "suis" },
    traps: [
      {
        id: "o-voudrais-neg",
        text: "voudrais",
        why: "Je voudrais asks for something. Here you are saying where you are not.",
        tag: "wrong_item",
      },
      {
        id: "o-comprends-neg",
        text: "comprends",
        why: "That says you did not follow, which is a different thing from not being there.",
        tag: "meaning_shift",
      },
    ],
    short: "Je ne suis pas ici.",
    explanation: "The verb goes between the two pieces: je ne suis pas.",
  }),
  fillSeed({
    id: "p-l3-repair-which-negation-frame",
    operation: "repair",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-ne-suis-pas"],
    targets: ["chunk-ce-n-est-pas"],
    tags: ["negation"],
    repairs: "negation",
    prompt: "You are talking about the ROOM, not about yourself. Which opening fits?",
    after: " ici.",
    correct: { id: "o-ce-nest-pas", text: "Ce n'est pas" },
    traps: [
      {
        id: "o-je-ne-suis-pas",
        text: "Je ne suis pas",
        why: "That says YOU are not here. The room is what is wrong, not you.",
        tag: "meaning_shift",
      },
      {
        id: "o-non-merci-frame",
        text: "Non merci",
        why: "That turns down an offer. Nobody offered you anything.",
        tag: "wrong_item",
      },
    ],
    short: "Ce n'est pas ici.",
    explanation: "Ce n'est pas talks about a thing or a place; je ne suis pas talks about you.",
  }),
  fillSeed({
    id: "p-l3-repair-decline-politely",
    operation: "repair",
    difficulty: "easy",
    surface: "choice",
    lesson: L,
    required: ["chunk-non-merci", "chunk-merci"],
    targets: ["chunk-non-merci"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "Someone offers you something you do not want. Refuse politely.",
    correct: { id: "o-non-merci", text: "Non merci." },
    traps: [
      {
        id: "o-merci-only",
        text: "Merci.",
        why: "On its own that reads as yes, please. You will be handed the thing.",
        tag: "meaning_shift",
      },
      {
        id: "o-oui-merci",
        text: "Oui merci.",
        why: "That accepts it warmly, which is the opposite of what you meant.",
        tag: "meaning_shift",
      },
    ],
    short: "Non merci.",
    explanation: "Non does the refusing; merci keeps it warm.",
  }),
  weaveSeed({
    id: "p-l3-produce-not-this-room",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "context",
    prompt: "Tell them this is not the place.",
    context: "Someone stops in your doorway looking for a meeting. It is not in this room.",
    answers: ["Ce n'est pas ici."],
    alternatives: ["Ce n'est pas ici"],
    ifCorrect: "Short, clear, and it sends them on rather than away.",
  }),
  weaveSeed({
    id: "p-l3-apply-answer-no",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-non", "chunk-je-ne-suis-pas"],
    targets: ["chunk-non", "chunk-je-ne-suis-pas"],
    weaveType: "context",
    prompt: "Answer them, then say where you are not.",
    context: "They call through the door to ask whether you are in the meeting room. You are not.",
    answers: ["Non, je ne suis pas ici."],
    alternatives: ["Non. Je ne suis pas ici."],
    ifCorrect: "Answer first, then the detail. That is the shape of a real reply.",
  }),
  weaveSeed({
    id: "p-l3-apply-answer-yes",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-je-suis-ici"],
    targets: ["chunk-oui", "chunk-je-suis-ici"],
    weaveType: "context",
    prompt: "Answer them, then say where you are.",
    context: "The same voice, the same question, and this time you ARE in the room.",
    answers: ["Oui, je suis ici."],
    alternatives: ["Oui. Je suis ici."],
    ifCorrect: "Same shape, opposite answer. The frame did not move.",
  }),
  weaveSeed({
    id: "p-l3-apply-not-that-place",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non", "chunk-ce-n-est-pas"],
    targets: ["chunk-non", "chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Answer them, then correct the place.",
    context: "They point at the door beside you and ask whether that is the one. It is not.",
    answers: ["Non, ce n'est pas ici."],
    alternatives: ["Non. Ce n'est pas ici."],
    ifCorrect: "You answered the person and fixed the room in one line.",
    ifWrong: "Your meaning lands. Answer first, then say which place is wrong.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l3-build-answer-no",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-non", "chunk-je-ne-suis-pas", "chunk-je-suis-ici"],
    targets: ["chunk-non", "chunk-je-ne-suis-pas"],
    prompt: "Put the answer together.",
    context: "They call through the door asking whether you are in there. You are not.",
    tiles: [
      { itemId: "chunk-non", text: "Non,", answerIndex: 0 },
      { itemId: "chunk-je-ne-suis-pas", text: "je ne suis pas", answerIndex: 1 },
      { itemId: "word-ici", text: "ici.", answerIndex: 2 },
      { itemId: "chunk-oui", text: "oui" },
    ],
    target: "Non, je ne suis pas ici.",
    ifCorrect: "Answer first, then the detail. That is the shape of a real reply.",
    ifWrong: "The answer comes first, then what is not the case.",
  }),
  buildSeed({
    id: "p-l3-build-not-that-place",
    operation: "repair",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-non", "chunk-ce-n-est-pas", "chunk-je-suis-ici", "chunk-je-ne-suis-pas"],
    targets: ["chunk-ce-n-est-pas"],
    tags: ["negation"],
    repairs: "negation",
    prompt: "Build the answer about the ROOM, not about you.",
    context: "They point at the door beside you and ask whether that is the one.",
    tiles: [
      { itemId: "chunk-non", text: "Non,", answerIndex: 0 },
      { itemId: "chunk-ce-n-est-pas", text: "ce n'est pas", answerIndex: 1 },
      { itemId: "word-ici", text: "ici.", answerIndex: 2 },
      { itemId: "chunk-je-ne-suis-pas", text: "je ne suis pas" },
    ],
    target: "Non, ce n'est pas ici.",
    ifCorrect: "Ce n'est pas talks about a place. Je ne suis pas talks about you.",
    ifWrong: "The room is what is wrong here, not you.",
  }),
  fillSeed({
    id: "p-l3-listen-not-understand",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    audio: "Je ne comprends pas.",
    prompt: "Listen. What did they say?",
    correct: { id: "o-dont-understand", text: "I don't understand." },
    traps: [
      { id: "o-not-here-l3", text: "It's not here.", why: "That is about a place. This one is about following what was said.", tag: "meaning_shift" },
      { id: "o-no-thanks-l3", text: "No thanks.", why: "That turns something down. Nothing was offered.", tag: "meaning_shift" },
    ],
    short: "Je ne comprends pas.",
    explanation: "The most useful sentence you own, heard rather than read.",
  }),
  fillSeed({
    id: "p-l3-listen-which-negation",
    operation: "repair",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-ne-suis-pas"],
    targets: ["chunk-ce-n-est-pas"],
    tags: ["negation"],
    repairs: "negation",
    audio: "Ce n'est pas ici.",
    prompt: "Listen carefully. Who or what is this about?",
    correct: { id: "o-about-place", text: "It's not here." },
    traps: [
      { id: "o-about-me", text: "I'm not here.", why: "Close, and the wrong subject. That one starts je ne suis.", tag: "meaning_shift" },
      { id: "o-here", text: "It's here.", why: "The opposite. Listen for the two pieces around the verb.", tag: "meaning_shift" },
    ],
    short: "Ce n'est pas ici.",
    explanation: "Two sentences that sound alike and mean different things. The subject is the tell.",
  }),
  weaveSeed({
    id: "p-l3-dictation-not-understand",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    audio: "Je ne comprends pas.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je ne comprends pas."],
    alternatives: ["je ne comprends pas.", "Je ne comprends pas"],
    ifCorrect: "Four pieces, and you caught the two that do the negating.",
    ifWrong: "Listen for the small word before the verb, and the one after it.",
  }),
  weaveSeed({
    id: "p-l3-dictation-not-here",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-suis-ici"],
    targets: ["chunk-ce-n-est-pas"],
    audio: "Ce n'est pas ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Ce n'est pas ici."],
    alternatives: ["ce n'est pas ici.", "Ce n'est pas ici"],
    ifCorrect: "The apostrophe and all. That is the written shape of the sound.",
    ifWrong: "The middle runs together when spoken: ce n'est.",
  }),
  weaveSeed({
    id: "p-l3-apply-no-and-not-following",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-non", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Answer them, then say why.",
    context: "They ask whether that was clear. It was not.",
    answers: ["Non, je ne comprends pas."],
    alternatives: ["Non. Je ne comprends pas.", "Non je ne comprends pas"],
    ifCorrect: "Answering first, then explaining, is the order that keeps it honest.",
  }),
  weaveSeed({
    id: "p-l3-apply-reach-and-say-lost",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Reach them, then say it went past you.",
    context: "They have moved on and you are still two sentences behind.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas."],
    ifCorrect: "Saying so is better than nodding and hoping.",
  }),
  weaveSeed({
    id: "p-l3-apply-decline-then-explain",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-je-ne-suis-pas"],
    targets: ["chunk-je-ne-suis-pas"],
    weaveType: "open",
    prompt: "Turn it down, then tell them they have the wrong person's room.",
    context: "They offer you the papers for whoever is in the meeting room. You are not.",
    answers: ["Non merci. Je ne suis pas ici."],
    alternatives: ["Non merci, je ne suis pas ici."],
    ifCorrect: "Je ne suis pas ici is about the PLACE they think you are in.",
  }),
  weaveSeed({
    id: "p-l3-apply-correct-the-room-politely",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Reach them before they open it, and tell them it is the wrong one.",
    context: "Their hand is already on a handle and the room behind it is not theirs.",
    answers: ["Excusez-moi, ce n'est pas ici."],
    alternatives: ["Excusez-moi. Ce n'est pas ici.", "Excusez-moi, ce n est pas ici."],
    ifCorrect: "Catching them before the door is worth the interruption.",
  }),
  weaveSeed({
    id: "p-l3-apply-yes-and-place",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-je-suis-ici", "chunk-bonjour"],
    targets: ["chunk-oui"],
    weaveType: "open",
    prompt: "Greet them, answer, and say where you are.",
    context: "A voice from the next room, looking for you.",
    answers: ["Bonjour. Oui, je suis ici."],
    alternatives: ["Bonjour, oui, je suis ici.", "Bonjour ! Oui, je suis ici."],
    ifCorrect: "Three small moves, and nobody has to come looking.",
  }),
  fillSeed({
    id: "p-l3-choice-refuse-or-answer",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-non", "chunk-non-merci"],
    targets: ["chunk-non-merci"],
    prompt: "They are holding out a cup. Which is right?",
    correct: { id: "o-nm", text: "Non merci." },
    traps: [
      { id: "o-n", text: "Non.", why: "Bare non answers a question. Against an offer it lands hard.", tag: "wrong_register" },
      { id: "o-o", text: "Oui.", why: "That accepts it, which is the opposite.", tag: "meaning_shift" },
    ],
    short: "Non merci.",
    explanation: "An offer takes merci with the non. A question does not.",
  }),
  fillSeed({
    id: "p-l3-listen-person-or-place",
    operation: "repair", difficulty: "hard", surface: "listen", lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    audio: "Ce n'est pas ici.",
    prompt: "Listen. Are they talking about themselves, or about the place?",
    correct: { id: "o-place", text: "About the place." },
    traps: [
      { id: "o-self", text: "About themselves.", why: "That would be je ne suis pas ici. Ce points at the room.", tag: "meaning_shift" },
      { id: "o-ask", text: "They asked a question.", why: "Nothing here is a question.", tag: "meaning_shift" },
    ],
    short: "Ce n'est pas ici.",
    explanation: "Both wrap the middle the same way. The opening word decides who it is about.",
  }),
  weaveSeed({
    id: "p-l3-dictation-no-and-lost",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-non", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    audio: "Non, je ne comprends pas.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Non, je ne comprends pas."],
    alternatives: ["Non. Je ne comprends pas.", "Non je ne comprends pas"],
    ifCorrect: "The answer word, then the negative wrapping.",
  }),
  weaveSeed({
    id: "p-l3-apply-confirm-place",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "mid",
    prompt: "Confirm the place.",
    context: "They ask whether this is it. It is.",
    answers: ["C'est ici."],
    alternatives: ["C est ici."],
    ifCorrect: "Two words settle it.",
  }),
  weaveSeed({
    id: "p-l3-apply-wrong-and-lost",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say it is the wrong place, and that you are lost.",
    context: "The directions were confident and none of them worked.",
    answers: ["Ce n'est pas ici. Je ne comprends pas."],
    alternatives: ["Ce n est pas ici. Je ne comprends pas."],
    ifCorrect: "Admitting both at once is faster than pretending to one.",
  }),
  weaveSeed({
    id: "p-l3-apply-decline-and-lost",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn down more help, and say why.",
    context: "They keep offering and none of it is landing.",
    answers: ["Non merci. Je ne comprends pas."],
    alternatives: ["Non merci, je ne comprends pas."],
    ifCorrect: "Refusing more of what is not working is not rude.",
  }),
  weaveSeed({
    id: "p-l3-apply-decline-wrong-place",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Turn it down, and say it is the wrong place.",
    context: "They offer to show you into a room you do not want.",
    answers: ["Non merci. Ce n'est pas ici."],
    alternatives: ["Non merci, ce n'est pas ici."],
    ifCorrect: "A refusal with the reason attached ends the conversation kindly.",
  }),
  weaveSeed({
    id: "p-l3-apply-not-me-and-lost",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-suis-pas"],
    weaveType: "open",
    prompt: "Say you are not in there, and that you are lost.",
    context: "They are calling for you from a room you have never been in.",
    answers: ["Je ne suis pas ici. Je ne comprends pas."],
    alternatives: ["Je ne suis pas ici, je ne comprends pas."],
    ifCorrect: "Two negatives, and between them the whole situation.",
  }),
  weaveSeed({
    id: "p-l3-apply-reach-and-deny",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-suis-pas"],
    targets: ["chunk-je-ne-suis-pas"],
    weaveType: "open",
    prompt: "Interrupt, and say you are not in there.",
    context: "They are searching a room you left ten minutes ago.",
    answers: ["Excusez-moi. Je ne suis pas ici."],
    alternatives: ["Excusez-moi, je ne suis pas ici."],
    ifCorrect: "Answering at all is what stops them searching.",
  }),
  weaveSeed({
    id: "p-l3-apply-reach-and-decline",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-non-merci"],
    targets: ["chunk-non-merci"],
    weaveType: "mid",
    prompt: "Get their attention, and turn it down.",
    context: "Someone is handing out something you do not want.",
    answers: ["Excusez-moi. Non merci."],
    alternatives: ["Excusez-moi, non merci."],
    ifCorrect: "Refusing politely still needs their attention first.",
  }),
  weaveSeed({
    id: "p-l3-repair-greet-and-lost",
    operation: "repair", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Greet them, and say you did not follow.",
    context: "They started explaining before you had finished arriving.",
    answers: ["Bonjour. Je ne comprends pas."],
    alternatives: ["Bonjour, je ne comprends pas."],
    ifCorrect: "Greeting first turns an admission into a conversation.",
  }),
  weaveSeed({
    id: "p-l3-apply-greet-and-correct",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Greet them, and correct it.",
    context: "They open with the wrong assumption about why you are there.",
    answers: ["Bonjour. Ce n'est pas ici."],
    alternatives: ["Bonjour, ce n'est pas ici."],
    ifCorrect: "Correcting early costs less than correcting later.",
  }),
  weaveSeed({
    id: "p-l3-apply-yes-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-merci"],
    targets: ["chunk-oui"],
    weaveType: "mid",
    prompt: "Agree, and thank them.",
    context: "They ask whether you found it. You did.",
    answers: ["Oui. Merci."],
    alternatives: ["Oui, merci."],
    ifCorrect: "Two words each, and the exchange is complete.",
  }),
  weaveSeed({
    id: "p-l3-apply-no-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-non", "chunk-merci"],
    targets: ["chunk-non"],
    weaveType: "mid",
    prompt: "Answer, and soften it.",
    context: "They ask whether you need anything else. You do not.",
    answers: ["Non. Merci."],
    alternatives: ["Non, merci."],
    ifCorrect: "A no with merci after it is a different thing from a bare no.",
  }),
  weaveSeed({
    id: "p-l3-apply-confirm-and-thank",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est", "chunk-merci"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Confirm you found it, and thank them.",
    context: "They walked you here to be sure.",
    answers: ["C'est ici. Merci."],
    alternatives: ["C est ici. Merci."],
    ifCorrect: "Confirming out loud tells them their directions worked.",
  }),
  weaveSeed({
    id: "p-l3-apply-wrong-and-thank",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-merci"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Say it is the wrong place, and thank them anyway.",
    context: "They tried, and it turned out to be the other building.",
    answers: ["Ce n'est pas ici. Merci."],
    alternatives: ["Ce n est pas ici. Merci."],
    ifCorrect: "They helped even though it did not work. The thanks is still owed.",
  }),
  weaveSeed({
    id: "p-l3-repair-lost-and-thank",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-merci"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say you did not follow, and thank them anyway.",
    context: "Third attempt, and neither of you has more time.",
    answers: ["Je ne comprends pas. Merci."],
    alternatives: ["Je ne comprends pas, merci."],
    ifCorrect: "Thanking for a failed attempt keeps the door open.",
  }),
  weaveSeed({
    id: "p-l3-apply-deny-and-thank",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-merci"],
    targets: ["chunk-je-ne-suis-pas"],
    weaveType: "open",
    prompt: "Say you are not in there, and close it politely.",
    context: "They checked the wrong room on your behalf.",
    answers: ["Je ne suis pas ici. Merci."],
    alternatives: ["Je ne suis pas ici, merci."],
    ifCorrect: "Correcting and thanking in the same breath costs nothing.",
  }),
  weaveSeed({
    id: "p-l3-apply-yes-here-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-oui", "chunk-je-suis-ici", "chunk-merci"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Confirm you are there, and thank them.",
    context: "They call your name across the room to check.",
    answers: ["Oui, je suis ici. Merci."],
    alternatives: ["Oui je suis ici. Merci."],
    ifCorrect: "Answering once properly saves them asking twice.",
  }),
];
