/**
 * L4 practice seeds — the other engine.
 *
 * `noun-faim` and `noun-question` are VIA_CARRIER items: "faim" is not
 * something a beginner says, "J'ai faim." is. Every seed here targets the
 * carrier chunk, never the bare noun.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-004";

export const L4_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l4-retrieve-j-ai-faim",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "mid",
    prompt: "I'm hungry.",
    answers: ["J'ai faim."],
    alternatives: ["J'ai faim", "Jai faim."],
    ifCorrect: "French has you HAVE hunger. That is the whole idea.",
  }),
  weaveSeed({
    id: "p-l4-retrieve-j-ai-une-question",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "mid",
    prompt: "I have a question.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "The sentence that opens almost every room you walk into.",
  }),
  fillSeed({
    id: "p-l4-repair-have-not-be",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-je-suis"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis", "avoir-vs-etre"],
    repairs: "j-ai-vs-je-suis",
    prompt: "You want to say you are hungry. Which engine does French use?",
    after: " faim.",
    correct: { id: "o-jai", text: "J'ai" },
    traps: [
      {
        id: "o-je-suis-faim",
        text: "Je suis",
        why: "That is the English shape. In French hunger is something you have, not something you are.",
        tag: "wrong_item",
      },
      {
        id: "o-je-voudrais-faim",
        text: "Je voudrais",
        why: "That asks for something. You are describing how you feel.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai faim.",
    explanation: "Hunger, questions and ideas all arrive on j'ai.",
  }),
  fillSeed({
    id: "p-l4-repair-which-kind-of-have",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-j-ai-faim", "noun-idee"],
    targets: ["chunk-j-ai-une-question"],
    prompt: "The room is waiting and you need one thing cleared up. What do you say?",
    correct: { id: "o-question", text: "J'ai une question." },
    traps: [
      {
        id: "o-faim",
        text: "J'ai faim.",
        why: "True, perhaps, but it does not get your question answered.",
        tag: "meaning_shift",
      },
      {
        id: "o-idee",
        text: "J'ai une idée.",
        why: "That offers something. You are asking for something.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une question.",
    explanation: "Same engine, three different things to have. Pick the one you mean.",
  }),
  weaveSeed({
    id: "p-l4-produce-open-a-question",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-j-ai-une-question"],
    weaveType: "context",
    prompt: "Greet them, then open your question.",
    context: "You have found the right person and they have a moment.",
    answers: ["Bonjour, j'ai une question."],
    alternatives: ["Bonjour. J'ai une question."],
    ifCorrect: "Polite opening, then the reason you came.",
  }),
  weaveSeed({
    id: "p-l4-produce-cut-in-with-an-idea",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    weaveType: "context",
    prompt: "Cut in politely, then say what you have.",
    context: "The room has been stuck on the same problem for ten minutes, and something occurs to you.",
    answers: ["Excusez-moi, j'ai une idée."],
    alternatives: ["Excusez-moi. J'ai une idée."],
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  weaveSeed({
    id: "p-l4-apply-here-and-hungry",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you have arrived, then say you have not eaten.",
    context: "You get in late. They ask whether you want anything before you start.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim."],
    ifCorrect: "Two engines in two short sentences, and neither one is new.",
    ifWrong: "Your meaning lands. One sentence for where you are, one for what you have.",
  }),
  weaveSeed({
    id: "p-l4-apply-question-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say what you need.",
    context: "They finish explaining, look at you, and wait. One thing did not land.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "You did not need the words handed to you. That is what owning a sentence feels like.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l4-build-here-and-hungry",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Put both engines in one moment.",
    context: "You get in late, and they ask whether you want anything first.",
    tiles: [
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 0 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question." },
    ],
    target: "Je suis ici. J'ai faim.",
    ifCorrect: "One sentence for where you are, one for what you have.",
    ifWrong: "Place yourself first, then say what you have.",
  }),
  buildSeed({
    id: "p-l4-build-cut-in-with-an-idea",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    prompt: "Build the interruption.",
    context: "The room has been stuck for ten minutes and something occurs to you.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-j-ai", text: "j'ai", answerIndex: 1 },
      { itemId: "noun-idee", text: "une idée.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "faim" },
    ],
    target: "Excusez-moi, j'ai une idée.",
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  fillSeed({
    id: "p-l4-listen-which-have",
    operation: "repair",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    audio: "J'ai faim.",
    prompt: "Listen. What do they have?",
    correct: { id: "o-hungry", text: "I'm hungry." },
    traps: [
      { id: "o-have-question", text: "I have a question.", why: "Same engine, different thing on the end. Listen past the j'ai.", tag: "meaning_shift" },
      { id: "o-am-here", text: "I'm here.", why: "That is the other engine entirely: je suis, not j'ai.", tag: "wrong_item" },
    ],
    short: "J'ai faim.",
    explanation: "Everything after j'ai is what changes. That is where to listen.",
  }),
  weaveSeed({
    id: "p-l4-dictation-hungry",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai faim."],
    alternatives: ["j'ai faim.", "J'ai faim"],
    ifCorrect: "Two words, one apostrophe, and it is yours.",
  }),
  weaveSeed({
    id: "p-l4-dictation-question",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    audio: "J'ai une question.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une question."],
    alternatives: ["j'ai une question.", "J'ai une question"],
    ifCorrect: "The small word in the middle is easy to lose. You kept it.",
    ifWrong: "There is a package word between the engine and the noun.",
  }),
  fillSeed({
    id: "p-l4-fill-what-you-have",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Which engine carries a question?",
    after: " une question.",
    correct: { id: "o-jai-q", text: "J'ai" },
    traps: [
      { id: "o-jesuis-q", text: "Je suis", why: "That says you ARE a question, which is not a thing anyone says.", tag: "wrong_item" },
      { id: "o-jevoudrais-q", text: "Je voudrais", why: "That asks for a question rather than having one.", tag: "meaning_shift" },
    ],
    short: "J'ai une question.",
    explanation: "Questions are had, not been.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-and-question",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Greet them, then say what you came for.",
    context: "Somebody behind a desk with a moment to spare.",
    answers: ["Bonjour. J'ai une question."],
    alternatives: ["Bonjour, j'ai une question.", "Bonjour. J ai une question."],
    ifCorrect: "The greeting is what buys the question its hearing.",
  }),
  weaveSeed({
    id: "p-l4-apply-hungry-and-here",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you have arrived, then say how you are.",
    context: "A long trip, a late arrival, and nobody has offered you anything.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim.", "Je suis ici. J ai faim."],
    ifCorrect: "French HAS hunger where English IS hungry. Two engines, two jobs.",
  }),
  weaveSeed({
    id: "p-l4-apply-cut-in-with-idea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Cut in, and say what you have.",
    context: "The room has been stuck on the same problem and something has occurred to you.",
    answers: ["Excusez-moi, j'ai une idée."],
    alternatives: ["Excusez-moi. J'ai une idée.", "Excusez-moi, j ai une idée."],
    ifCorrect: "An idea is worth the interruption if you open it properly.",
  }),
  weaveSeed({
    id: "p-l4-repair-decline-because-question",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-une-question"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down, and say what you actually need.",
    context: "They offer you a seat and a drink. You only came to ask one thing.",
    answers: ["Non merci. J'ai une question."],
    alternatives: ["Non merci, j'ai une question."],
    ifCorrect: "Redirecting is kinder than a bare refusal.",
  }),
  fillSeed({
    id: "p-l4-choice-have-or-be",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-suis"],
    targets: ["chunk-j-ai-faim"],
    prompt: "You want to say you are hungry. Which engine does French use?",
    correct: { id: "o-ai", text: "J'ai faim." },
    traps: [
      { id: "o-suis", text: "Je suis faim.", why: "The commonest early slip. French HAS hunger, it does not BE it.", tag: "wrong_item" },
      { id: "o-ici", text: "Je suis ici.", why: "That places you somewhere and says nothing about hunger.", tag: "meaning_shift" },
    ],
    short: "J'ai faim.",
    explanation: "Two engines. Je suis for where and who, j'ai for what you carry.",
  }),
  fillSeed({
    id: "p-l4-listen-what-do-they-carry",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    audio: "J'ai une question.",
    prompt: "Listen. What have they got?",
    correct: { id: "o-q", text: "A question." },
    traps: [
      { id: "o-faim", text: "Hunger.", why: "That would be j'ai faim. The word after j'ai is the whole message.", tag: "meaning_shift" },
      { id: "o-idee", text: "An idea.", why: "Close, and a different noun. Listen past the j'ai.", tag: "meaning_shift" },
    ],
    short: "J'ai une question.",
    explanation: "J'ai is a container. What matters is what it is carrying.",
  }),
  buildSeed({
    id: "p-l4-build-greet-and-ask",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    prompt: "Assemble the opening.",
    context: "One thing to ask, and a stranger to ask it of.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Bonjour. J'ai une question.",
    ifCorrect: "Greeting first, always.",
    ifWrong: "Right pieces. Open before you ask.",
  }),
  weaveSeed({
    id: "p-l4-dictation-hungry-and-here",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "Je suis ici. J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici. J ai faim."],
    ifCorrect: "Two engines, one after the other, doing different work.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-and-hungry",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Greet them, then say how you are.",
    context: "You arrive at their door at two and nothing has been mentioned about lunch.",
    answers: ["Bonjour. J'ai faim."],
    alternatives: ["Bonjour, j'ai faim.", "Bonjour. J ai faim."],
    ifCorrect: "A hint, delivered politely, which is often how it is done.",
  }),
  weaveSeed({
    id: "p-l4-apply-decline-because-hungry",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-faim"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn the drink down, and say what you actually need.",
    context: "They offer coffee. You have not eaten since seven.",
    answers: ["Non merci. J'ai faim."],
    alternatives: ["Non merci, j'ai faim."],
    ifCorrect: "Redirecting an offer works better than refusing it flat.",
  }),
  weaveSeed({
    id: "p-l4-apply-two-things-to-say",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "noun-idee", "chunk-j-ai"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Say you have both.",
    context: "You have been holding a question and a suggestion for ten minutes.",
    answers: ["J'ai une question. J'ai une idée."],
    alternatives: ["J'ai une question, j'ai une idée."],
    ifCorrect: "One engine, two loads, and each keeps its own small word.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-with-a-question",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Announce yourself, then say what you came for.",
    context: "Expected, and they are on a call they are about to end.",
    answers: ["Je suis ici. J'ai une question."],
    alternatives: ["Je suis ici, j'ai une question."],
    ifCorrect: "Announce first. The question waits two seconds and lands better for it.",
  }),
  weaveSeed({
    id: "p-l4-apply-cut-in-hungry",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-faim"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, then say how you are.",
    context: "Nobody has stopped and it is well past lunch.",
    answers: ["Excusez-moi, j'ai faim."],
    alternatives: ["Excusez-moi. J'ai faim.", "Excusez-moi, j ai faim."],
    ifCorrect: "Interrupting for a real need is what excusez-moi is for.",
  }),
  weaveSeed({
    id: "p-l4-dictation-two-things",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-j-ai-une-question", "noun-idee"],
    targets: ["noun-idee"],
    audio: "J'ai une question. J'ai une idée.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une question. J'ai une idée."],
    alternatives: ["J ai une question. J ai une idée."],
    ifCorrect: "Two sentences, same engine, different load.",
  }),
  weaveSeed({
    id: "p-l4-apply-have-idea",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "mid",
    prompt: "Say what you have.",
    context: "They ask whether anyone has anything.",
    answers: ["J'ai une idée."],
    alternatives: ["J ai une idée."],
    ifCorrect: "The same j'ai frame, a different thing in it.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-and-idea",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Greet them, and say what you have.",
    context: "You come in with something worth saying.",
    answers: ["Bonjour. J'ai une idée."],
    alternatives: ["Bonjour, j'ai une idée."],
    ifCorrect: "Greeting first is what stops it sounding like an interruption.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-with-idea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Say you are here, and what you brought.",
    context: "You walked over specifically to say this.",
    answers: ["Je suis ici. J'ai une idée."],
    alternatives: ["Je suis ici, j'ai une idée."],
    ifCorrect: "Arriving and having something are two facts, said plainly.",
  }),
  weaveSeed({
    id: "p-l4-apply-decline-with-idea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down, and offer something instead.",
    context: "They propose one thing. You have a better one.",
    answers: ["Non merci. J'ai une idée."],
    alternatives: ["Non merci, j'ai une idée."],
    ifCorrect: "A refusal lands better with an alternative attached.",
  }),
  weaveSeed({
    id: "p-l4-apply-hungry-and-question",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say how you are, and what else you have.",
    context: "Two things at once, and both of them yours.",
    answers: ["J'ai faim. J'ai une question."],
    alternatives: ["J ai faim. J'ai une question."],
    ifCorrect: "The same opener twice, doing two different jobs.",
  }),
  weaveSeed({
    id: "p-l4-apply-idea-and-hungry",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai", "noun-idee", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Offer the thought, and say how you are.",
    context: "You have a suggestion and it involves lunch.",
    answers: ["J'ai une idée. J'ai faim."],
    alternatives: ["J ai une idée. J'ai faim."],
    ifCorrect: "Two j'ai sentences, and the second explains the first.",
  }),
  weaveSeed({
    id: "p-l4-apply-reach-with-question",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Reach them, and say what you have.",
    context: "They are about to leave the room.",
    answers: ["Excusez-moi. J'ai une question."],
    alternatives: ["Excusez-moi, j'ai une question."],
    ifCorrect: "Naming the question stops them walking away.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-arrive-hungry",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Greet, announce yourself, and say how you are.",
    context: "You arrive for lunch and nobody has ordered.",
    answers: ["Bonjour. Je suis ici. J'ai faim."],
    alternatives: ["Bonjour, je suis ici. J'ai faim."],
    ifCorrect: "Three short sentences, and everyone knows where they stand.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-arrive-idea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Greet, say you are here, and say what you brought.",
    context: "A meeting you are early for, with something to contribute.",
    answers: ["Bonjour. Je suis ici. J'ai une idée."],
    alternatives: ["Bonjour, je suis ici. J'ai une idée."],
    ifCorrect: "Arriving with something is better than arriving and waiting.",
  }),
  weaveSeed({
    id: "p-l4-apply-hungry-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-merci"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say how you are, and thank them.",
    context: "They noticed before you said anything.",
    answers: ["J'ai faim. Merci."],
    alternatives: ["J ai faim. Merci."],
    ifCorrect: "Saying the plain thing is often the whole skill.",
  }),
  weaveSeed({
    id: "p-l4-apply-question-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-merci"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say what you have, and thank them for the room.",
    context: "They stopped what they were doing to listen.",
    answers: ["J'ai une question. Merci."],
    alternatives: ["J ai une question. Merci."],
    ifCorrect: "Thanking before you ask assumes goodwill, which usually produces it.",
  }),
  weaveSeed({
    id: "p-l4-apply-idea-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai", "noun-idee", "chunk-merci"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Offer the thought, and thank them for asking.",
    context: "They asked whether anybody had anything, and you did.",
    answers: ["J'ai une idée. Merci."],
    alternatives: ["J ai une idée. Merci."],
    ifCorrect: "Thanking for being asked is what gets you asked again.",
  }),
  weaveSeed({
    id: "p-l4-apply-reach-hungry-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-faim", "chunk-merci"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Reach them, say how you are, and thank them.",
    context: "They are clearing up and have not asked you anything.",
    answers: ["Excusez-moi. J'ai faim. Merci."],
    alternatives: ["Excusez-moi, j'ai faim. Merci."],
    ifCorrect: "Three moves, and none of them needs a new word.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-idea-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai", "noun-idee", "chunk-merci"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Announce yourself, offer the thought, and close.",
    context: "You came in only to say this and are leaving after.",
    answers: ["Je suis ici. J'ai une idée. Merci."],
    alternatives: ["Je suis ici. J ai une idée. Merci."],
    ifCorrect: "A whole contribution in three short sentences.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-hungry-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim", "chunk-merci"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you are here, how you are, and thank them.",
    context: "You arrive for lunch and they waited.",
    answers: ["Je suis ici. J'ai faim. Merci."],
    alternatives: ["Je suis ici. J ai faim. Merci."],
    ifCorrect: "Where you are and how you are, then the thanks that closes it.",
  }),
  weaveSeed({
    id: "p-l4-apply-reach-hungry-question",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Reach them, and say both things you have.",
    context: "Two things at once and neither of them can wait.",
    answers: ["Excusez-moi. J'ai faim. J'ai une question."],
    alternatives: ["Excusez-moi, j'ai faim. J'ai une question."],
    ifCorrect: "The same opener twice, doing two different jobs.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-hungry-question",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Announce yourself, and say both things.",
    context: "You came in with a question and no lunch.",
    answers: ["Je suis ici. J'ai faim. J'ai une question."],
    alternatives: ["Je suis ici. J ai faim. J'ai une question."],
    ifCorrect: "Three j'ai-and-je-suis sentences, and the contrast is the lesson.",
  }),
  weaveSeed({
    id: "p-l4-apply-decline-and-place",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-je-suis-ici"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down, and say where you are.",
    context: "They offer to fetch you from somewhere you are not.",
    answers: ["Non merci. Je suis ici."],
    alternatives: ["Non merci, je suis ici."],
    ifCorrect: "A refusal and a location, and neither needs an explanation.",
  }),
  weaveSeed({
    id: "p-l4-apply-yes-and-hungry",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Agree, and say how you are.",
    context: "They ask whether you want to stop for lunch.",
    answers: ["Oui. J'ai faim."],
    alternatives: ["Oui, j'ai faim."],
    ifCorrect: "Agreeing with a reason attached is a stronger yes.",
  }),
  weaveSeed({
    id: "p-l4-apply-yes-and-question",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Agree, and say what you have.",
    context: "They ask whether anyone needs anything before they go.",
    answers: ["Oui. J'ai une question."],
    alternatives: ["Oui, j'ai une question."],
    ifCorrect: "Saying yes and then what you meant by it.",
  }),
  weaveSeed({
    id: "p-l4-apply-yes-and-idea",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Agree, and offer the thought.",
    context: "They ask whether anybody has a better plan.",
    answers: ["Oui. J'ai une idée."],
    alternatives: ["Oui, j'ai une idée."],
    ifCorrect: "Une idée, not un idée. The word decides, not the meaning.",
  }),
  weaveSeed({
    id: "p-l4-apply-here-and-question",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-c-est", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Confirm the place, and say what you have.",
    context: "You found the room and you did not come empty-handed.",
    answers: ["C'est ici. J'ai une question."],
    alternatives: ["C est ici. J'ai une question."],
    ifCorrect: "Arriving and having something are two sentences, said plainly.",
  }),
  weaveSeed({
    id: "p-l4-apply-wrong-place-question",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say it is the wrong place, and ask anyway.",
    context: "Wrong room, right person, and you may as well ask.",
    answers: ["Ce n'est pas ici. J'ai une question."],
    alternatives: ["Ce n est pas ici. J'ai une question."],
    ifCorrect: "The wrong room is still a room with someone helpful in it.",
  }),
  weaveSeed({
    id: "p-l4-repair-question-and-lost",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say what you have, and why.",
    context: "You are asking precisely because none of it landed.",
    answers: ["J'ai une question. Je ne comprends pas."],
    alternatives: ["J ai une question. Je ne comprends pas."],
    ifCorrect: "Naming the question and the reason together gets a better answer.",
  }),
  weaveSeed({
    id: "p-l4-repair-question-ask-again",
    operation: "repair", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Flag the question, and ask for the repeat.",
    context: "They explained once, fast, and you want the middle again.",
    answers: ["J'ai une question. Vous pouvez répéter ?"],
    alternatives: ["J ai une question. Vous pouvez répéter ?"],
    ifCorrect: "A repeat is a kind of question, and asking for it is the same move.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-hungry-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-faim", "chunk-merci"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Greet them, say how you are, and thank them.",
    context: "They ask how you are and they mean it.",
    answers: ["Bonjour. J'ai faim. Merci."],
    alternatives: ["Bonjour, j'ai faim. Merci."],
    ifCorrect: "Answering honestly is faster than answering politely.",
  }),
  weaveSeed({
    id: "p-l4-apply-reach-idea-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee", "chunk-merci"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Reach them, offer the thought, and close.",
    context: "You interrupt only because the thought is worth it.",
    answers: ["Excusez-moi. J'ai une idée. Merci."],
    alternatives: ["Excusez-moi, j'ai une idée. Merci."],
    ifCorrect: "Interrupting with something useful is not really interrupting.",
  }),
];
