/**
 * L4 practice seeds — the other engine.
 *
 * `noun-faim` and `noun-question` are VIA_CARRIER items: "faim" is not
 * something a beginner says, "J'ai faim." is. Every seed here targets the
 * carrier chunk, never the bare noun.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-004";

export const L4_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l4-retrieve-j-ai-faim",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "mid",
    prompt: "I'm hungry.",
    answers: ["J'ai faim."],
    alternatives: ["J'ai faim", "Jai faim."],
    ifCorrect: "French has you HAVE hunger. That is the whole idea.",
  }),
  weaveSeed({
    id: "p-l4-retrieve-j-ai-une-question",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "mid",
    prompt: "I have a question.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "The sentence that opens almost every room you walk into.",
  }),
  fillSeed({
    id: "p-l4-repair-have-not-be",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-je-suis"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis", "avoir-vs-etre"],
    repairs: "j-ai-vs-je-suis",
    prompt: "You want to say you are hungry. Which engine does French use?",
    after: " faim.",
    correct: { id: "o-jai", text: "J'ai" },
    traps: [
      {
        id: "o-je-suis-faim",
        text: "Je suis",
        why: "That is the English shape. In French hunger is something you have, not something you are.",
        tag: "wrong_item",
      },
      {
        id: "o-je-voudrais-faim",
        text: "Je voudrais",
        why: "That asks for something. You are describing how you feel.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai faim.",
    explanation: "Hunger, questions and ideas all arrive on j'ai.",
  }),
  fillSeed({
    id: "p-l4-repair-which-kind-of-have",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-j-ai-faim", "noun-idee"],
    targets: ["chunk-j-ai-une-question"],
    prompt: "The room is waiting and you need one thing cleared up. What do you say?",
    correct: { id: "o-question", text: "J'ai une question." },
    traps: [
      {
        id: "o-faim",
        text: "J'ai faim.",
        why: "True, perhaps, but it does not get your question answered.",
        tag: "meaning_shift",
      },
      {
        id: "o-idee",
        text: "J'ai une idée.",
        why: "That offers something. You are asking for something.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une question.",
    explanation: "Same engine, three different things to have. Pick the one you mean.",
  }),
  weaveSeed({
    id: "p-l4-produce-open-a-question",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-j-ai-une-question"],
    weaveType: "context",
    prompt: "Greet them, then open your question.",
    context: "You have found the right person and they have a moment.",
    answers: ["Bonjour, j'ai une question."],
    alternatives: ["Bonjour. J'ai une question."],
    ifCorrect: "Polite opening, then the reason you came.",
  }),
  weaveSeed({
    id: "p-l4-produce-cut-in-with-an-idea",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    weaveType: "context",
    prompt: "Cut in politely, then say what you have.",
    context: "The room has been stuck on the same problem for ten minutes, and something occurs to you.",
    answers: ["Excusez-moi, j'ai une idée."],
    alternatives: ["Excusez-moi. J'ai une idée."],
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  weaveSeed({
    id: "p-l4-apply-here-and-hungry",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you have arrived, then say you have not eaten.",
    context: "You get in late. They ask whether you want anything before you start.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim."],
    ifCorrect: "Two engines in two short sentences, and neither one is new.",
    ifWrong: "Your meaning lands. One sentence for where you are, one for what you have.",
  }),
  weaveSeed({
    id: "p-l4-apply-question-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say what you need.",
    context: "They finish explaining, look at you, and wait. One thing did not land.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "You did not need the words handed to you. That is what owning a sentence feels like.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l4-build-here-and-hungry",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Put both engines in one moment.",
    context: "You get in late, and they ask whether you want anything first.",
    tiles: [
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 0 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question." },
    ],
    target: "Je suis ici. J'ai faim.",
    ifCorrect: "One sentence for where you are, one for what you have.",
    ifWrong: "Place yourself first, then say what you have.",
  }),
  buildSeed({
    id: "p-l4-build-cut-in-with-an-idea",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    prompt: "Build the interruption.",
    context: "The room has been stuck for ten minutes and something occurs to you.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-j-ai", text: "j'ai", answerIndex: 1 },
      { itemId: "noun-idee", text: "une idée.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "faim" },
    ],
    target: "Excusez-moi, j'ai une idée.",
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  fillSeed({
    id: "p-l4-listen-which-have",
    operation: "repair",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    audio: "J'ai faim.",
    prompt: "Listen. What do they have?",
    correct: { id: "o-hungry", text: "I'm hungry." },
    traps: [
      { id: "o-have-question", text: "I have a question.", why: "Same engine, different thing on the end. Listen past the j'ai.", tag: "meaning_shift" },
      { id: "o-am-here", text: "I'm here.", why: "That is the other engine entirely: je suis, not j'ai.", tag: "wrong_item" },
    ],
    short: "J'ai faim.",
    explanation: "Everything after j'ai is what changes. That is where to listen.",
  }),
  weaveSeed({
    id: "p-l4-dictation-hungry",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai faim."],
    alternatives: ["j'ai faim.", "J'ai faim"],
    ifCorrect: "Two words, one apostrophe, and it is yours.",
  }),
  weaveSeed({
    id: "p-l4-dictation-question",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    audio: "J'ai une question.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une question."],
    alternatives: ["j'ai une question.", "J'ai une question"],
    ifCorrect: "The small word in the middle is easy to lose. You kept it.",
    ifWrong: "There is a package word between the engine and the noun.",
  }),
  fillSeed({
    id: "p-l4-fill-what-you-have",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Which engine carries a question?",
    after: " une question.",
    correct: { id: "o-jai-q", text: "J'ai" },
    traps: [
      { id: "o-jesuis-q", text: "Je suis", why: "That says you ARE a question, which is not a thing anyone says.", tag: "wrong_item" },
      { id: "o-jevoudrais-q", text: "Je voudrais", why: "That asks for a question rather than having one.", tag: "meaning_shift" },
    ],
    short: "J'ai une question.",
    explanation: "Questions are had, not been.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-and-question",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Greet them, then say what you came for.",
    context: "Somebody behind a desk with a moment to spare.",
    answers: ["Bonjour. J'ai une question."],
    alternatives: ["Bonjour, j'ai une question.", "Bonjour. J ai une question."],
    ifCorrect: "The greeting is what buys the question its hearing.",
  }),
  weaveSeed({
    id: "p-l4-apply-hungry-and-here",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you have arrived, then say how you are.",
    context: "A long trip, a late arrival, and nobody has offered you anything.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim.", "Je suis ici. J ai faim."],
    ifCorrect: "French HAS hunger where English IS hungry. Two engines, two jobs.",
  }),
  weaveSeed({
    id: "p-l4-apply-cut-in-with-idea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Cut in, and say what you have.",
    context: "The room has been stuck on the same problem and something has occurred to you.",
    answers: ["Excusez-moi, j'ai une idée."],
    alternatives: ["Excusez-moi. J'ai une idée.", "Excusez-moi, j ai une idée."],
    ifCorrect: "An idea is worth the interruption if you open it properly.",
  }),
  weaveSeed({
    id: "p-l4-repair-decline-because-question",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-une-question"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down, and say what you actually need.",
    context: "They offer you a seat and a drink. You only came to ask one thing.",
    answers: ["Non merci. J'ai une question."],
    alternatives: ["Non merci, j'ai une question."],
    ifCorrect: "Redirecting is kinder than a bare refusal.",
  }),
  fillSeed({
    id: "p-l4-choice-have-or-be",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-suis"],
    targets: ["chunk-j-ai-faim"],
    prompt: "You want to say you are hungry. Which engine does French use?",
    correct: { id: "o-ai", text: "J'ai faim." },
    traps: [
      { id: "o-suis", text: "Je suis faim.", why: "The commonest early slip. French HAS hunger, it does not BE it.", tag: "wrong_item" },
      { id: "o-ici", text: "Je suis ici.", why: "That places you somewhere and says nothing about hunger.", tag: "meaning_shift" },
    ],
    short: "J'ai faim.",
    explanation: "Two engines. Je suis for where and who, j'ai for what you carry.",
  }),
  fillSeed({
    id: "p-l4-listen-what-do-they-carry",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    audio: "J'ai une question.",
    prompt: "Listen. What have they got?",
    correct: { id: "o-q", text: "A question." },
    traps: [
      { id: "o-faim", text: "Hunger.", why: "That would be j'ai faim. The word after j'ai is the whole message.", tag: "meaning_shift" },
      { id: "o-idee", text: "An idea.", why: "Close, and a different noun. Listen past the j'ai.", tag: "meaning_shift" },
    ],
    short: "J'ai une question.",
    explanation: "J'ai is a container. What matters is what it is carrying.",
  }),
  buildSeed({
    id: "p-l4-build-greet-and-ask",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    prompt: "Assemble the opening.",
    context: "One thing to ask, and a stranger to ask it of.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Bonjour. J'ai une question.",
    ifCorrect: "Greeting first, always.",
    ifWrong: "Right pieces. Open before you ask.",
  }),
  weaveSeed({
    id: "p-l4-dictation-hungry-and-here",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "Je suis ici. J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici. J ai faim."],
    ifCorrect: "Two engines, one after the other, doing different work.",
  }),
  weaveSeed({
    id: "p-l4-apply-greet-and-hungry",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Greet them, then say how you are.",
    context: "You arrive at their door at two and nothing has been mentioned about lunch.",
    answers: ["Bonjour. J'ai faim."],
    alternatives: ["Bonjour, j'ai faim.", "Bonjour. J ai faim."],
    ifCorrect: "A hint, delivered politely, which is often how it is done.",
  }),
  weaveSeed({
    id: "p-l4-apply-decline-because-hungry",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-faim"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn the drink down, and say what you actually need.",
    context: "They offer coffee. You have not eaten since seven.",
    answers: ["Non merci. J'ai faim."],
    alternatives: ["Non merci, j'ai faim."],
    ifCorrect: "Redirecting an offer works better than refusing it flat.",
  }),
  weaveSeed({
    id: "p-l4-apply-two-things-to-say",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "noun-idee", "chunk-j-ai"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Say you have both.",
    context: "You have been holding a question and a suggestion for ten minutes.",
    answers: ["J'ai une question. J'ai une idée."],
    alternatives: ["J'ai une question, j'ai une idée."],
    ifCorrect: "One engine, two loads, and each keeps its own small word.",
  }),
  weaveSeed({
    id: "p-l4-apply-arrive-with-a-question",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Announce yourself, then say what you came for.",
    context: "Expected, and they are on a call they are about to end.",
    answers: ["Je suis ici. J'ai une question."],
    alternatives: ["Je suis ici, j'ai une question."],
    ifCorrect: "Announce first. The question waits two seconds and lands better for it.",
  }),
  weaveSeed({
    id: "p-l4-apply-cut-in-hungry",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-faim"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, then say how you are.",
    context: "Nobody has stopped and it is well past lunch.",
    answers: ["Excusez-moi, j'ai faim."],
    alternatives: ["Excusez-moi. J'ai faim.", "Excusez-moi, j ai faim."],
    ifCorrect: "Interrupting for a real need is what excusez-moi is for.",
  }),
  weaveSeed({
    id: "p-l4-dictation-two-things",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-j-ai-une-question", "noun-idee"],
    targets: ["noun-idee"],
    audio: "J'ai une question. J'ai une idée.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une question. J'ai une idée."],
    alternatives: ["J ai une question. J ai une idée."],
    ifCorrect: "Two sentences, same engine, different load.",
  }),
];
