/**
 * L4 practice seeds — the other engine.
 *
 * `noun-faim` and `noun-question` are VIA_CARRIER items: "faim" is not
 * something a beginner says, "J'ai faim." is. Every seed here targets the
 * carrier chunk, never the bare noun.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-004";

export const L4_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l4-retrieve-j-ai-faim",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "mid",
    prompt: "I'm hungry.",
    answers: ["J'ai faim."],
    alternatives: ["J'ai faim", "Jai faim."],
    ifCorrect: "French has you HAVE hunger. That is the whole idea.",
  }),
  weaveSeed({
    id: "p-l4-retrieve-j-ai-une-question",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "mid",
    prompt: "I have a question.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "The sentence that opens almost every room you walk into.",
  }),
  fillSeed({
    id: "p-l4-repair-have-not-be",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-je-suis"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis", "avoir-vs-etre"],
    repairs: "j-ai-vs-je-suis",
    prompt: "You want to say you are hungry. Which engine does French use?",
    after: " faim.",
    correct: { id: "o-jai", text: "J'ai" },
    traps: [
      {
        id: "o-je-suis-faim",
        text: "Je suis",
        why: "That is the English shape. In French hunger is something you have, not something you are.",
        tag: "wrong_item",
      },
      {
        id: "o-je-voudrais-faim",
        text: "Je voudrais",
        why: "That asks for something. You are describing how you feel.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai faim.",
    explanation: "Hunger, questions and ideas all arrive on j'ai.",
  }),
  fillSeed({
    id: "p-l4-repair-which-kind-of-have",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-j-ai-faim", "noun-idee"],
    targets: ["chunk-j-ai-une-question"],
    prompt: "The room is waiting and you need one thing cleared up. What do you say?",
    correct: { id: "o-question", text: "J'ai une question." },
    traps: [
      {
        id: "o-faim",
        text: "J'ai faim.",
        why: "True, perhaps, but it does not get your question answered.",
        tag: "meaning_shift",
      },
      {
        id: "o-idee",
        text: "J'ai une idée.",
        why: "That offers something. You are asking for something.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une question.",
    explanation: "Same engine, three different things to have. Pick the one you mean.",
  }),
  weaveSeed({
    id: "p-l4-produce-open-a-question",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-j-ai-une-question"],
    weaveType: "context",
    prompt: "Greet them, then open your question.",
    context: "You have found the right person and they have a moment.",
    answers: ["Bonjour, j'ai une question."],
    alternatives: ["Bonjour. J'ai une question."],
    ifCorrect: "Polite opening, then the reason you came.",
  }),
  weaveSeed({
    id: "p-l4-produce-cut-in-with-an-idea",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    weaveType: "context",
    prompt: "Cut in politely, then say what you have.",
    context: "The room has been stuck on the same problem for ten minutes, and something occurs to you.",
    answers: ["Excusez-moi, j'ai une idée."],
    alternatives: ["Excusez-moi. J'ai une idée."],
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  weaveSeed({
    id: "p-l4-apply-here-and-hungry",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say you have arrived, then say you have not eaten.",
    context: "You get in late. They ask whether you want anything before you start.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim."],
    ifCorrect: "Two engines in two short sentences, and neither one is new.",
    ifWrong: "Your meaning lands. One sentence for where you are, one for what you have.",
  }),
  weaveSeed({
    id: "p-l4-apply-question-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Say what you need.",
    context: "They finish explaining, look at you, and wait. One thing did not land.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "You did not need the words handed to you. That is what owning a sentence feels like.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l4-build-here-and-hungry",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    targets: ["chunk-je-suis-ici", "chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Put both engines in one moment.",
    context: "You get in late, and they ask whether you want anything first.",
    tiles: [
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 0 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question." },
    ],
    target: "Je suis ici. J'ai faim.",
    ifCorrect: "One sentence for where you are, one for what you have.",
    ifWrong: "Place yourself first, then say what you have.",
  }),
  buildSeed({
    id: "p-l4-build-cut-in-with-an-idea",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-excusez-moi", "noun-idee"],
    prompt: "Build the interruption.",
    context: "The room has been stuck for ten minutes and something occurs to you.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-j-ai", text: "j'ai", answerIndex: 1 },
      { itemId: "noun-idee", text: "une idée.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "faim" },
    ],
    target: "Excusez-moi, j'ai une idée.",
    ifCorrect: "A third thing to have, on the engine you already own.",
  }),
  fillSeed({
    id: "p-l4-listen-which-have",
    operation: "repair",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-faim"],
    tags: ["j-ai-vs-je-suis"],
    audio: "J'ai faim.",
    prompt: "Listen. What do they have?",
    correct: { id: "o-hungry", text: "I'm hungry." },
    traps: [
      { id: "o-have-question", text: "I have a question.", why: "Same engine, different thing on the end. Listen past the j'ai.", tag: "meaning_shift" },
      { id: "o-am-here", text: "I'm here.", why: "That is the other engine entirely — je suis, not j'ai.", tag: "wrong_item" },
    ],
    short: "J'ai faim.",
    explanation: "Everything after j'ai is what changes. That is where to listen.",
  }),
  weaveSeed({
    id: "p-l4-dictation-hungry",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai faim."],
    alternatives: ["j'ai faim.", "J'ai faim"],
    ifCorrect: "Two words, one apostrophe, and it is yours.",
  }),
  weaveSeed({
    id: "p-l4-dictation-question",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-une-question"],
    audio: "J'ai une question.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une question."],
    alternatives: ["j'ai une question.", "J'ai une question"],
    ifCorrect: "The small word in the middle is easy to lose. You kept it.",
    ifWrong: "There is a package word between the engine and the noun.",
  }),
  fillSeed({
    id: "p-l4-fill-what-you-have",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Which engine carries a question?",
    after: " une question.",
    correct: { id: "o-jai-q", text: "J'ai" },
    traps: [
      { id: "o-jesuis-q", text: "Je suis", why: "That says you ARE a question, which is not a thing anyone says.", tag: "wrong_item" },
      { id: "o-jevoudrais-q", text: "Je voudrais", why: "That asks for a question rather than having one.", tag: "meaning_shift" },
    ],
    short: "J'ai une question.",
    explanation: "Questions are had, not been.",
  }),
];
