/**
 * L5 practice seeds — the small word in front.
 *
 * `grammar-un-une-package` is `recognition` in L5, so it may be RECOGNISED but
 * never demanded as production. The one seed that targets it is a choice, which
 * is the same rule `screenIsSafeForItem` already applies on the lesson side.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-005";

export const L5_SEEDS: PracticeSeed[] = [
  fillSeed({
    id: "p-l5-retrieve-package-cafe",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-un-cafe", "noun-cafe", "grammar-un-une-package"],
    targets: ["chunk-un-cafe", "grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which small word does café travel with?",
    before: "Je voudrais ",
    after: " café.",
    correct: { id: "o-un-cafe", text: "un" },
    traps: [
      {
        id: "o-une-cafe",
        text: "une",
        why: "Café takes un. The two are not interchangeable, even though both mean a.",
        tag: "wrong_item",
      },
      {
        id: "o-le-cafe",
        text: "le",
        why: "That points at a particular coffee. You are asking for any one.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais un café.",
    explanation: "Each noun carries its own small word, and café carries un.",
  }),
  fillSeed({
    id: "p-l5-retrieve-package-question",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-une-question", "noun-question", "grammar-un-une-package"],
    targets: ["chunk-une-question", "grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which small word does question travel with?",
    before: "J'ai ",
    after: " question.",
    correct: { id: "o-une-question", text: "une" },
    traps: [
      {
        id: "o-un-question",
        text: "un",
        why: "Question takes une. The package is fixed to the noun, not to the sentence.",
        tag: "wrong_item",
      },
      {
        id: "o-la-question",
        text: "la",
        why: "That points at one particular question. You just have a question.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une question.",
    explanation: "Question carries une, and it carries it everywhere.",
  }),
  fillSeed({
    id: "p-l5-repair-package-idee",
    operation: "repair",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["noun-idee", "chunk-j-ai", "grammar-un-une-package"],
    targets: ["noun-idee"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Something occurs to you. Which package does idée travel in?",
    before: "J'ai ",
    after: " idée.",
    correct: { id: "o-une-idee", text: "une" },
    traps: [
      {
        id: "o-un-idee",
        text: "un",
        why: "Idée takes une, like question. Knowing one helps you guess the other.",
        tag: "wrong_item",
      },
      {
        id: "o-le-idee",
        text: "le",
        why: "That points at a particular idea. Yours has only just arrived.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une idée.",
    explanation: "Une again — the same package question travels in.",
  }),
  weaveSeed({
    id: "p-l5-produce-request-with-package",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais", "chunk-un-cafe"],
    weaveType: "context",
    prompt: "Ask for one, with its small word in front.",
    context: "You are at the counter and there is coffee going.",
    answers: ["Je voudrais un café."],
    alternatives: ["Je voudrais un café, s'il vous plaît."],
    ifCorrect: "Choosing the package is easy. Saying it inside a sentence is the part that counts.",
  }),
  weaveSeed({
    id: "p-l5-produce-have-with-package",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-j-ai", "chunk-une-question"],
    weaveType: "context",
    prompt: "Say what you have, with the right small word.",
    context: "They pause and look round the room to see if anyone needs anything.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "The package rode along without you having to think about it.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-then-ask",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-un-cafe", "chunk-une-question"],
    weaveType: "open",
    prompt: "Ask for the one, then say you have the other.",
    context: "A coffee first, and then the thing you actually came in to ask.",
    answers: ["Je voudrais un café. J'ai une question."],
    alternatives: ["Je voudrais un café, j'ai une question."],
    ifCorrect: "Two packages, two engines, one moment. Both small words landed.",
    ifWrong: "Your meaning lands. Ask for the coffee first, then say what you have.",
  }),
  weaveSeed({
    id: "p-l5-apply-idea-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Say what you have.",
    context: "The meeting has stalled. Everyone is quiet, and something has just occurred to you.",
    answers: ["J'ai une idée."],
    alternatives: ["J'ai une idée"],
    ifCorrect: "No translation, no tray. You reached for it and it was there.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l5-build-order-then-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-un-cafe", "chunk-une-question"],
    tags: ["articles"],
    prompt: "Build both halves of the moment.",
    context: "A coffee first, then the thing you actually came in to ask.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-un-cafe", text: "un café.", answerIndex: 1 },
      { itemId: "chunk-j-ai", text: "J'ai", answerIndex: 2 },
      { itemId: "chunk-une-question", text: "une question.", answerIndex: 3 },
      { itemId: "noun-idee", text: "une idée." },
    ],
    target: "Je voudrais un café. J'ai une question.",
    ifCorrect: "Two packages, two engines, and both small words landed.",
    ifWrong: "Ask for the coffee first, then say what you have.",
  }),
  buildSeed({
    id: "p-l5-build-the-package",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-une-question"],
    tags: ["articles", "gender"],
    prompt: "Build it with the right small word.",
    context: "They pause and look round to see if anyone needs anything.",
    tiles: [
      { itemId: "chunk-j-ai", text: "J'ai", answerIndex: 0 },
      { itemId: "chunk-une-question", text: "une question.", answerIndex: 1 },
      { itemId: "chunk-un-cafe", text: "un café." },
    ],
    target: "J'ai une question.",
    ifCorrect: "The package rides along with the noun, every time.",
  }),
  fillSeed({
    id: "p-l5-listen-which-drink",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-un-the", "chunk-un-cafe", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    audio: "Je voudrais un thé.",
    prompt: "Listen. What are they asking for?",
    correct: { id: "o-tea", text: "I would like a tea." },
    traps: [
      { id: "o-coffee-l5", text: "I would like a coffee.", why: "Same request, different thing inside it. The last word is the one that changed.", tag: "meaning_shift" },
      { id: "o-question-l5", text: "I have a question.", why: "That is the other engine — having, not asking for.", tag: "wrong_item" },
    ],
    short: "Je voudrais un thé.",
    explanation: "The frame is familiar; listen to what is sitting inside it.",
  }),
  weaveSeed({
    id: "p-l5-dictation-coffee",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-un-cafe"],
    audio: "Je voudrais un café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais un café."],
    alternatives: ["je voudrais un café.", "Je voudrais un café"],
    ifCorrect: "The small word came through even at speed.",
  }),
  weaveSeed({
    id: "p-l5-dictation-idea",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    audio: "J'ai une idée.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une idée."],
    alternatives: ["j'ai une idée.", "J'ai une idée"],
    ifCorrect: "Two accents and an apostrophe, all in the right places.",
    ifWrong: "Listen for the package word before the noun.",
  }),
  weaveSeed({
    id: "p-l5-apply-two-packages-context",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Ask for the other one.",
    context: "You had coffee this morning and you would rather not have another.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Same frame, different thing in it. No new grammar required.",
  }),
  fillSeed({
    id: "p-l5-choice-which-package-goes-where",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-un-cafe", "chunk-une-question", "grammar-un-une-package"],
    targets: ["grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which of these has its small word right?",
    correct: { id: "o-right-pack", text: "J'ai une question." },
    traps: [
      { id: "o-un-question", text: "J'ai un question.", why: "Question travels with une, and it does so everywhere.", tag: "wrong_item" },
      { id: "o-une-cafe", text: "Je voudrais une café.", why: "Café travels with un. The package is fixed to the noun.", tag: "wrong_item" },
    ],
    short: "J'ai une question.",
    explanation: "Each noun keeps its own small word, whatever sentence it lands in.",
  }),
];
