/**
 * L5 practice seeds — the small word in front.
 *
 * `grammar-un-une-package` is `recognition` in L5, so it may be RECOGNISED but
 * never demanded as production. The one seed that targets it is a choice, which
 * is the same rule `screenIsSafeForItem` already applies on the lesson side.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-005";

export const L5_SEEDS: PracticeSeed[] = [
  fillSeed({
    id: "p-l5-retrieve-package-cafe",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-un-cafe", "noun-cafe", "grammar-un-une-package"],
    targets: ["chunk-un-cafe", "grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which small word does café travel with?",
    before: "Je voudrais ",
    after: " café.",
    correct: { id: "o-un-cafe", text: "un" },
    traps: [
      {
        id: "o-une-cafe",
        text: "une",
        why: "Café takes un. The two are not interchangeable, even though both mean a.",
        tag: "wrong_item",
      },
      {
        id: "o-le-cafe",
        text: "le",
        why: "That points at a particular coffee. You are asking for any one.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais un café.",
    explanation: "Each noun carries its own small word, and café carries un.",
  }),
  fillSeed({
    id: "p-l5-retrieve-package-question",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-une-question", "grammar-un-une-package"],
    targets: ["chunk-une-question", "grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which small word does question travel with?",
    before: "J'ai ",
    after: " question.",
    correct: { id: "o-une-question", text: "une" },
    traps: [
      {
        id: "o-un-question",
        text: "un",
        why: "Question takes une. The package is fixed to the noun, not to the sentence.",
        tag: "wrong_item",
      },
      {
        id: "o-la-question",
        text: "la",
        why: "That points at one particular question. You just have a question.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une question.",
    explanation: "Question carries une, and it carries it everywhere.",
  }),
  fillSeed({
    id: "p-l5-repair-package-idee",
    operation: "repair",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["noun-idee", "chunk-j-ai", "grammar-un-une-package"],
    targets: ["noun-idee"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Something occurs to you. Which package does idée travel in?",
    before: "J'ai ",
    after: " idée.",
    correct: { id: "o-une-idee", text: "une" },
    traps: [
      {
        id: "o-un-idee",
        text: "un",
        why: "Idée takes une, like question. Knowing one helps you guess the other.",
        tag: "wrong_item",
      },
      {
        id: "o-le-idee",
        text: "le",
        why: "That points at a particular idea. Yours has only just arrived.",
        tag: "meaning_shift",
      },
    ],
    short: "J'ai une idée.",
    explanation: "Une again, the same package that question travels in.",
  }),
  weaveSeed({
    id: "p-l5-produce-request-with-package",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais", "chunk-un-cafe"],
    weaveType: "context",
    prompt: "Ask for one, with its small word in front.",
    context: "You are at the counter and there is coffee going.",
    answers: ["Je voudrais un café."],
    alternatives: ["Je voudrais un café, s'il vous plaît."],
    ifCorrect: "Choosing the package is easy. Saying it inside a sentence is the part that counts.",
  }),
  weaveSeed({
    id: "p-l5-produce-have-with-package",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-j-ai", "chunk-une-question"],
    weaveType: "context",
    prompt: "Say what you have, with the right small word.",
    context: "They pause and look round the room to see if anyone needs anything.",
    answers: ["J'ai une question."],
    alternatives: ["J'ai une question"],
    ifCorrect: "The package rode along without you having to think about it.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-then-ask",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-un-cafe", "chunk-une-question"],
    weaveType: "open",
    prompt: "Ask for the one, then say you have the other.",
    context: "A coffee first, and then the thing you actually came in to ask.",
    answers: ["Je voudrais un café. J'ai une question."],
    alternatives: ["Je voudrais un café, j'ai une question."],
    ifCorrect: "Two packages, two engines, one moment. Both small words landed.",
    ifWrong: "Your meaning lands. Ask for the coffee first, then say what you have.",
  }),
  weaveSeed({
    id: "p-l5-apply-idea-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Say what you have.",
    context: "The meeting has stalled. Everyone is quiet, and something has just occurred to you.",
    answers: ["J'ai une idée."],
    alternatives: ["J'ai une idée"],
    ifCorrect: "No translation, no tray. You reached for it and it was there.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l5-build-order-then-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-un-cafe", "chunk-une-question"],
    tags: ["articles"],
    prompt: "Build both halves of the moment.",
    context: "A coffee first, then the thing you actually came in to ask.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-un-cafe", text: "un café.", answerIndex: 1 },
      { itemId: "chunk-j-ai", text: "J'ai", answerIndex: 2 },
      { itemId: "chunk-une-question", text: "une question.", answerIndex: 3 },
      { itemId: "noun-idee", text: "une idée." },
    ],
    target: "Je voudrais un café. J'ai une question.",
    ifCorrect: "Two packages, two engines, and both small words landed.",
    ifWrong: "Ask for the coffee first, then say what you have.",
  }),
  buildSeed({
    id: "p-l5-build-the-package",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-une-question"],
    tags: ["articles", "gender"],
    prompt: "Build it with the right small word.",
    context: "They pause and look round to see if anyone needs anything.",
    tiles: [
      { itemId: "chunk-j-ai", text: "J'ai", answerIndex: 0 },
      { itemId: "chunk-une-question", text: "une question.", answerIndex: 1 },
      { itemId: "chunk-un-cafe", text: "un café." },
    ],
    target: "J'ai une question.",
    ifCorrect: "The package rides along with the noun, every time.",
  }),
  fillSeed({
    id: "p-l5-listen-which-drink",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-un-the", "chunk-un-cafe", "chunk-je-voudrais"],
    targets: ["chunk-un-the"],
    audio: "Je voudrais un thé.",
    prompt: "Listen. What are they asking for?",
    correct: { id: "o-tea", text: "I would like a tea." },
    traps: [
      { id: "o-coffee-l5", text: "I would like a coffee.", why: "Same request, different thing inside it. The last word is the one that changed.", tag: "meaning_shift" },
      { id: "o-question-l5", text: "I have a question.", why: "That is the other engine: having, not asking for.", tag: "wrong_item" },
    ],
    short: "Je voudrais un thé.",
    explanation: "The frame is familiar; listen to what is sitting inside it.",
  }),
  weaveSeed({
    id: "p-l5-dictation-coffee",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-un-cafe"],
    audio: "Je voudrais un café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais un café."],
    alternatives: ["je voudrais un café.", "Je voudrais un café"],
    ifCorrect: "The small word came through even at speed.",
  }),
  weaveSeed({
    id: "p-l5-dictation-idea",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    audio: "J'ai une idée.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une idée."],
    alternatives: ["j'ai une idée.", "J'ai une idée"],
    ifCorrect: "Two accents and an apostrophe, all in the right places.",
    ifWrong: "Listen for the package word before the noun.",
  }),
  weaveSeed({
    id: "p-l5-apply-two-packages-context",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Ask for the other one.",
    context: "You had coffee this morning and you would rather not have another.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un thé, s'il vous plaît."],
    ifCorrect: "Same frame, different thing in it. No new grammar required.",
  }),
  fillSeed({
    id: "p-l5-choice-which-package-goes-where",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-un-cafe", "chunk-une-question", "grammar-un-une-package"],
    targets: ["grammar-un-une-package"],
    tags: ["articles", "gender"],
    repairs: "articles",
    prompt: "Which of these has its small word right?",
    correct: { id: "o-right-pack", text: "J'ai une question." },
    traps: [
      { id: "o-un-question", text: "J'ai un question.", why: "Question travels with une, and it does so everywhere.", tag: "wrong_item" },
      { id: "o-une-cafe", text: "Je voudrais une café.", why: "Café travels with un. The package is fixed to the noun.", tag: "wrong_item" },
    ],
    short: "J'ai une question.",
    explanation: "Each noun keeps its own small word, whatever sentence it lands in.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-tea-with-package",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "grammar-un-une-package"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other drink, with its small word.",
    context: "You had coffee this morning and would rather not have another.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un thé", "Je voudrais un the."],
    ifCorrect: "Thé takes un, the same package as café.",
  }),
  weaveSeed({
    id: "p-l5-apply-question-then-idea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-une-question", "noun-idee", "chunk-j-ai"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Say you have both things, each with its own small word.",
    context: "The room is quiet and you have been holding two thoughts.",
    answers: ["J'ai une question. J'ai une idée."],
    alternatives: ["J'ai une question, j'ai une idée."],
    ifCorrect: "Question and idée both take une, and both keep it wherever they go.",
  }),
  weaveSeed({
    id: "p-l5-apply-polite-order-package",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-un-cafe"],
    weaveType: "open",
    prompt: "Order, with the small word and the polite tail.",
    context: "A formal counter and somebody waiting behind you.",
    answers: ["Je voudrais un café, s'il vous plaît."],
    alternatives: ["Je voudrais un café s'il vous plaît."],
    ifCorrect: "The package travels with the noun; the tail goes at the end.",
  }),
  fillSeed({
    id: "p-l5-choice-which-package-idea",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["noun-idee", "grammar-un-une-package"],
    targets: ["noun-idee"],
    prompt: "Something has occurred to you. Which package does idée travel in?",
    correct: { id: "o-une", text: "J'ai une idée." },
    traps: [
      { id: "o-un", text: "J'ai un idée.", why: "Idée carries une, and it keeps it in every sentence.", tag: "wrong_item" },
      { id: "o-none", text: "J'ai idée.", why: "The noun does not travel bare. The small word is part of it.", tag: "missing_word" },
    ],
    short: "J'ai une idée.",
    explanation: "The package belongs to the noun, not to the sentence.",
  }),
  fillSeed({
    id: "p-l5-listen-which-package",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-un-cafe", "chunk-une-question", "grammar-un-une-package"],
    targets: ["chunk-un-cafe"],
    audio: "Je voudrais un café.",
    prompt: "Listen. Which small word did the noun bring with it?",
    correct: { id: "o-un", text: "un" },
    traps: [
      { id: "o-une", text: "une", why: "Une belongs to question and idée. Café takes un.", tag: "wrong_item" },
      { id: "o-le", text: "le", why: "Not one of the two packages this lesson works.", tag: "wrong_item" },
    ],
    short: "un café",
    explanation: "The package is short and unstressed, which is exactly why it is worth listening for.",
  }),
  buildSeed({
    id: "p-l5-build-two-packages",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-un-cafe", "chunk-une-question"],
    prompt: "Build both, each with its own package.",
    context: "A coffee first, and then the thing you came in to ask.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-un-cafe", text: "un café.", answerIndex: 1 },
      { itemId: "chunk-j-ai", text: "J'ai", answerIndex: 2 },
      { itemId: "chunk-une-question", text: "une question.", answerIndex: 3 },
      { itemId: "chunk-un-the", text: "un thé." },
    ],
    target: "Je voudrais un café. J'ai une question.",
    ifCorrect: "Two nouns, two packages, and neither one borrows the other's.",
    ifWrong: "Right pieces. Each noun keeps the small word it came with.",
  }),
  weaveSeed({
    id: "p-l5-dictation-tea-package",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    audio: "Je voudrais un thé.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un the.", "Je voudrais un thé"],
    ifCorrect: "The accent on thé is the whole word.",
  }),
  weaveSeed({
    id: "p-l5-retrieve-idea-package",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "mid",
    prompt: "Say what has just occurred to you.",
    context: "The meeting has stalled and everyone has gone quiet.",
    answers: ["J'ai une idée."],
    alternatives: ["J ai une idée.", "J'ai une idee."],
    ifCorrect: "Une idée, packaged and ready to offer.",
  }),
  weaveSeed({
    id: "p-l5-apply-greet-order-tea",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "grammar-un-une-package"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Open it, then order the other drink.",
    context: "A counter you have not used before, and you have had enough coffee today.",
    answers: ["Bonjour. Je voudrais un thé."],
    alternatives: ["Bonjour, je voudrais un thé."],
    ifCorrect: "Thé keeps un wherever it appears.",
  }),
  weaveSeed({
    id: "p-l5-apply-idea-then-order",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["noun-idee", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Say what has occurred to you, then order something to think over.",
    context: "The room has stalled and you would rather work it out with a coffee.",
    answers: ["J'ai une idée. Je voudrais un café."],
    alternatives: ["J'ai une idée, je voudrais un café."],
    ifCorrect: "Une for the idea, un for the coffee. Neither borrows the other's.",
  }),
  weaveSeed({
    id: "p-l5-apply-both-drinks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order for two: one of each.",
    context: "You are fetching for somebody else as well, and they take tea.",
    answers: ["Je voudrais un café. Je voudrais un thé."],
    alternatives: ["Je voudrais un café, je voudrais un thé."],
    ifCorrect: "Same package, two different drinks.",
  }),
  weaveSeed({
    id: "p-l5-apply-question-politely",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-une-question", "chunk-j-ai", "chunk-sil-vous-plait"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Say you have a question, politely.",
    context: "A formal desk, and they are about to close for lunch.",
    answers: ["J'ai une question, s'il vous plaît."],
    alternatives: ["J ai une question, s'il vous plaît."],
    ifCorrect: "Une question keeps its package, and the tail goes at the end.",
  }),
  weaveSeed({
    id: "p-l5-dictation-idea-and-coffee",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["noun-idee", "chunk-un-cafe"],
    targets: ["noun-idee"],
    audio: "J'ai une idée. Je voudrais un café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai une idée. Je voudrais un café."],
    alternatives: ["J ai une idée. Je voudrais un café."],
    ifCorrect: "Une and un, one sentence apart, both audible.",
  }),
  weaveSeed({
    id: "p-l5-retrieve-tea-cold",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "mid",
    prompt: "Order a tea.",
    context: "Nothing complicated. Just the other drink.",
    answers: ["Je voudrais un thé."],
    alternatives: ["Je voudrais un the.", "Je voudrais un thé !"],
    ifCorrect: "The package came with the noun and stays attached to it.",
  }),
  weaveSeed({
    id: "p-l5-apply-idea-order-tea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai", "noun-idee", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Offer the thought, and order the other one.",
    context: "The room has gone quiet and you would rather think over tea.",
    answers: ["J'ai une idée. Je voudrais un thé."],
    alternatives: ["J ai une idée. Je voudrais un thé."],
    ifCorrect: "Une idée, un thé. The same little word doing the same job.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-tea-then-question",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Order the other one, then say what else you have.",
    context: "You want the tea and the answer, in that order.",
    answers: ["Je voudrais un thé. J'ai une question."],
    alternatives: ["Je voudrais un thé. J ai une question."],
    ifCorrect: "Un thé, une question. The article follows the word, not the meaning.",
  }),
  weaveSeed({
    id: "p-l5-apply-question-order-coffee",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai", "chunk-une-question", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-un-cafe"],
    weaveType: "open",
    prompt: "Say what you have, then order.",
    context: "You will ask it, but not before the coffee arrives.",
    answers: ["J'ai une question. Je voudrais un café."],
    alternatives: ["J ai une question. Je voudrais un café."],
    ifCorrect: "Une question, un café. Two words, two different articles.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-coffee-then-idea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "noun-idee"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Order, and say what you brought.",
    context: "You have thought of something and want to sit with it.",
    answers: ["Je voudrais un café. J'ai une idée."],
    alternatives: ["Je voudrais un café. J ai une idée."],
    ifCorrect: "Un café, une idée. Nothing about them looks different but the article.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-tea-then-idea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "chunk-j-ai", "noun-idee"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Order the other one, and say what you brought.",
    context: "Late afternoon and the thought only just arrived.",
    answers: ["Je voudrais un thé. J'ai une idée."],
    alternatives: ["Je voudrais un thé. J ai une idée."],
    ifCorrect: "Un thé, une idée. The pattern holds whatever you put in it.",
  }),
  weaveSeed({
    id: "p-l5-apply-question-order-tea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai", "chunk-une-question", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Say what you have, then order the other one.",
    context: "Both at once, at a counter, in one breath.",
    answers: ["J'ai une question. Je voudrais un thé."],
    alternatives: ["J ai une question. Je voudrais un thé."],
    ifCorrect: "Une question, un thé. Two articles, and neither is optional.",
  }),
  weaveSeed({
    id: "p-l5-apply-idea-order-coffee-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai", "noun-idee", "chunk-je-voudrais", "chunk-un-cafe", "chunk-merci"],
    targets: ["chunk-un-cafe"],
    weaveType: "open",
    prompt: "Offer the thought, order, and close.",
    context: "You want to sit with it, and coffee helps.",
    answers: ["J'ai une idée. Je voudrais un café. Merci."],
    alternatives: ["J ai une idée. Je voudrais un café. Merci."],
    ifCorrect: "Une idée, un café. The article changes and nothing else does.",
  }),
  weaveSeed({
    id: "p-l5-apply-greet-question-order",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai", "chunk-une-question", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Greet, say what you have, and order.",
    context: "You arrive with a question and no intention of asking it first.",
    answers: ["Bonjour. J'ai une question. Je voudrais un café."],
    alternatives: ["Bonjour, j'ai une question. Je voudrais un café."],
    ifCorrect: "Une question, un café. Two nouns, two different little words.",
  }),
  weaveSeed({
    id: "p-l5-apply-reach-idea-order-tea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai", "noun-idee", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Reach them, offer the thought, and order the other one.",
    context: "Late afternoon, and the thought only just arrived.",
    answers: ["Excusez-moi. J'ai une idée. Je voudrais un thé."],
    alternatives: ["Excusez-moi, j'ai une idée. Je voudrais un thé."],
    ifCorrect: "Une idée, un thé. The pattern holds whatever you put in it.",
  }),
  weaveSeed({
    id: "p-l5-apply-order-coffee-question-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-j-ai", "chunk-une-question", "chunk-merci"],
    targets: ["chunk-une-question"],
    weaveType: "open",
    prompt: "Order, say what else you have, and close.",
    context: "You will ask it, but not before the coffee arrives.",
    answers: ["Je voudrais un café. J'ai une question. Merci."],
    alternatives: ["Je voudrais un café. J ai une question. Merci."],
    ifCorrect: "Un café, une question. Neither article is optional.",
  }),
  weaveSeed({
    id: "p-l5-apply-question-order-tea-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai", "chunk-une-question", "chunk-je-voudrais", "chunk-un-the", "chunk-merci"],
    targets: ["chunk-un-the"],
    weaveType: "open",
    prompt: "Say what you have, order the other one, and close.",
    context: "Both at once, at a counter, in one breath.",
    answers: ["J'ai une question. Je voudrais un thé. Merci."],
    alternatives: ["J ai une question. Je voudrais un thé. Merci."],
    ifCorrect: "Une question, un thé. Two articles, and the word decides each.",
  }),
  weaveSeed({
    id: "p-l5-apply-greet-idea-order-tea",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai", "noun-idee", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["noun-idee"],
    weaveType: "open",
    prompt: "Greet, offer the thought, and order the other one.",
    context: "You come in with something and want to talk it over.",
    answers: ["Bonjour. J'ai une idée. Je voudrais un thé."],
    alternatives: ["Bonjour, j'ai une idée. Je voudrais un thé."],
    ifCorrect: "Une idée, un thé, and the difference is not the meaning.",
  }),
];
