/**
 * L6 practice seeds — the whole small moment.
 *
 * L6 owns no new engine; it owns the ARC. So its seeds lean cumulative: the
 * language is all older, and what is being practised is holding several pieces
 * together in one moment without dropping any of them.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-006";

export const L6_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l6-retrieve-au-revoir",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Say goodbye.",
    context: "You are at the door with your coat on.",
    answers: ["Au revoir."],
    alternatives: ["Au revoir"],
    ifCorrect: "The moment closes as deliberately as it opened.",
  }),
  fillSeed({
    id: "p-l6-repair-did-not-catch-it",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-non-merci"],
    targets: ["chunk-je-ne-comprends-pas"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "They answer your question quickly and at length. You catch almost none of it.",
    correct: { id: "o-jncp", text: "Je ne comprends pas." },
    traps: [
      {
        id: "o-non-merci-catch",
        text: "Non merci, au revoir.",
        why: "That turns something down. They were answering you, not offering you anything.",
        tag: "meaning_shift",
      },
      {
        id: "o-merci-catch",
        text: "Merci beaucoup, au revoir.",
        why: "Polite, and it ends the exchange with you still lost.",
        tag: "meaning_shift",
      },
    ],
    short: "Je ne comprends pas.",
    explanation: "Saying it is not a failure in the moment; it is the sentence that keeps the moment going.",
  }),
  weaveSeed({
    id: "p-l6-produce-excuse-and-not-follow",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    weaveType: "context",
    prompt: "Cut in politely, then say it went past you.",
    context: "They are already moving on to the next thing and you are still behind.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas."],
    ifCorrect: "Polite, honest, and it stops the moment running away from you.",
  }),
  weaveSeed({
    id: "p-l6-apply-thanks-and-close",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    weaveType: "context",
    prompt: "Thank them and take your leave.",
    context: "You got what you came for and they are already turning back to their work.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci. Au revoir."],
    ifCorrect: "Two words, and the moment ends warmly.",
  }),
  weaveSeed({
    id: "p-l6-apply-this-is-the-place",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "context",
    prompt: "Tell them this is the place.",
    context: "Someone arrives behind you looking for the same meeting, and checks the door.",
    answers: ["C'est ici."],
    alternatives: ["C'est ici"],
    ifCorrect: "You are the one who knows now. That is a small promotion.",
  }),
  weaveSeed({
    id: "p-l6-apply-step-in-whole",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Step in, say you have arrived, and open your one question.",
    context: "The door opens and they look up. You have about two seconds.",
    answers: ["Bonjour. Je suis ici. J'ai une question."],
    alternatives: ["Bonjour, je suis ici. J'ai une question."],
    ifCorrect: "Three sentences you already had, doing one job together.",
    ifWrong: "Your meaning lands. Greet, place yourself, then say what you came for.",
  }),
  weaveSeed({
    id: "p-l6-apply-whole-moment",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-je-suis-ici",
      "chunk-j-ai-une-question",
      "chunk-merci",
      "chunk-au-revoir",
    ],
    targets: ["chunk-j-ai-une-question", "chunk-merci", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Take the whole moment, from the door to the door.",
    context: "In, ask your question, and out again. They are friendly and in a hurry.",
    answers: ["Bonjour. Je suis ici. J'ai une question. Merci. Au revoir."],
    alternatives: ["Bonjour, je suis ici. J'ai une question. Merci, au revoir."],
    ifCorrect: "That is a complete small moment in French, start to finish.",
    ifWrong: "Your meaning lands. Open it, say what you came for, then close it.",
  }),
  weaveSeed({
    id: "p-l6-apply-say-so-and-ask-again",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Say it went past you, then ask for it again.",
    context: "They answered quickly and at length, and you are still standing there.",
    answers: ["Je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: ["Je ne comprends pas, vous pouvez répéter ?"],
    ifCorrect: "Name the problem, then ask. The moment keeps going.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l6-build-close-warmly",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    prompt: "Close the moment.",
    context: "You got what you came for, and they are turning back to their work.",
    tiles: [
      { itemId: "chunk-merci", text: "Merci,", answerIndex: 0 },
      { itemId: "chunk-au-revoir", text: "au revoir.", answerIndex: 1 },
      { itemId: "chunk-bonjour", text: "bonjour" },
    ],
    target: "Merci, au revoir.",
    ifCorrect: "Two words, and the moment ends warmly.",
  }),
  buildSeed({
    id: "p-l6-build-step-in",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    prompt: "Step in, place yourself, and open your question.",
    context: "The door opens and they look up. You have about two seconds.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir." },
    ],
    target: "Bonjour. Je suis ici. J'ai une question.",
    ifCorrect: "Three sentences you already had, doing one job together.",
    ifWrong: "Greet, place yourself, then say what you came for.",
  }),
  buildSeed({
    id: "p-l6-build-the-repair-pair",
    operation: "repair",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "Build the whole repair.",
    context: "They answered fast, and they have paused, willing to go again.",
    tiles: [
      { itemId: "chunk-je-ne-comprends-pas", text: "Je ne comprends pas.", answerIndex: 0 },
      { itemId: "chunk-vous-pouvez-repeter", text: "Vous pouvez répéter ?", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Je ne comprends pas. Vous pouvez répéter ?",
    ifCorrect: "Name the problem, then ask. That order is what keeps it moving.",
    ifWrong: "Say what went wrong before you ask for it again.",
  }),
  fillSeed({
    id: "p-l6-listen-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Merci, au revoir.",
    prompt: "Listen. What is happening here?",
    correct: { id: "o-leaving", text: "Thanks, goodbye." },
    traps: [
      { id: "o-arriving", text: "Hello, I'm here.", why: "That opens a moment. This one ends it.", tag: "meaning_shift" },
      { id: "o-declining", text: "No thanks.", why: "That turns something down rather than closing a visit.", tag: "meaning_shift" },
    ],
    short: "Merci, au revoir.",
    explanation: "You will hear this at the end of almost every exchange.",
  }),
  weaveSeed({
    id: "p-l6-dictation-goodbye",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    audio: "Merci, au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci. Au revoir.", "merci, au revoir."],
    ifCorrect: "Both halves of the close, written back.",
  }),
  weaveSeed({
    id: "p-l6-dictation-excuse-not-follow",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    audio: "Excusez-moi, je ne comprends pas.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas.", "excusez-moi, je ne comprends pas."],
    ifCorrect: "A long one, caught whole. That is real listening.",
    ifWrong: "Two sentences you own, run together at speed.",
  }),
  weaveSeed({
    id: "p-l6-apply-decline-and-ask",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-une-question"],
    targets: ["chunk-non-merci", "chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Turn it down, then say what you came for.",
    context: "Someone offers you a coffee on the way in, and you have one thing to ask.",
    answers: ["Non merci. J'ai une question."],
    alternatives: ["Non merci, j'ai une question."],
    ifCorrect: "Declined warmly, and the reason you came is still on the table.",
    ifWrong: "Turn the offer down first, then open your question.",
  }),
  weaveSeed({
    id: "p-l6-apply-arrive-ask-and-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "In, ask, and out again.",
    context: "They are friendly and in a hurry, and you have one thing to settle.",
    answers: ["Bonjour. Je suis ici. J'ai une question. Au revoir."],
    alternatives: ["Bonjour, je suis ici. J'ai une question. Au revoir."],
    ifCorrect: "The whole visit, opened and closed by you.",
  }),
  weaveSeed({
    id: "p-l6-apply-decline-and-close",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-au-revoir"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down and close the moment.",
    context: "One more coffee at the door, and you are already late.",
    answers: ["Non merci. Au revoir !"],
    alternatives: ["Non merci, au revoir !", "Non merci. Au revoir."],
    ifCorrect: "Refusing and closing in one breath, without either sounding curt.",
  }),
  weaveSeed({
    id: "p-l6-apply-not-that-room-then-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-au-revoir", "chunk-excusez-moi"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Apologise for the interruption, say it is the wrong room, and go.",
    context: "Wrong door, a room full of strangers, and no reason to stay.",
    answers: ["Excusez-moi. Ce n'est pas ici. Au revoir."],
    alternatives: ["Excusez-moi, ce n'est pas ici. Au revoir."],
    ifCorrect: "Three seconds, and nobody is left wondering who you were.",
  }),
  weaveSeed({
    id: "p-l6-apply-confirm-the-room",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est", "chunk-oui"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Confirm it for them.",
    context: "Somebody arrives behind you looking for the same meeting.",
    answers: ["Oui, c'est ici."],
    alternatives: ["Oui. C'est ici.", "Oui, c est ici."],
    ifCorrect: "Now you are the one who knows.",
  }),
  fillSeed({
    id: "p-l6-choice-open-or-close-the-visit",
    operation: "repair", difficulty: "easy", surface: "choice", lesson: L,
    required: ["chunk-bonjour", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    prompt: "You have what you came for and are leaving. Which word?",
    correct: { id: "o-bye", text: "Au revoir." },
    traps: [
      { id: "o-hi", text: "Bonjour.", why: "That opens a visit. You are ending one.", tag: "meaning_shift" },
      { id: "o-here", text: "Je suis ici.", why: "That announces an arrival, which is the other end.", tag: "meaning_shift" },
    ],
    short: "Au revoir.",
    explanation: "The same visit needs a different word at each end.",
  }),
  fillSeed({
    id: "p-l6-listen-whole-visit",
    operation: "repair", difficulty: "hard", surface: "listen", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Bonjour. Je suis ici. Au revoir.",
    prompt: "Listen. How much of the visit did they do?",
    correct: { id: "o-all", text: "All of it: arrived, announced and left." },
    traps: [
      { id: "o-arrive", text: "Two of the three: arrived, announced.", why: "It ends with au revoir, so they closed it too.", tag: "meaning_shift" },
      { id: "o-ask", text: "All of it: arrived, asked and left.", why: "Nothing here is a question.", tag: "meaning_shift" },
    ],
    short: "Bonjour. Je suis ici. Au revoir.",
    explanation: "A visit has two ends, and both of them are yours to say.",
  }),
  buildSeed({
    id: "p-l6-build-whole-visit",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    prompt: "Assemble the whole visit.",
    context: "In, one question, and out again.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 3 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Bonjour. Je suis ici. J'ai une question. Au revoir.",
    ifCorrect: "Four sentences, four lessons, one visit.",
    ifWrong: "Right pieces. It opens with the greeting and closes with the goodbye.",
  }),
  weaveSeed({
    id: "p-l6-dictation-whole-visit",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Bonjour. Je suis ici. Au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Bonjour. Je suis ici. Au revoir."],
    alternatives: ["Bonjour, je suis ici. Au revoir."],
    ifCorrect: "Three sentences and a whole visit between them.",
  }),
  weaveSeed({
    id: "p-l6-apply-greet-thank-leave",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Greet, thank, and close.",
    context: "A shop you were in for ninety seconds.",
    answers: ["Bonjour. Merci. Au revoir."],
    alternatives: ["Bonjour, merci, au revoir."],
    ifCorrect: "Three words, and the whole visit was polite.",
  }),
  weaveSeed({
    id: "p-l6-apply-arrive-and-leave",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say you came, and that you are not staying.",
    context: "You promised to look in. They are on a call.",
    answers: ["Je suis ici. Au revoir."],
    alternatives: ["Je suis ici, au revoir."],
    ifCorrect: "Showing up counts even when it lasts four seconds.",
  }),
  weaveSeed({
    id: "p-l6-apply-question-then-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say what you have, then close.",
    context: "You ask on your way out, already holding the door.",
    answers: ["J'ai une question. Au revoir."],
    alternatives: ["J ai une question. Au revoir."],
    ifCorrect: "Asking as you leave is a real thing people do.",
  }),
  weaveSeed({
    id: "p-l6-repair-lost-then-leave",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say it did not land, and close.",
    context: "Out of time, and it is not going to land today.",
    answers: ["Je ne comprends pas. Au revoir."],
    alternatives: ["Je ne comprends pas, au revoir."],
    ifCorrect: "Saying so before you go is better than leaving them guessing.",
  }),
  weaveSeed({
    id: "p-l6-apply-wrong-place-leave",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say it is the wrong place, and close.",
    context: "You are out of time to keep looking today.",
    answers: ["Ce n'est pas ici. Au revoir."],
    alternatives: ["Ce n est pas ici. Au revoir."],
    ifCorrect: "Stopping out loud is kinder than drifting away.",
  }),
  weaveSeed({
    id: "p-l6-apply-confirm-then-leave",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-c-est", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Confirm you found it, and close.",
    context: "They waited at the door to be sure.",
    answers: ["C'est ici. Au revoir."],
    alternatives: ["C est ici. Au revoir."],
    ifCorrect: "The confirmation is what lets them go home.",
  }),
  weaveSeed({
    id: "p-l6-apply-reach-then-leave",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Get their attention, and close.",
    context: "You interrupted, briefly, and are stepping back out.",
    answers: ["Excusez-moi. Au revoir."],
    alternatives: ["Excusez-moi, au revoir."],
    ifCorrect: "Even a four-second interruption gets a proper ending.",
  }),
  weaveSeed({
    id: "p-l6-apply-not-me-then-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say you are not in there, and close.",
    context: "They are holding the door of a room you are not in.",
    answers: ["Je ne suis pas ici. Au revoir."],
    alternatives: ["Je ne suis pas ici, au revoir."],
    ifCorrect: "Two facts, and neither needs an apology.",
  }),
  weaveSeed({
    id: "p-l6-apply-arrive-thank-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-je-suis-ici"],
    weaveType: "open",
    prompt: "Announce yourself, thank them, and close.",
    context: "The whole visit, and it lasted a minute.",
    answers: ["Je suis ici. Merci. Au revoir."],
    alternatives: ["Je suis ici. Merci, au revoir."],
    ifCorrect: "Arrive, thank, leave. Most visits are exactly this.",
  }),
  weaveSeed({
    id: "p-l6-apply-greet-question-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question", "chunk-merci"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Greet, say what you have, and thank them.",
    context: "A stranger at a desk who owes you nothing.",
    answers: ["Bonjour. J'ai une question. Merci."],
    alternatives: ["Bonjour, j'ai une question. Merci."],
    ifCorrect: "The whole exchange, and not one new word in it.",
  }),
  weaveSeed({
    id: "p-l6-apply-reach-question-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-une-question", "chunk-merci"],
    targets: ["chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Reach them, say what you have, and thank them.",
    context: "They are mid-conversation with someone else.",
    answers: ["Excusez-moi. J'ai une question. Merci."],
    alternatives: ["Excusez-moi, j'ai une question. Merci."],
    ifCorrect: "Reach, ask, thank. The shape of nearly every request.",
  }),
  weaveSeed({
    id: "p-l6-repair-again-and-thanks",
    operation: "repair", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-vous-pouvez-repeter", "chunk-merci"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Ask for it again, and thank them.",
    context: "They said it once and moved straight on.",
    answers: ["Vous pouvez répéter ? Merci."],
    alternatives: ["Vous pouvez répéter ? Merci !"],
    ifCorrect: "Thanking for the repeat is what makes a third ask possible.",
  }),
  weaveSeed({
    id: "p-l6-repair-reach-again-thanks",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-vous-pouvez-repeter", "chunk-merci"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Reach them, ask for it again, and thank them.",
    context: "Their back is turned and they are already moving on.",
    answers: ["Excusez-moi. Vous pouvez répéter ? Merci."],
    alternatives: ["Excusez-moi, vous pouvez répéter ? Merci."],
    ifCorrect: "Three moves that between them rescue most missed sentences.",
  }),
  weaveSeed({
    id: "p-l6-repair-lost-again-thanks",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter", "chunk-merci"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say you did not follow, ask again, and thank them.",
    context: "Full speed, and you caught the first three words.",
    answers: ["Je ne comprends pas. Vous pouvez répéter ? Merci."],
    alternatives: ["Je ne comprends pas, vous pouvez répéter ? Merci."],
    ifCorrect: "Admit, ask, thank. Nobody has lost face.",
  }),
  weaveSeed({
    id: "p-l6-apply-confirm-thank-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-c-est", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Confirm, thank them, and close.",
    context: "They gave you directions and the directions worked.",
    answers: ["C'est ici. Merci. Au revoir."],
    alternatives: ["C est ici. Merci, au revoir."],
    ifCorrect: "Telling them it worked is how they know to give them again.",
  }),
  weaveSeed({
    id: "p-l6-apply-greet-confirm",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Greet them, and confirm the place.",
    context: "You arrive and they look up expecting a question.",
    answers: ["Bonjour. C'est ici."],
    alternatives: ["Bonjour, c'est ici."],
    ifCorrect: "Sometimes the answer arrives before the question.",
  }),
  // L6 had no slot-level question at all: every seed asked for a whole
  // utterance, so the one distinction the lesson keeps flagging -- j'ai for
  // what you have, je suis for what you are -- was never asked directly.
  fillSeed({
    id: "p-l6-retrieve-have-not-be",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-j-ai", "chunk-une-question"],
    targets: ["chunk-j-ai"],
    tags: ["j-ai-vs-je-suis"],
    prompt: "Which engine carries a question?",
    after: " une question.",
    correct: { id: "o-jai-q", text: "J'ai" },
    traps: [
      {
        id: "o-jesuis-q",
        text: "Je suis",
        why: "Je suis says what you are. A question is something you have, not something you are.",
        tag: "wrong_item",
      },
      {
        id: "o-jevais-q",
        text: "Je vais",
        why: "Je vais takes you somewhere. It cannot hold a question for you.",
        tag: "wrong_item",
      },
    ],
    short: "J'ai une question.",
    explanation: "French hands questions, hunger and ideas to j'ai. Je suis is for who and where you are.",
  }),
];
