/**
 * L6 practice seeds — the whole small moment.
 *
 * L6 owns no new engine; it owns the ARC. So its seeds lean cumulative: the
 * language is all older, and what is being practised is holding several pieces
 * together in one moment without dropping any of them.
 */
import { fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-006";

export const L6_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l6-retrieve-au-revoir",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Say goodbye.",
    context: "You are at the door with your coat on.",
    answers: ["Au revoir."],
    alternatives: ["Au revoir"],
    ifCorrect: "The moment closes as deliberately as it opened.",
  }),
  fillSeed({
    id: "p-l6-repair-did-not-catch-it",
    operation: "repair",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-non-merci"],
    targets: ["chunk-je-ne-comprends-pas"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "They answer your question quickly and at length. You catch almost none of it.",
    correct: { id: "o-jncp", text: "Je ne comprends pas." },
    traps: [
      {
        id: "o-non-merci-catch",
        text: "Non merci.",
        why: "That turns something down. They were answering you, not offering you anything.",
        tag: "meaning_shift",
      },
      {
        id: "o-merci-catch",
        text: "Merci.",
        why: "Polite, and it ends the exchange with you still lost.",
        tag: "meaning_shift",
      },
    ],
    short: "Je ne comprends pas.",
    explanation: "Saying it is not a failure in the moment; it is the sentence that keeps the moment going.",
  }),
  weaveSeed({
    id: "p-l6-produce-excuse-and-not-follow",
    operation: "produce",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    weaveType: "context",
    prompt: "Cut in politely, then say it went past you.",
    context: "They are already moving on to the next thing and you are still behind.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas."],
    ifCorrect: "Polite, honest, and it stops the moment running away from you.",
  }),
  weaveSeed({
    id: "p-l6-apply-thanks-and-close",
    operation: "apply",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    weaveType: "context",
    prompt: "Thank them and take your leave.",
    context: "You got what you came for and they are already turning back to their work.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci. Au revoir."],
    ifCorrect: "Two words, and the moment ends warmly.",
  }),
  weaveSeed({
    id: "p-l6-apply-this-is-the-place",
    operation: "apply",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "context",
    prompt: "Tell them this is the place.",
    context: "Someone arrives behind you looking for the same meeting, and checks the door.",
    answers: ["C'est ici."],
    alternatives: ["C'est ici"],
    ifCorrect: "You are the one who knows now. That is a small promotion.",
  }),
  weaveSeed({
    id: "p-l6-apply-step-in-whole",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Step in, say you have arrived, and open your one question.",
    context: "The door opens and they look up. You have about two seconds.",
    answers: ["Bonjour. Je suis ici. J'ai une question."],
    alternatives: ["Bonjour, je suis ici. J'ai une question."],
    ifCorrect: "Three sentences you already had, doing one job together.",
    ifWrong: "Your meaning lands. Greet, place yourself, then say what you came for.",
  }),
  weaveSeed({
    id: "p-l6-apply-whole-moment",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-je-suis-ici",
      "chunk-j-ai-une-question",
      "chunk-merci",
      "chunk-au-revoir",
    ],
    targets: ["chunk-j-ai-une-question", "chunk-merci", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Take the whole moment, from the door to the door.",
    context: "In, ask your question, and out again. They are friendly and in a hurry.",
    answers: ["Bonjour. Je suis ici. J'ai une question. Merci. Au revoir."],
    alternatives: ["Bonjour, je suis ici. J'ai une question. Merci, au revoir."],
    ifCorrect: "That is a complete small moment in French, start to finish.",
    ifWrong: "Your meaning lands. Open it, say what you came for, then close it.",
  }),
  weaveSeed({
    id: "p-l6-apply-say-so-and-ask-again",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Say it went past you, then ask for it again.",
    context: "They answered quickly and at length, and you are still standing there.",
    answers: ["Je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: ["Je ne comprends pas, vous pouvez répéter ?"],
    ifCorrect: "Name the problem, then ask. The moment keeps going.",
  }),
];
