/**
 * L6 practice seeds — the whole small moment.
 *
 * L6 owns no new engine; it owns the ARC. So its seeds lean cumulative: the
 * language is all older, and what is being practised is holding several pieces
 * together in one moment without dropping any of them.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-006";

export const L6_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l6-retrieve-au-revoir",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Say goodbye.",
    context: "You are at the door with your coat on.",
    answers: ["Au revoir."],
    alternatives: ["Au revoir"],
    ifCorrect: "The moment closes as deliberately as it opened.",
  }),
  fillSeed({
    id: "p-l6-repair-did-not-catch-it",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-non-merci"],
    targets: ["chunk-je-ne-comprends-pas"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "They answer your question quickly and at length. You catch almost none of it.",
    correct: { id: "o-jncp", text: "Je ne comprends pas." },
    traps: [
      {
        id: "o-non-merci-catch",
        text: "Non merci.",
        why: "That turns something down. They were answering you, not offering you anything.",
        tag: "meaning_shift",
      },
      {
        id: "o-merci-catch",
        text: "Merci.",
        why: "Polite, and it ends the exchange with you still lost.",
        tag: "meaning_shift",
      },
    ],
    short: "Je ne comprends pas.",
    explanation: "Saying it is not a failure in the moment; it is the sentence that keeps the moment going.",
  }),
  weaveSeed({
    id: "p-l6-produce-excuse-and-not-follow",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    weaveType: "context",
    prompt: "Cut in politely, then say it went past you.",
    context: "They are already moving on to the next thing and you are still behind.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas."],
    ifCorrect: "Polite, honest, and it stops the moment running away from you.",
  }),
  weaveSeed({
    id: "p-l6-apply-thanks-and-close",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    weaveType: "context",
    prompt: "Thank them and take your leave.",
    context: "You got what you came for and they are already turning back to their work.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci. Au revoir."],
    ifCorrect: "Two words, and the moment ends warmly.",
  }),
  weaveSeed({
    id: "p-l6-apply-this-is-the-place",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "context",
    prompt: "Tell them this is the place.",
    context: "Someone arrives behind you looking for the same meeting, and checks the door.",
    answers: ["C'est ici."],
    alternatives: ["C'est ici"],
    ifCorrect: "You are the one who knows now. That is a small promotion.",
  }),
  weaveSeed({
    id: "p-l6-apply-step-in-whole",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Step in, say you have arrived, and open your one question.",
    context: "The door opens and they look up. You have about two seconds.",
    answers: ["Bonjour. Je suis ici. J'ai une question."],
    alternatives: ["Bonjour, je suis ici. J'ai une question."],
    ifCorrect: "Three sentences you already had, doing one job together.",
    ifWrong: "Your meaning lands. Greet, place yourself, then say what you came for.",
  }),
  weaveSeed({
    id: "p-l6-apply-whole-moment",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-je-suis-ici",
      "chunk-j-ai-une-question",
      "chunk-merci",
      "chunk-au-revoir",
    ],
    targets: ["chunk-j-ai-une-question", "chunk-merci", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Take the whole moment, from the door to the door.",
    context: "In, ask your question, and out again. They are friendly and in a hurry.",
    answers: ["Bonjour. Je suis ici. J'ai une question. Merci. Au revoir."],
    alternatives: ["Bonjour, je suis ici. J'ai une question. Merci, au revoir."],
    ifCorrect: "That is a complete small moment in French, start to finish.",
    ifWrong: "Your meaning lands. Open it, say what you came for, then close it.",
  }),
  weaveSeed({
    id: "p-l6-apply-say-so-and-ask-again",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Say it went past you, then ask for it again.",
    context: "They answered quickly and at length, and you are still standing there.",
    answers: ["Je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: ["Je ne comprends pas, vous pouvez répéter ?"],
    ifCorrect: "Name the problem, then ask. The moment keeps going.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l6-build-close-warmly",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    prompt: "Close the moment.",
    context: "You got what you came for, and they are turning back to their work.",
    tiles: [
      { itemId: "chunk-merci", text: "Merci,", answerIndex: 0 },
      { itemId: "chunk-au-revoir", text: "au revoir.", answerIndex: 1 },
      { itemId: "chunk-bonjour", text: "bonjour" },
    ],
    target: "Merci, au revoir.",
    ifCorrect: "Two words, and the moment ends warmly.",
  }),
  buildSeed({
    id: "p-l6-build-step-in",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    targets: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-j-ai-une-question"],
    prompt: "Step in, place yourself, and open your question.",
    context: "The door opens and they look up. You have about two seconds.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir." },
    ],
    target: "Bonjour. Je suis ici. J'ai une question.",
    ifCorrect: "Three sentences you already had, doing one job together.",
    ifWrong: "Greet, place yourself, then say what you came for.",
  }),
  buildSeed({
    id: "p-l6-build-the-repair-pair",
    operation: "repair",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "Build the whole repair.",
    context: "They answered fast, and they have paused, willing to go again.",
    tiles: [
      { itemId: "chunk-je-ne-comprends-pas", text: "Je ne comprends pas.", answerIndex: 0 },
      { itemId: "chunk-vous-pouvez-repeter", text: "Vous pouvez répéter ?", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Je ne comprends pas. Vous pouvez répéter ?",
    ifCorrect: "Name the problem, then ask. That order is what keeps it moving.",
    ifWrong: "Say what went wrong before you ask for it again.",
  }),
  fillSeed({
    id: "p-l6-listen-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Merci, au revoir.",
    prompt: "Listen. What is happening here?",
    correct: { id: "o-leaving", text: "Thanks, goodbye." },
    traps: [
      { id: "o-arriving", text: "Hello, I'm here.", why: "That opens a moment. This one ends it.", tag: "meaning_shift" },
      { id: "o-declining", text: "No thanks.", why: "That turns something down rather than closing a visit.", tag: "meaning_shift" },
    ],
    short: "Merci, au revoir.",
    explanation: "You will hear this at the end of almost every exchange.",
  }),
  weaveSeed({
    id: "p-l6-dictation-goodbye",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-au-revoir"],
    audio: "Merci, au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci. Au revoir.", "merci, au revoir."],
    ifCorrect: "Both halves of the close, written back.",
  }),
  weaveSeed({
    id: "p-l6-dictation-excuse-not-follow",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-excusez-moi", "chunk-je-ne-comprends-pas"],
    audio: "Excusez-moi, je ne comprends pas.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Excusez-moi, je ne comprends pas."],
    alternatives: ["Excusez-moi. Je ne comprends pas.", "excusez-moi, je ne comprends pas."],
    ifCorrect: "A long one, caught whole. That is real listening.",
    ifWrong: "Two sentences you own, run together at speed.",
  }),
  weaveSeed({
    id: "p-l6-apply-decline-and-ask",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-j-ai-une-question"],
    targets: ["chunk-non-merci", "chunk-j-ai-une-question"],
    weaveType: "open",
    prompt: "Turn it down, then say what you came for.",
    context: "Someone offers you a coffee on the way in, and you have one thing to ask.",
    answers: ["Non merci. J'ai une question."],
    alternatives: ["Non merci, j'ai une question."],
    ifCorrect: "Declined warmly, and the reason you came is still on the table.",
    ifWrong: "Turn the offer down first, then open your question.",
  }),
];
