/**
 * L7 practice seeds — leaving.
 *
 * Earlier language appears as REQUIRED frame material, which is what
 * `requiredItemIds` is for: it gates eligibility without claiming the attempt
 * demonstrated it.
 *
 * WHAT THIS POOL MAY WORK, and why it is not everything L7 shows. Practice can
 * only exercise language the LESSON actually gave evidence for: a seed that
 * requires an item the learner has never been graded on is unservable forever,
 * because the reach check asks whether they own it and the answer stays no.
 * L7's Showcase introduces fourteen further items — au travail, à l'hôtel,
 * à demain, je pars, une autre fois, maintenant and the rest — and the lesson
 * body has no room to work them, so this pool deliberately does not either.
 * They are exposure until a lesson asks for them.
 *
 * Every surface below is a distinct communicative act. Where two share an
 * architecture they do different jobs: "Je vais au café." announces a
 * departure, "Non merci, je vais au café." declines one. What is NOT here is
 * the same sentence with the destination swapped for its own sake.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-007";

export const L7_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l7-retrieve-je-vais",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais", "chunk-a-la-maison"],
    weaveType: "mid",
    prompt: "I'm going home.",
    answers: ["Je vais à la maison."],
    alternatives: ["Je vais à la maison"],
    ifCorrect: "One frozen piece that moves you somewhere.",
  }),
  fillSeed({
    id: "p-l7-repair-which-mover",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-vais", "chunk-je-suis"],
    targets: ["chunk-je-vais"],
    prompt: "You are leaving for home. Which word moves you?",
    before: "Je ",
    after: " à la maison.",
    correct: { id: "o-vais", text: "vais" },
    traps: [
      {
        id: "o-suis-home",
        text: "suis",
        why: "That says you ARE at home. You are still here, on your way.",
        tag: "meaning_shift",
      },
      {
        id: "o-voudrais-home",
        text: "voudrais",
        why: "That asks for home rather than heading there.",
        tag: "meaning_shift",
      },
    ],
    short: "Je vais à la maison.",
    explanation: "Je vais moves you. Je suis places you.",
  }),
  fillSeed({
    id: "p-l7-retrieve-destination",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-a-la-maison", "chunk-je-vais"],
    targets: ["chunk-a-la-maison"],
    prompt: "Which piece names where you are heading?",
    before: "Je vais ",
    after: ".",
    correct: { id: "o-a-la-maison", text: "à la maison" },
    traps: [
      {
        id: "o-ici-dest",
        text: "ici",
        why: "That is where you already are, not where you are going.",
        tag: "meaning_shift",
      },
      {
        id: "o-au-revoir-dest",
        text: "au revoir",
        why: "That closes the moment. It is not a place.",
        tag: "wrong_item",
      },
    ],
    short: "Je vais à la maison.",
    explanation: "À la maison travels whole. You never take it apart.",
  }),
  weaveSeed({
    id: "p-l7-apply-go-and-close",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    weaveType: "context",
    prompt: "Say where you are going, then close the room behind you.",
    context: "Evening. People are still talking, but you are finished.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir."],
    ifCorrect: "Leaving has two halves and you did both.",
  }),
  weaveSeed({
    id: "p-l7-apply-yes-then-go",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui", "chunk-je-vais"],
    weaveType: "context",
    prompt: "Answer them, then say where you are going.",
    context: "They see you reaching for your coat and ask whether you are heading off. You are.",
    answers: ["Oui, je vais à la maison."],
    alternatives: ["Oui. Je vais à la maison."],
    ifCorrect: "Answer first, then the detail. Same shape as every other reply you own.",
  }),
  weaveSeed({
    id: "p-l7-apply-decline-and-go",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-je-vais"],
    weaveType: "open",
    prompt: "Turn the offer down, then say where you are heading.",
    context: "Your coat is on. They hold up the pot and offer you one more coffee.",
    answers: ["Non merci. Je vais à la maison."],
    alternatives: ["Non merci, je vais à la maison."],
    ifCorrect: "Declined warmly, and you are out of the door.",
    ifWrong: "Your meaning lands. Turn it down first, then say where you are going.",
  }),
  weaveSeed({
    id: "p-l7-apply-thanks-go-close",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-merci", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-je-vais", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Thank them, say where you are going, and close it.",
    context: "They walked you to the door at the end of a long day.",
    answers: ["Merci. Je vais à la maison. Au revoir."],
    alternatives: ["Merci, je vais à la maison. Au revoir."],
    ifCorrect: "Warm, clear, and finished. Nothing in it is new.",
    ifWrong: "Your meaning lands. Thanks, then where you are going, then goodbye.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l7-build-go-and-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    prompt: "Build the leaving.",
    context: "Evening. People are still talking, but you are finished.",
    tiles: [
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 0 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Je vais à la maison. Au revoir.",
    ifCorrect: "Where you are going, then the door closing. Both halves.",
    ifWrong: "Say where you are heading before you say goodbye.",
  }),
  buildSeed({
    id: "p-l7-build-decline-and-go",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-je-vais"],
    prompt: "Turn it down, then go.",
    context: "Your coat is on and they hold up the pot for one more coffee.",
    tiles: [
      { itemId: "chunk-non-merci", text: "Non merci.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-oui", text: "Oui," },
    ],
    target: "Non merci. Je vais à la maison.",
    ifCorrect: "Declined warmly, and you are out of the door.",
  }),
  buildSeed({
    id: "p-l7-build-thanks-go-close",
    operation: "apply",
    difficulty: "hard",
    surface: "build",
    lesson: L,
    required: ["chunk-merci", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-je-vais", "chunk-au-revoir"],
    prompt: "Take your leave properly.",
    context: "They walked you to the door at the end of a long day.",
    tiles: [
      { itemId: "chunk-merci", text: "Merci.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 3 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Merci. Je vais à la maison. Au revoir.",
    ifCorrect: "Warm, clear, finished. Nothing in it is new.",
    ifWrong: "Thanks, then where you are going, then goodbye.",
  }),
  fillSeed({
    id: "p-l7-listen-going-home",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    audio: "Je vais à la maison.",
    prompt: "Listen. What are they telling you?",
    correct: { id: "o-going-home", text: "I'm going home." },
    traps: [
      { id: "o-am-home", text: "I'm at home.", why: "That places them there already. This one is movement.", tag: "meaning_shift" },
      { id: "o-want-home", text: "I would like to go home.", why: "That asks. This one announces.", tag: "wrong_register" },
    ],
    short: "Je vais à la maison.",
    explanation: "Je vais moves you. Je suis places you.",
  }),
  weaveSeed({
    id: "p-l7-dictation-going-home",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais", "chunk-a-la-maison"],
    audio: "Je vais à la maison.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison."],
    alternatives: ["je vais à la maison.", "Je vais à la maison"],
    ifCorrect: "The destination travels whole, accent and all.",
    ifWrong: "À la maison is one piece. You never take it apart.",
  }),
  weaveSeed({
    id: "p-l7-dictation-leave-and-close",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    audio: "Je vais à la maison. Au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir.", "je vais à la maison. au revoir."],
    ifCorrect: "Two sentences, caught in one pass.",
  }),
  fillSeed({
    id: "p-l7-choice-announce-or-ask",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You have decided to leave. You are not asking permission. What do you say?",
    correct: { id: "o-announce", text: "Je vais à la maison." },
    traps: [
      { id: "o-ask-leave", text: "Je voudrais à la maison.", why: "Je voudrais asks for a thing, and it cannot carry a destination like this.", tag: "wrong_item" },
      { id: "o-be-home", text: "Je suis à la maison.", why: "That says you are already there, which you are not.", tag: "meaning_shift" },
    ],
    short: "Je vais à la maison.",
    explanation: "Leaving is announced, not requested.",
  }),
  // ── Where you are going ───────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-produce-cafe-destination",
    operation: "produce",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "mid",
    prompt: "Say where you are heading.",
    context: "Someone sees you with your coat on and asks what you are up to.",
    answers: ["Je vais au café."],
    alternatives: ["Je vais au café", "Je vais au cafe."],
    ifCorrect: "The engine, then the place with its own shape attached.",
  }),
  weaveSeed({
    id: "p-l7-apply-greet-then-going",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Open the moment, then say where you are heading.",
    context: "You pass a neighbour on the stairs. They have not seen you yet.",
    answers: ["Bonjour, je vais au café."],
    alternatives: ["Bonjour. Je vais au café.", "Bonjour, je vais au cafe."],
    ifCorrect: "Greeting first is what keeps it friendly rather than abrupt.",
  }),
  weaveSeed({
    id: "p-l7-apply-answer-where-going",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui", "chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Answer them, then say where.",
    context: "They call after you as you reach the door: « Vous partez ? »",
    answers: ["Oui, je vais à la maison."],
    alternatives: ["Oui, je vais à la maison", "Oui je vais a la maison."],
    ifCorrect: "Answering first, then the detail. That order is the natural one.",
  }),
  weaveSeed({
    id: "p-l7-apply-decline-with-destination",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Turn it down, and let them know why.",
    context: "They are holding the pot out to you and it is already late. « Un café ? »",
    answers: ["Non merci, je vais à la maison."],
    alternatives: ["Non merci. Je vais à la maison.", "Non, merci, je vais à la maison."],
    ifCorrect: "The reason does the softening. A bare non merci is colder than it sounds.",
  }),
  buildSeed({
    id: "p-l7-build-going-and-closing",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    prompt: "Put the whole leaving back together.",
    context: "Your hand is on the door and the room is still talking.",
    tiles: [
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 0 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Je vais à la maison. Au revoir.",
    ifCorrect: "Where you are going, then the door closing behind you.",
    ifWrong: "All the right pieces. The destination comes before the goodbye.",
  }),
  fillSeed({
    id: "p-l7-repair-which-destination-shape",
    operation: "repair",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-gare"],
    targets: ["chunk-a-la-gare"],
    prompt: "The station does not take the same shape as the café. Which one?",
    before: "Je vais ",
    after: " gare.",
    correct: { id: "o-ala", text: "à la" },
    traps: [
      { id: "o-au", text: "au", why: "Au belongs to café. Gare carries à la, like à la maison." },
      { id: "o-al", text: "à l'", why: "À l' is for a place starting with a vowel sound." },
    ],
    short: "à la",
    explanation: "Je vais à la gare. The shape belongs to the place and never changes.",
  }),

  // ── Closing the moment ────────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-retrieve-warm-thanks",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "mid",
    prompt: "Thank them, more than in passing.",
    context: "They went and found the thing you needed instead of pointing at a shelf.",
    answers: ["Merci beaucoup."],
    alternatives: ["Merci beaucoup !", "Merci beaucoup"],
    ifCorrect: "Beaucoup is what turns an acknowledgement into thanks.",
  }),
  weaveSeed({
    id: "p-l7-produce-thanks-and-goodbye",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Thank them warmly and close.",
    context: "The counter is done with you and there is a queue behind.",
    answers: ["Merci beaucoup, au revoir !"],
    alternatives: ["Merci beaucoup, au revoir.", "Merci beaucoup au revoir"],
    ifCorrect: "Two moves, one breath. That is how a French counter ends.",
  }),
  weaveSeed({
    id: "p-l7-apply-close-the-evening",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Thank them, then wish them the hours ahead.",
    context: "They stayed past closing to sort it out for you, and it is dark outside.",
    answers: ["Merci beaucoup, bonne soirée !"],
    alternatives: ["Merci beaucoup, bonne soirée.", "Merci beaucoup bonne soirée"],
    ifCorrect: "Bonne soirée is for an evening they have not had yet.",
  }),
  weaveSeed({
    id: "p-l7-apply-goodbye-and-evening",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-au-revoir", "chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Close it, and leave them something for the evening.",
    context: "You are the last one out and they are locking up behind you.",
    answers: ["Au revoir, bonne soirée !"],
    alternatives: ["Au revoir, bonne soirée.", "Au revoir bonne soirée"],
    ifCorrect: "Au revoir ends the exchange; bonne soirée hands them the rest of the day.",
  }),
  buildSeed({
    id: "p-l7-build-the-warm-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    prompt: "Assemble the warm close.",
    context: "They did you a real favour and the day is nearly over.",
    tiles: [
      { itemId: "chunk-merci-beaucoup", text: "Merci beaucoup,", answerIndex: 0 },
      { itemId: "chunk-bonne-soiree", text: "bonne soirée !", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Merci beaucoup, bonne soirée !",
    ifCorrect: "Thanks first, then the wish. Reversed, it sounds like an afterthought.",
    ifWrong: "Right pieces. The thanks opens the close.",
  }),

  // ── Leaving early, kindly ─────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-retrieve-must-go",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "mid",
    prompt: "Say you have to go.",
    context: "The thing is still running and your train is not going to wait.",
    answers: ["Je dois partir."],
    alternatives: ["Je dois partir", "Je dois partir !"],
    ifCorrect: "Dois puts the reason outside your own wish, which is what makes it polite.",
  }),
  weaveSeed({
    id: "p-l7-produce-sorry-must-go",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole", "chunk-je-dois-partir"],
    weaveType: "mid",
    prompt: "Apologise, then say you have to go.",
    context: "You are standing up while somebody is still mid-sentence.",
    answers: ["Désolé, je dois partir."],
    alternatives: ["Desole, je dois partir.", "Désolée, je dois partir.", "Désolé je dois partir"],
    ifCorrect: "The apology lands before the leaving does. That is the whole trick.",
  }),
  weaveSeed({
    id: "p-l7-apply-leave-early-and-close",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir", "chunk-au-revoir"],
    targets: ["chunk-je-dois-partir", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Get yourself out of the room without being rude.",
    context: "Half the table is still eating and you have twenty minutes to cross town.",
    answers: ["Désolé, je dois partir. Au revoir."],
    alternatives: ["Désolé, je dois partir. Au revoir !", "Desole, je dois partir. Au revoir."],
    ifCorrect: "Apology, reason, close. Three small moves and nobody is offended.",
  }),
  weaveSeed({
    id: "p-l7-apply-must-go-with-thanks",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-dois-partir", "chunk-merci-beaucoup"],
    targets: ["chunk-je-dois-partir", "chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Leave, and make sure they know it was good.",
    context: "They cooked. You have to be somewhere. They are watching you find your coat.",
    answers: ["Je dois partir. Merci beaucoup !"],
    alternatives: ["Je dois partir. Merci beaucoup.", "Je dois partir, merci beaucoup !"],
    ifCorrect: "Leaving on the thanks rather than the reason is what makes it warm.",
  }),
  weaveSeed({
    id: "p-l7-repair-decline-and-leave",
    operation: "repair",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-dois-partir"],
    targets: ["chunk-non-merci", "chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Turn the offer down, and give the reason.",
    context: "They are already pouring and you are already late. « Un café ? »",
    answers: ["Non merci, je dois partir."],
    alternatives: ["Non merci. Je dois partir.", "Non, merci, je dois partir."],
    ifCorrect: "A refusal with a reason is not a refusal, it is an apology.",
  }),
  fillSeed({
    id: "p-l7-repair-sorry-or-thanks",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-desole", "chunk-merci", "chunk-je-dois-partir"],
    targets: ["chunk-desole"],
    prompt: "You are about to interrupt something. Which word opens it?",
    before: "",
    after: ", je dois partir.",
    correct: { id: "o-des", text: "Désolé" },
    traps: [
      { id: "o-mer", text: "Merci", why: "Merci thanks them. It does not apologise for cutting the thing short." },
      { id: "o-non", text: "Non merci", why: "Non merci refuses an offer. Nobody has offered you anything here." },
    ],
    short: "Désolé",
    explanation: "Désolé, je dois partir. The apology is what buys the interruption.",
  }),

  // ── Leaving in the middle of something ────────────────────────────────────
  weaveSeed({
    id: "p-l7-repair-lost-it-on-the-way-out",
    operation: "repair",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-desole", "chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-desole"],
    weaveType: "open",
    prompt: "Apologise, say it went past you, then ask for it again.",
    context: "They said something about tomorrow as you were already turning to leave.",
    answers: ["Désolé, je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: [
      "Desole, je ne comprends pas. Vous pouvez répéter ?",
      "Désolé, je ne comprends pas, vous pouvez répéter ?",
    ],
    ifCorrect: "Three moves: soften it, name the problem, ask for the fix.",
  }),
  weaveSeed({
    id: "p-l7-apply-question-before-leaving",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Get the one thing in, and say why it cannot wait.",
    context: "Your coat is on, everyone is standing, and there is still something you need.",
    answers: ["J'ai une question. Je dois partir."],
    alternatives: ["J ai une question. Je dois partir.", "J'ai une question, je dois partir."],
    ifCorrect: "The leaving is what turns a late question into a reasonable one.",
  }),

  // ── Ordering, then leaving ────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-order-then-go",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Order, and warn them you cannot stay.",
    context: "You want one before the train, and the queue behind you is long.",
    answers: ["Je voudrais un café. Je dois partir."],
    alternatives: ["Je voudrais un café, je dois partir."],
    ifCorrect: "Saying you are leaving turns a takeaway request into a courtesy.",
  }),
  weaveSeed({
    id: "p-l7-apply-hungry-so-going",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Say how you feel, then what you are doing about it.",
    context: "It is past two and nobody has stopped for lunch.",
    answers: ["J'ai faim. Je vais au café."],
    alternatives: ["J'ai faim, je vais au café.", "J ai faim. Je vais au café."],
    ifCorrect: "The feeling explains the leaving. That is why the order is this way round.",
  }),
  weaveSeed({
    id: "p-l7-apply-arrive-then-leave",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-dois-partir", "chunk-merci-beaucoup"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Announce yourself, then say you cannot stay long.",
    context: "You promised you would come by, and you have ten minutes.",
    answers: ["Je suis ici. Je dois partir."],
    alternatives: ["Je suis ici, je dois partir."],
    ifCorrect: "Saying it up front is kinder than leaving suddenly later.",
  }),

  // ── Hearing it ────────────────────────────────────────────────────────────
  fillSeed({
    id: "p-l7-listen-which-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-merci-beaucoup"],
    audio: "Merci beaucoup, au revoir !",
    prompt: "Listen. How warmly did they thank you?",
    correct: { id: "o-warm", text: "Thank you very much, goodbye." },
    traps: [
      { id: "o-plain", text: "Thanks, goodbye.", why: "That is merci on its own. You heard the longer, warmer one.", tag: "meaning_shift" },
      { id: "o-evening", text: "Goodbye, have a good evening.", why: "No evening was mentioned. The second half was the goodbye itself.", tag: "meaning_shift" },
    ],
    short: "Merci beaucoup, au revoir !",
    explanation: "Beaucoup is the difference between polite and grateful.",
  }),
  fillSeed({
    id: "p-l7-listen-the-evening-wish",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    audio: "Au revoir, bonne soirée !",
    prompt: "Listen. What did they wish you?",
    correct: { id: "o-evening", text: "A good evening." },
    traps: [
      { id: "o-day", text: "A good day.", why: "That is bonne journée. You heard the one for the hours after dark.", tag: "meaning_shift" },
      { id: "o-nothing", text: "Nothing, they just said goodbye.", why: "There was a second half, and it was a wish.", tag: "meaning_shift" },
    ],
    short: "Au revoir, bonne soirée !",
    explanation: "Bonne soirée is for an evening they have not had yet.",
  }),
  weaveSeed({
    id: "p-l7-dictation-must-go",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole", "chunk-je-dois-partir"],
    audio: "Désolé, je dois partir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Désolé, je dois partir."],
    alternatives: ["Desole, je dois partir.", "Désolée, je dois partir."],
    ifCorrect: "Heard and written. Désolé carries the accents you can hear.",
  }),
  weaveSeed({
    id: "p-l7-dictation-warm-close",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    audio: "Merci beaucoup, bonne soirée !",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci beaucoup, bonne soirée !"],
    alternatives: ["Merci beaucoup, bonne soirée.", "Merci beaucoup bonne soiree"],
    ifCorrect: "Two chunks, one closing.",
  }),
  weaveSeed({
    id: "p-l7-dictation-going-to-the-cafe",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    audio: "Je vais au café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais au café."],
    alternatives: ["Je vais au cafe.", "Je vais au café"],
    ifCorrect: "Au café, heard as one piece and written as one.",
  }),
];
