/**
 * L7 practice seeds — leaving.
 *
 * Earlier language appears as REQUIRED frame material, which is what
 * `requiredItemIds` is for: it gates eligibility without claiming the attempt
 * demonstrated it.
 *
 * WHAT THIS POOL MAY WORK, and why it is not everything L7 shows. Practice can
 * only exercise language the LESSON actually gave evidence for: a seed that
 * requires an item the learner has never been graded on is unservable forever,
 * because the reach check asks whether they own it and the answer stays no.
 * L7's Showcase introduces fourteen further items — au travail, à l'hôtel,
 * à demain, je pars, une autre fois, maintenant and the rest — and the lesson
 * body has no room to work them, so this pool deliberately does not either.
 * They are exposure until a lesson asks for them.
 *
 * WHAT "the lesson graded it" ACTUALLY GATES. `seedIsLawfulFor` requires the
 * learner to have reached every ITEM a seed lists in `requiredItemIds`. It says
 * nothing about the SENTENCE: a seed may compose any utterance it likes from
 * items the learner owns. So this pool is not limited to sentences L7 showed —
 * it is limited to L7's twelve declared targets plus the thirty-three items
 * reachable after L1-L7, combined into situations the lesson never had room to
 * stage.
 *
 * Every surface below is a distinct communicative act. Where two share an
 * architecture they do different jobs: "Je vais au café." announces a
 * departure, "Non merci, je vais au café." declines one, and "J'ai faim. Je
 * vais au café." explains one. What is NOT here is the same sentence with a
 * word swapped for its own sake, or one utterance counted once per interaction.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-007";

export const L7_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l7-retrieve-je-vais",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais", "chunk-a-la-maison"],
    weaveType: "mid",
    prompt: "I'm going home.",
    answers: ["Je vais à la maison."],
    alternatives: ["Je vais à la maison"],
    ifCorrect: "One frozen piece that moves you somewhere.",
  }),
  fillSeed({
    id: "p-l7-repair-which-mover",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-vais", "chunk-je-suis"],
    targets: ["chunk-je-vais"],
    prompt: "You are leaving for home. Which word moves you?",
    before: "Je ",
    after: " à la maison.",
    correct: { id: "o-vais", text: "vais" },
    traps: [
      {
        id: "o-suis-home",
        text: "suis",
        why: "That says you ARE at home. You are still here, on your way.",
        tag: "meaning_shift",
      },
      {
        id: "o-voudrais-home",
        text: "voudrais",
        why: "That asks for home rather than heading there.",
        tag: "meaning_shift",
      },
    ],
    short: "Je vais à la maison.",
    explanation: "Je vais moves you. Je suis places you.",
  }),
  fillSeed({
    id: "p-l7-retrieve-destination",
    operation: "retrieve",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-a-la-maison", "chunk-je-vais"],
    targets: ["chunk-a-la-maison"],
    prompt: "Which piece names where you are heading?",
    before: "Je vais ",
    after: ".",
    correct: { id: "o-a-la-maison", text: "à la maison" },
    traps: [
      {
        id: "o-ici-dest",
        text: "ici",
        why: "That is where you already are, not where you are going.",
        tag: "meaning_shift",
      },
      {
        id: "o-au-revoir-dest",
        text: "au revoir",
        why: "That closes the moment. It is not a place.",
        tag: "wrong_item",
      },
    ],
    short: "Je vais à la maison.",
    explanation: "À la maison travels whole. You never take it apart.",
  }),
  weaveSeed({
    id: "p-l7-apply-go-and-close",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    weaveType: "context",
    prompt: "Say where you are going, then close the room behind you.",
    context: "Evening. People are still talking, but you are finished.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir."],
    ifCorrect: "Leaving has two halves and you did both.",
  }),
  weaveSeed({
    id: "p-l7-apply-yes-then-go",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui", "chunk-je-vais"],
    weaveType: "context",
    prompt: "Answer them, then say where you are going.",
    context: "They see you reaching for your coat and ask whether you are heading off. You are.",
    answers: ["Oui, je vais à la maison."],
    alternatives: ["Oui. Je vais à la maison."],
    ifCorrect: "Answer first, then the detail. Same shape as every other reply you own.",
  }),
  weaveSeed({
    id: "p-l7-apply-decline-and-go",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-je-vais"],
    weaveType: "open",
    prompt: "Turn the offer down, then say where you are heading.",
    context: "Your coat is on. They hold up the pot and offer you one more coffee.",
    answers: ["Non merci. Je vais à la maison."],
    alternatives: ["Non merci, je vais à la maison."],
    ifCorrect: "Declined warmly, and you are out of the door.",
    ifWrong: "Your meaning lands. Turn it down first, then say where you are going.",
  }),
  weaveSeed({
    id: "p-l7-apply-thanks-go-close",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-merci", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-je-vais", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Thank them, say where you are going, and close it.",
    context: "They walked you to the door at the end of a long day.",
    answers: ["Merci. Je vais à la maison. Au revoir."],
    alternatives: ["Merci, je vais à la maison. Au revoir."],
    ifCorrect: "Warm, clear, and finished. Nothing in it is new.",
    ifWrong: "Your meaning lands. Thanks, then where you are going, then goodbye.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l7-build-go-and-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    prompt: "Build the leaving.",
    context: "Evening. People are still talking, but you are finished.",
    tiles: [
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 0 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Je vais à la maison. Au revoir.",
    ifCorrect: "Where you are going, then the door closing. Both halves.",
    ifWrong: "Say where you are heading before you say goodbye.",
  }),
  buildSeed({
    id: "p-l7-build-decline-and-go",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-je-vais"],
    prompt: "Turn it down, then go.",
    context: "Your coat is on and they hold up the pot for one more coffee.",
    tiles: [
      { itemId: "chunk-non-merci", text: "Non merci.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-oui", text: "Oui," },
    ],
    target: "Non merci. Je vais à la maison.",
    ifCorrect: "Declined warmly, and you are out of the door.",
  }),
  buildSeed({
    id: "p-l7-build-thanks-go-close",
    operation: "apply",
    difficulty: "hard",
    surface: "build",
    lesson: L,
    required: ["chunk-merci", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-merci", "chunk-je-vais", "chunk-au-revoir"],
    prompt: "Take your leave properly.",
    context: "They walked you to the door at the end of a long day.",
    tiles: [
      { itemId: "chunk-merci", text: "Merci.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 3 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Merci. Je vais à la maison. Au revoir.",
    ifCorrect: "Warm, clear, finished. Nothing in it is new.",
    ifWrong: "Thanks, then where you are going, then goodbye.",
  }),
  fillSeed({
    id: "p-l7-listen-going-home",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    audio: "Je vais à la maison.",
    prompt: "Listen. What are they telling you?",
    correct: { id: "o-going-home", text: "I'm going home." },
    traps: [
      { id: "o-am-home", text: "I'm at home.", why: "That places them there already. This one is movement.", tag: "meaning_shift" },
      { id: "o-want-home", text: "I would like to go home.", why: "That asks. This one announces.", tag: "wrong_register" },
    ],
    short: "Je vais à la maison.",
    explanation: "Je vais moves you. Je suis places you.",
  }),
  weaveSeed({
    id: "p-l7-dictation-going-home",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais", "chunk-a-la-maison"],
    audio: "Je vais à la maison.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison."],
    alternatives: ["je vais à la maison.", "Je vais à la maison"],
    ifCorrect: "The destination travels whole, accent and all.",
    ifWrong: "À la maison is one piece. You never take it apart.",
  }),
  weaveSeed({
    id: "p-l7-dictation-leave-and-close",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    audio: "Je vais à la maison. Au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir.", "je vais à la maison. au revoir."],
    ifCorrect: "Two sentences, caught in one pass.",
  }),
  fillSeed({
    id: "p-l7-choice-announce-or-ask",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You have decided to leave. You are not asking permission. What do you say?",
    correct: { id: "o-announce", text: "Je vais à la maison." },
    traps: [
      { id: "o-ask-leave", text: "Je voudrais à la maison.", why: "Je voudrais asks for a thing, and it cannot carry a destination like this.", tag: "wrong_item" },
      { id: "o-be-home", text: "Je suis à la maison.", why: "That says you are already there, which you are not.", tag: "meaning_shift" },
    ],
    short: "Je vais à la maison.",
    explanation: "Leaving is announced, not requested.",
  }),
  // ── Where you are going ───────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-produce-cafe-destination",
    operation: "produce",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "mid",
    prompt: "Say where you are heading.",
    context: "Someone sees you with your coat on and asks what you are up to.",
    answers: ["Je vais au café."],
    alternatives: ["Je vais au café", "Je vais au cafe."],
    ifCorrect: "The engine, then the place with its own shape attached.",
  }),
  weaveSeed({
    id: "p-l7-apply-greet-then-going",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-bonjour", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Open the moment, then say where you are heading.",
    context: "You pass a neighbour on the stairs. They have not seen you yet.",
    answers: ["Bonjour, je vais au café."],
    alternatives: ["Bonjour. Je vais au café.", "Bonjour, je vais au cafe."],
    ifCorrect: "Greeting first is what keeps it friendly rather than abrupt.",
  }),
  weaveSeed({
    id: "p-l7-apply-answer-where-going",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui", "chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Answer them, then say where.",
    context: "They call after you as you reach the door: « Vous partez ? »",
    answers: ["Oui, je vais à la maison."],
    alternatives: ["Oui, je vais à la maison", "Oui je vais a la maison."],
    ifCorrect: "Answering first, then the detail. That order is the natural one.",
  }),
  weaveSeed({
    id: "p-l7-apply-decline-with-destination",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci", "chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Turn it down, and let them know why.",
    context: "They are holding the pot out to you and it is already late. « Un café ? »",
    answers: ["Non merci, je vais à la maison."],
    alternatives: ["Non merci. Je vais à la maison.", "Non, merci, je vais à la maison."],
    ifCorrect: "The reason does the softening. A bare non merci is colder than it sounds.",
  }),
  buildSeed({
    id: "p-l7-build-going-and-closing",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    prompt: "Put the whole leaving back together.",
    context: "Your hand is on the door and the room is still talking.",
    tiles: [
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 0 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Je vais à la maison. Au revoir.",
    ifCorrect: "Where you are going, then the door closing behind you.",
    ifWrong: "All the right pieces. The destination comes before the goodbye.",
  }),
  fillSeed({
    id: "p-l7-repair-which-destination-shape",
    operation: "repair",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-gare"],
    targets: ["chunk-a-la-gare"],
    prompt: "The station does not take the same shape as the café. Which one?",
    before: "Je vais ",
    after: " gare.",
    correct: { id: "o-ala", text: "à la" },
    traps: [
      { id: "o-au", text: "au", why: "Au belongs to café. Gare carries à la, like à la maison." },
      { id: "o-al", text: "à l'", why: "À l' is for a place starting with a vowel sound." },
    ],
    short: "à la",
    explanation: "Je vais à la gare. The shape belongs to the place and never changes.",
  }),

  // ── Closing the moment ────────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-retrieve-warm-thanks",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "mid",
    prompt: "Thank them, more than in passing.",
    context: "They went and found the thing you needed instead of pointing at a shelf.",
    answers: ["Merci beaucoup."],
    alternatives: ["Merci beaucoup !", "Merci beaucoup"],
    ifCorrect: "Beaucoup is what turns an acknowledgement into thanks.",
  }),
  weaveSeed({
    id: "p-l7-produce-thanks-and-goodbye",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Thank them warmly and close.",
    context: "The counter is done with you and there is a queue behind.",
    answers: ["Merci beaucoup, au revoir !"],
    alternatives: ["Merci beaucoup, au revoir.", "Merci beaucoup au revoir"],
    ifCorrect: "Two moves, one breath. That is how a French counter ends.",
  }),
  weaveSeed({
    id: "p-l7-apply-close-the-evening",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Thank them, then wish them the hours ahead.",
    context: "They stayed past closing to sort it out for you, and it is dark outside.",
    answers: ["Merci beaucoup, bonne soirée !"],
    alternatives: ["Merci beaucoup, bonne soirée.", "Merci beaucoup bonne soirée"],
    ifCorrect: "Bonne soirée is for an evening they have not had yet.",
  }),
  weaveSeed({
    id: "p-l7-apply-goodbye-and-evening",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-au-revoir", "chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Close it, and leave them something for the evening.",
    context: "You are the last one out and they are locking up behind you.",
    answers: ["Au revoir, bonne soirée !"],
    alternatives: ["Au revoir, bonne soirée.", "Au revoir bonne soirée"],
    ifCorrect: "Au revoir ends the exchange; bonne soirée hands them the rest of the day.",
  }),
  buildSeed({
    id: "p-l7-build-the-warm-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    prompt: "Assemble the warm close.",
    context: "They did you a real favour and the day is nearly over.",
    tiles: [
      { itemId: "chunk-merci-beaucoup", text: "Merci beaucoup,", answerIndex: 0 },
      { itemId: "chunk-bonne-soiree", text: "bonne soirée !", answerIndex: 1 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Merci beaucoup, bonne soirée !",
    ifCorrect: "Thanks first, then the wish. Reversed, it sounds like an afterthought.",
    ifWrong: "Right pieces. The thanks opens the close.",
  }),

  // ── Leaving early, kindly ─────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-retrieve-must-go",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "mid",
    prompt: "Say you have to go.",
    context: "The thing is still running and your train is not going to wait.",
    answers: ["Je dois partir."],
    alternatives: ["Je dois partir", "Je dois partir !"],
    ifCorrect: "Dois puts the reason outside your own wish, which is what makes it polite.",
  }),
  weaveSeed({
    id: "p-l7-produce-sorry-must-go",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole", "chunk-je-dois-partir"],
    weaveType: "mid",
    prompt: "Apologise, then say you have to go.",
    context: "You are standing up while somebody is still mid-sentence.",
    answers: ["Désolé, je dois partir."],
    alternatives: ["Desole, je dois partir.", "Désolée, je dois partir.", "Désolé je dois partir"],
    ifCorrect: "The apology lands before the leaving does. That is the whole trick.",
  }),
  weaveSeed({
    id: "p-l7-apply-leave-early-and-close",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir", "chunk-au-revoir"],
    targets: ["chunk-je-dois-partir", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Get yourself out of the room without being rude.",
    context: "Half the table is still eating and you have twenty minutes to cross town.",
    answers: ["Désolé, je dois partir. Au revoir."],
    alternatives: ["Désolé, je dois partir. Au revoir !", "Desole, je dois partir. Au revoir."],
    ifCorrect: "Apology, reason, close. Three small moves and nobody is offended.",
  }),
  weaveSeed({
    id: "p-l7-apply-must-go-with-thanks",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-dois-partir", "chunk-merci-beaucoup"],
    targets: ["chunk-je-dois-partir", "chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Leave, and make sure they know it was good.",
    context: "They cooked. You have to be somewhere. They are watching you find your coat.",
    answers: ["Je dois partir. Merci beaucoup !"],
    alternatives: ["Je dois partir. Merci beaucoup.", "Je dois partir, merci beaucoup !"],
    ifCorrect: "Leaving on the thanks rather than the reason is what makes it warm.",
  }),
  weaveSeed({
    id: "p-l7-repair-decline-and-leave",
    operation: "repair",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-non-merci", "chunk-je-dois-partir"],
    targets: ["chunk-non-merci", "chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Turn the offer down, and give the reason.",
    context: "They are already pouring and you are already late. « Un café ? »",
    answers: ["Non merci, je dois partir."],
    alternatives: ["Non merci. Je dois partir.", "Non, merci, je dois partir."],
    ifCorrect: "A refusal with a reason is not a refusal, it is an apology.",
  }),
  fillSeed({
    id: "p-l7-repair-sorry-or-thanks",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-desole", "chunk-merci", "chunk-je-dois-partir"],
    targets: ["chunk-desole"],
    prompt: "You are about to interrupt something. Which word opens it?",
    before: "",
    after: ", je dois partir.",
    correct: { id: "o-des", text: "Désolé" },
    traps: [
      { id: "o-mer", text: "Merci", why: "Merci thanks them. It does not apologise for cutting the thing short." },
      { id: "o-non", text: "Non merci", why: "Non merci refuses an offer. Nobody has offered you anything here." },
    ],
    short: "Désolé",
    explanation: "Désolé, je dois partir. The apology is what buys the interruption.",
  }),

  // ── Leaving in the middle of something ────────────────────────────────────
  weaveSeed({
    id: "p-l7-repair-lost-it-on-the-way-out",
    operation: "repair",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-desole", "chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-desole"],
    weaveType: "open",
    prompt: "Apologise, say it went past you, then ask for it again.",
    context: "They said something about tomorrow as you were already turning to leave.",
    answers: ["Désolé, je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: [
      "Desole, je ne comprends pas. Vous pouvez répéter ?",
      "Désolé, je ne comprends pas, vous pouvez répéter ?",
    ],
    ifCorrect: "Three moves: soften it, name the problem, ask for the fix.",
  }),
  weaveSeed({
    id: "p-l7-apply-question-before-leaving",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Get the one thing in, and say why it cannot wait.",
    context: "Your coat is on, everyone is standing, and there is still something you need.",
    answers: ["J'ai une question. Je dois partir."],
    alternatives: ["J ai une question. Je dois partir.", "J'ai une question, je dois partir."],
    ifCorrect: "The leaving is what turns a late question into a reasonable one.",
  }),

  // ── Ordering, then leaving ────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-order-then-go",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Order, and warn them you cannot stay.",
    context: "You want one before the train, and the queue behind you is long.",
    answers: ["Je voudrais un café. Je dois partir."],
    alternatives: ["Je voudrais un café, je dois partir."],
    ifCorrect: "Saying you are leaving turns a takeaway request into a courtesy.",
  }),
  weaveSeed({
    id: "p-l7-apply-hungry-so-going",
    operation: "apply",
    difficulty: "medium",
    surface: "context",
    lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Say how you feel, then what you are doing about it.",
    context: "It is past two and nobody has stopped for lunch.",
    answers: ["J'ai faim. Je vais au café."],
    alternatives: ["J'ai faim, je vais au café.", "J ai faim. Je vais au café."],
    ifCorrect: "The feeling explains the leaving. That is why the order is this way round.",
  }),
  weaveSeed({
    id: "p-l7-apply-arrive-then-leave",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-dois-partir", "chunk-merci-beaucoup"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Announce yourself, then say you cannot stay long.",
    context: "You promised you would come by, and you have ten minutes.",
    answers: ["Je suis ici. Je dois partir."],
    alternatives: ["Je suis ici, je dois partir."],
    ifCorrect: "Saying it up front is kinder than leaving suddenly later.",
  }),

  // ── Hearing it ────────────────────────────────────────────────────────────
  fillSeed({
    id: "p-l7-listen-which-close",
    operation: "retrieve",
    difficulty: "easy",
    surface: "listen",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-merci-beaucoup"],
    audio: "Merci beaucoup, au revoir !",
    prompt: "Listen. How warmly did they thank you?",
    correct: { id: "o-warm", text: "Thank you very much, goodbye." },
    traps: [
      { id: "o-plain", text: "Thanks, goodbye.", why: "That is merci on its own. You heard the longer, warmer one.", tag: "meaning_shift" },
      { id: "o-evening", text: "Goodbye, have a good evening.", why: "No evening was mentioned. The second half was the goodbye itself.", tag: "meaning_shift" },
    ],
    short: "Merci beaucoup, au revoir !",
    explanation: "Beaucoup is the difference between polite and grateful.",
  }),
  fillSeed({
    id: "p-l7-listen-the-evening-wish",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    audio: "Au revoir, bonne soirée !",
    prompt: "Listen. What did they wish you?",
    correct: { id: "o-evening", text: "A good evening." },
    traps: [
      { id: "o-day", text: "A good day.", why: "That is bonne journée. You heard the one for the hours after dark.", tag: "meaning_shift" },
      { id: "o-nothing", text: "Nothing, they just said goodbye.", why: "There was a second half, and it was a wish.", tag: "meaning_shift" },
    ],
    short: "Au revoir, bonne soirée !",
    explanation: "Bonne soirée is for an evening they have not had yet.",
  }),
  weaveSeed({
    id: "p-l7-dictation-must-go",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole", "chunk-je-dois-partir"],
    audio: "Désolé, je dois partir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Désolé, je dois partir."],
    alternatives: ["Desole, je dois partir.", "Désolée, je dois partir."],
    ifCorrect: "Heard and written. Désolé carries the accents you can hear.",
  }),
  weaveSeed({
    id: "p-l7-dictation-warm-close",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    targets: ["chunk-merci-beaucoup", "chunk-bonne-soiree"],
    audio: "Merci beaucoup, bonne soirée !",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci beaucoup, bonne soirée !"],
    alternatives: ["Merci beaucoup, bonne soirée.", "Merci beaucoup bonne soiree"],
    ifCorrect: "Two chunks, one closing.",
  }),
  weaveSeed({
    id: "p-l7-dictation-going-to-the-cafe",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    audio: "Je vais au café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais au café."],
    alternatives: ["Je vais au cafe.", "Je vais au café"],
    ifCorrect: "Au café, heard as one piece and written as one.",
  }),
  // ── Being asked, and answering ────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-yes-to-the-cafe",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Answer them, and say where.",
    context: "They saw you pick up your keys. « Vous partez ? »",
    answers: ["Oui, je vais au café."],
    alternatives: ["Oui, je vais au cafe.", "Oui je vais au café"],
    ifCorrect: "Answer first, place second. Reversed it sounds like an excuse.",
  }),
  weaveSeed({
    id: "p-l7-apply-yes-must-go",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-je-dois-partir"],
    targets: ["chunk-oui", "chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Confirm it, and say it is not your choice.",
    context: "They had hoped you would stay for the second half. « Vous partez ? »",
    answers: ["Oui, je dois partir."],
    alternatives: ["Oui, je dois partir", "Oui je dois partir."],
    ifCorrect: "Dois is what keeps a yes from sounding like a preference.",
  }),
  weaveSeed({
    id: "p-l7-repair-decline-the-second-one",
    operation: "repair", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci"],
    weaveType: "mid",
    prompt: "Turn it down, and say where you are going instead.",
    context: "The pot is out again and it is nearly eleven. « Un café ? »",
    answers: ["Non merci, je vais à la maison."],
    alternatives: ["Non merci. Je vais à la maison.", "Non, merci, je vais à la maison."],
    ifCorrect: "The destination is the reason, and a reason is what makes a refusal kind.",
  }),

  // ── Explaining the leaving ────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-hungry-going-home",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Say how you are, then what you are going to do about it.",
    context: "Nobody has eaten and the meeting has drifted past two.",
    answers: ["J'ai faim. Je vais à la maison."],
    alternatives: ["J ai faim. Je vais à la maison.", "J'ai faim, je vais à la maison."],
    ifCorrect: "The state explains the move. That is why it comes first.",
  }),
  weaveSeed({
    id: "p-l7-apply-question-then-go-home",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Get the last thing in, then say you are off.",
    context: "You have one thing left to ask and the room is emptying around you.",
    answers: ["J'ai une question. Je vais à la maison."],
    alternatives: ["J ai une question. Je vais à la maison."],
    ifCorrect: "Asking before you announce the leaving is what stops it being a parting shot.",
  }),
  weaveSeed({
    id: "p-l7-apply-not-here-so-going",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Say it is the wrong place, then say what you are doing.",
    context: "You have found the room, and the meeting you wanted is clearly not in it.",
    answers: ["Ce n'est pas ici. Je vais à la maison."],
    alternatives: ["Ce n est pas ici. Je vais à la maison."],
    ifCorrect: "Naming the problem before the exit keeps it from looking like sulking.",
  }),
  weaveSeed({
    id: "p-l7-apply-didnt-follow-so-going",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole"],
    weaveType: "open",
    prompt: "Apologise, say it went past you, and say you cannot stay for the rest.",
    context: "The explanation was long, it lost you early, and you are out of time.",
    answers: ["Désolé, je ne comprends pas. Je dois partir."],
    alternatives: ["Desole, je ne comprends pas. Je dois partir."],
    ifCorrect: "Three short moves. Each one is honest and none of them is an argument.",
  }),

  // ── The counter, on your way out ──────────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-order-and-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Order, and thank them properly when it lands.",
    context: "One before the train. They are quick about it and they smile.",
    answers: ["Je voudrais un café. Merci beaucoup !"],
    alternatives: ["Je voudrais un café. Merci beaucoup.", "Je voudrais un café, merci beaucoup !"],
    ifCorrect: "Beaucoup is what makes a transaction feel like an exchange.",
  }),
  weaveSeed({
    id: "p-l7-apply-tea-then-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Order the other drink, and warn them you cannot wait long.",
    context: "You have eight minutes and there is one person ahead of you.",
    answers: ["Je voudrais un thé. Je dois partir."],
    alternatives: ["Je voudrais un thé, je dois partir."],
    ifCorrect: "Saying it up front turns a rush into a courtesy.",
  }),
  weaveSeed({
    id: "p-l7-apply-excuse-then-going",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Reach them first, then say where you are going.",
    context: "They are facing away and you would rather they knew you had left.",
    answers: ["Excusez-moi, je vais au café."],
    alternatives: ["Excusez-moi. Je vais au café.", "Excusez-moi, je vais au cafe."],
    ifCorrect: "Getting their attention is what turns leaving into telling them you left.",
  }),

  // ── Closing, with the right warmth ────────────────────────────────────────
  weaveSeed({
    id: "p-l7-produce-thanks-then-home",
    operation: "produce", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "mid",
    prompt: "Thank them warmly, then say where you are going.",
    context: "They fixed the thing you could not, and it is late.",
    answers: ["Merci beaucoup. Je vais à la maison."],
    alternatives: ["Merci beaucoup, je vais à la maison."],
    ifCorrect: "Thanks first. The leaving reads as a consequence rather than an escape.",
  }),
  weaveSeed({
    id: "p-l7-apply-home-and-evening",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Say where you are going, and leave them the evening.",
    context: "You are the first to go and the others are settling in for a while.",
    answers: ["Je vais à la maison. Bonne soirée !"],
    alternatives: ["Je vais à la maison. Bonne soirée.", "Je vais à la maison, bonne soirée !"],
    ifCorrect: "Bonne soirée is generous precisely because you are the one leaving.",
  }),
  weaveSeed({
    id: "p-l7-apply-sorry-go-evening",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Apologise, say you have to go, and still wish them well.",
    context: "It is somebody's evening and you are leaving in the middle of it.",
    answers: ["Désolé, je dois partir. Bonne soirée !"],
    alternatives: ["Desole, je dois partir. Bonne soirée !", "Désolé, je dois partir. Bonne soirée."],
    ifCorrect: "The wish at the end is what stops the apology sounding like an excuse.",
  }),
  weaveSeed({
    id: "p-l7-retrieve-just-goodbye",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Close it, plainly.",
    context: "A short exchange, nothing owed either way, and you are done.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci, au revoir !", "Merci au revoir"],
    ifCorrect: "Not every goodbye needs beaucoup. This one does not.",
  }),

  // ── Reconstructing whole moments ──────────────────────────────────────────
  buildSeed({
    id: "p-l7-build-sorry-go-evening",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-desole", "chunk-je-dois-partir", "chunk-bonne-soiree"],
    targets: ["chunk-desole", "chunk-bonne-soiree"],
    prompt: "Put the whole early exit together.",
    context: "Leaving somebody's evening before it has really started.",
    tiles: [
      { itemId: "chunk-desole", text: "Désolé,", answerIndex: 0 },
      { itemId: "chunk-je-dois-partir", text: "je dois partir.", answerIndex: 1 },
      { itemId: "chunk-bonne-soiree", text: "Bonne soirée !", answerIndex: 2 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Désolé, je dois partir. Bonne soirée !",
    ifCorrect: "Apology, reason, wish. Nobody is offended by that order.",
    ifWrong: "Right pieces. The apology opens it and the wish closes it.",
  }),
  buildSeed({
    id: "p-l7-build-hungry-then-cafe",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    prompt: "Assemble the reason and the move.",
    context: "Two o'clock, nobody has stopped, and you have had enough.",
    tiles: [
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-au-cafe", text: "au café.", answerIndex: 2 },
      { itemId: "chunk-a-la-maison", text: "à la maison." },
    ],
    target: "J'ai faim. Je vais au café.",
    ifCorrect: "The state, then the destination it explains.",
    ifWrong: "Right pieces. Say how you are before you say where you are going.",
  }),
  buildSeed({
    id: "p-l7-build-order-and-thanks",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    prompt: "Build the whole counter exchange.",
    context: "One coffee, quickly, and they were kind about it.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-un-cafe", text: "un café.", answerIndex: 1 },
      { itemId: "chunk-merci-beaucoup", text: "Merci beaucoup !", answerIndex: 2 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Je voudrais un café. Merci beaucoup !",
    ifCorrect: "The request, then the thanks it earned.",
    ifWrong: "Right pieces. Thanks come after the thing you asked for.",
  }),

  // ── Hearing the difference ────────────────────────────────────────────────
  fillSeed({
    id: "p-l7-listen-which-destination",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe", "chunk-a-la-gare"],
    targets: ["chunk-a-la-gare"],
    audio: "Je vais à la gare.",
    prompt: "Listen. Where are they going?",
    correct: { id: "o-gare", text: "To the station." },
    traps: [
      { id: "o-cafe", text: "To the café.", why: "That would be au café. You heard the à la shape.", tag: "meaning_shift" },
      { id: "o-home", text: "Home.", why: "Home is à la maison. Same shape, different place.", tag: "meaning_shift" },
    ],
    short: "Je vais à la gare.",
    explanation: "Two of these take à la. The word after it is what tells them apart.",
  }),
  fillSeed({
    id: "p-l7-listen-leaving-or-staying",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-dois-partir", "chunk-je-suis-ici"],
    targets: ["chunk-je-dois-partir"],
    audio: "Désolé, je dois partir.",
    prompt: "Listen. What are they telling you?",
    correct: { id: "o-going", text: "They are sorry, but they have to go." },
    traps: [
      { id: "o-here", text: "They are sorry they are late.", why: "Nothing here is about arriving. Partir is the leaving.", tag: "meaning_shift" },
      { id: "o-refuse", text: "They are turning something down.", why: "That would be non merci. This one gives a reason for leaving.", tag: "meaning_shift" },
    ],
    short: "Désolé, je dois partir.",
    explanation: "Désolé softens it; je dois partir is the part that actually leaves.",
  }),
  weaveSeed({
    id: "p-l7-dictation-home-and-evening",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    audio: "Je vais à la maison. Bonne soirée !",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison. Bonne soirée !"],
    alternatives: ["Je vais à la maison. Bonne soirée.", "Je vais a la maison. Bonne soiree !"],
    ifCorrect: "Two sentences, one departure.",
  }),
  weaveSeed({
    id: "p-l7-dictation-thanks-and-goodbye",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Merci beaucoup, au revoir !",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci beaucoup, au revoir !"],
    alternatives: ["Merci beaucoup, au revoir.", "Merci beaucoup au revoir"],
    ifCorrect: "The commonest close on the whole path.",
  }),
  // ── Choosing the right warmth ─────────────────────────────────────────────
  fillSeed({
    id: "p-l7-choice-plain-or-warm-thanks",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-merci", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    prompt: "They went out of their way for you. Which thanks fits?",
    correct: { id: "o-warm", text: "Merci beaucoup." },
    traps: [
      { id: "o-plain", text: "Merci.", why: "Merci is for a small thing handed over. This was more than that.", tag: "wrong_register" },
      { id: "o-no", text: "Non merci.", why: "That refuses something. Nothing is being offered here.", tag: "meaning_shift" },
    ],
    short: "Merci beaucoup.",
    explanation: "The size of the thanks should match the size of the favour.",
  }),
  fillSeed({
    id: "p-l7-choice-goodbye-or-evening",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    prompt: "It is eight in the evening and they are staying on. What do you add after au revoir?",
    correct: { id: "o-soiree", text: "Bonne soirée !" },
    traps: [
      { id: "o-merci", text: "Merci beaucoup !", why: "Thanks close a favour. This closes an evening.", tag: "meaning_shift" },
      { id: "o-nothing", text: "Nothing, au revoir is enough.", why: "It is not wrong, but it leaves the warmth on the table.", tag: "wrong_register" },
    ],
    short: "Bonne soirée !",
    explanation: "Au revoir ends the exchange; bonne soirée hands them the rest of the evening.",
  }),
  fillSeed({
    id: "p-l7-repair-going-or-being",
    operation: "repair", difficulty: "easy", surface: "fill", lesson: L,
    required: ["chunk-je-vais", "chunk-je-suis"],
    targets: ["chunk-je-vais"],
    prompt: "You are not describing where you ARE. Which engine moves you?",
    before: "Je ",
    after: " au café.",
    correct: { id: "o-vais", text: "vais" },
    traps: [
      { id: "o-suis", text: "suis", why: "Je suis places you somewhere. Je vais takes you there.", tag: "wrong_item" },
      { id: "o-ai", text: "ai", why: "J'ai is for what you have, not where you are heading.", tag: "wrong_item" },
    ],
    short: "vais",
    explanation: "Je vais au café. The engine is the part that moves.",
  }),

  // ── Answering someone else's goodbye ──────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-answer-their-goodbye",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Answer them, and give the evening back.",
    context: "They get there first, on their way past: « Au revoir, bonne soirée ! »",
    answers: ["Au revoir, bonne soirée !"],
    alternatives: ["Au revoir, bonne soirée.", "Merci, au revoir !"],
    ifCorrect: "Returning the wish is the whole convention. Silence reads as a snub.",
  }),
  weaveSeed({
    id: "p-l7-apply-thanks-back",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Thank them for it, then close.",
    context: "They held the door and pointed you the right way. « Au revoir ! »",
    answers: ["Merci beaucoup, au revoir !"],
    alternatives: ["Merci beaucoup, au revoir.", "Merci beaucoup ! Au revoir !"],
    ifCorrect: "The thanks is what makes it an exchange rather than two people talking past each other.",
  }),

  // ── Leaving when the thing has not worked ─────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-wrong-room-so-going",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-desole", "chunk-je-dois-partir"],
    targets: ["chunk-desole"],
    weaveType: "open",
    prompt: "Say it is the wrong place, apologise, and go.",
    context: "You have walked into the wrong meeting and eight people are looking at you.",
    answers: ["Désolé, ce n'est pas ici. Je dois partir."],
    alternatives: ["Desole, ce n est pas ici. Je dois partir."],
    ifCorrect: "Apologising for the interruption is what buys you the exit.",
  }),
  weaveSeed({
    id: "p-l7-repair-ask-again-then-go",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-vous-pouvez-repeter", "chunk-merci-beaucoup", "chunk-je-dois-partir"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Ask once more, thank them, and say you are out of time.",
    context: "You still have not caught it and there are two minutes left.",
    answers: ["Vous pouvez répéter ? Merci beaucoup. Je dois partir."],
    alternatives: ["Vous pouvez répéter ? Merci beaucoup, je dois partir."],
    ifCorrect: "Thanking between the ask and the exit is what keeps it from being abrupt.",
  }),
  weaveSeed({
    id: "p-l7-apply-not-me-going-home",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-suis-pas", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Tell them you are not in there, then say where you are going.",
    context:
      "They are calling for you from the meeting room, and you are already at the front door.",
    answers: ["Je ne suis pas ici. Je vais à la maison."],
    alternatives: ["Je ne suis pas ici, je vais à la maison."],
    ifCorrect: "Je ne suis pas ici is about the PLACE they think you are in, not about who you are.",
  }),

  // ── Announcing, once you are already at the door ──────────────────────────
  weaveSeed({
    id: "p-l7-produce-just-going-home",
    operation: "produce", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "mid",
    prompt: "Say where you are going.",
    context: "Somebody looks up as you reach for your coat.",
    answers: ["Je vais à la maison."],
    alternatives: ["Je vais à la maison", "Je vais a la maison."],
    ifCorrect: "Short, and it answers the question they were about to ask.",
  }),
  weaveSeed({
    id: "p-l7-apply-greet-and-going-home",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Greet them, then say where you are going.",
    context: "You meet the concierge on the stairs and neither of you has spoken yet.",
    answers: ["Bonjour, je vais à la maison."],
    alternatives: ["Bonjour. Je vais à la maison.", "Bonjour je vais à la maison"],
    ifCorrect: "In France the greeting comes first even when you are on your way out.",
  }),
  weaveSeed({
    id: "p-l7-apply-here-then-going",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Let them know you came, and where you will be.",
    context: "You promised to look in. They are on a call and cannot talk.",
    answers: ["Je suis ici. Je vais au café."],
    alternatives: ["Je suis ici, je vais au café."],
    ifCorrect: "Two facts, no fuss: you came, and here is where to find you.",
  }),

  // ── Reconstruction ────────────────────────────────────────────────────────
  buildSeed({
    id: "p-l7-build-answer-and-destination",
    operation: "retrieve", difficulty: "easy", surface: "build", lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui"],
    prompt: "Assemble the answer.",
    context: "« Vous partez ? » and you are.",
    tiles: [
      { itemId: "chunk-oui", text: "Oui,", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-non-merci", text: "non merci," },
    ],
    target: "Oui, je vais à la maison.",
    ifCorrect: "The yes goes first. Everything after it is the detail.",
    ifWrong: "Right pieces. Answer before you explain.",
  }),
  buildSeed({
    id: "p-l7-build-wrong-room-exit",
    operation: "repair", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-desole", "chunk-ce-n-est-pas", "chunk-je-dois-partir"],
    targets: ["chunk-desole", "chunk-je-dois-partir"],
    prompt: "Put the apology, the correction and the exit in order.",
    context: "Wrong room, eight faces, and no reason to stay.",
    tiles: [
      { itemId: "chunk-desole", text: "Désolé,", answerIndex: 0 },
      { itemId: "chunk-ce-n-est-pas", text: "ce n'est pas ici.", answerIndex: 1 },
      { itemId: "chunk-je-dois-partir", text: "Je dois partir.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Désolé, ce n'est pas ici. Je dois partir.",
    ifCorrect: "Apologise, explain, leave. In that order nobody has to ask anything.",
    ifWrong: "Right pieces. The apology comes before the explanation.",
  }),

  // ── Hearing it, under pressure ────────────────────────────────────────────
  fillSeed({
    id: "p-l7-listen-warm-or-plain",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-merci", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    audio: "Merci beaucoup !",
    prompt: "Listen. How much did that thanks carry?",
    correct: { id: "o-lots", text: "A lot. They really meant it." },
    traps: [
      { id: "o-little", text: "The ordinary amount.", why: "That would be merci on its own. You heard the longer one.", tag: "wrong_register" },
      { id: "o-refuse", text: "They were turning something down.", why: "Non merci refuses. This one only thanks.", tag: "meaning_shift" },
    ],
    short: "Merci beaucoup !",
    explanation: "Beaucoup is the whole difference, and it is audible.",
  }),
  weaveSeed({
    id: "p-l7-dictation-sorry-wrong-place",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-desole", "chunk-ce-n-est-pas"],
    targets: ["chunk-desole"],
    audio: "Désolé, ce n'est pas ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Désolé, ce n'est pas ici."],
    alternatives: ["Desole, ce n'est pas ici.", "Désolé, ce n est pas ici."],
    ifCorrect: "An apology and a correction, written the way they are said.",
  }),
  weaveSeed({
    id: "p-l7-dictation-yes-going-home",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-oui"],
    audio: "Oui, je vais à la maison.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Oui, je vais à la maison."],
    alternatives: ["Oui je vais à la maison", "Oui, je vais a la maison."],
    ifCorrect: "An answer and its reason, in one breath.",
  }),
  // ── Interrupting, in order to leave ───────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-cut-in-to-leave",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Cut in, and say you have to go.",
    context: "Two people are mid-conversation and neither has noticed you waiting.",
    answers: ["Excusez-moi, je dois partir."],
    alternatives: ["Excusez-moi. Je dois partir.", "Excusez-moi je dois partir"],
    ifCorrect: "Excusez-moi buys the interruption; je dois partir uses it.",
  }),
  weaveSeed({
    id: "p-l7-apply-greet-and-go",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Greet them, and say you cannot stop.",
    context: "You pass someone you know in the corridor and you are already late.",
    answers: ["Bonjour ! Je dois partir."],
    alternatives: ["Bonjour, je dois partir.", "Bonjour. Je dois partir."],
    ifCorrect: "Greeting anyway is what keeps hurrying past from reading as rudeness.",
  }),
  weaveSeed({
    id: "p-l7-apply-sorry-then-question",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-desole", "chunk-j-ai-une-question"],
    targets: ["chunk-desole"],
    weaveType: "open",
    prompt: "Apologise for the interruption, then ask.",
    context: "They are packing up and you have one thing you still need.",
    answers: ["Désolé, j'ai une question."],
    alternatives: ["Desole, j'ai une question.", "Désolé. J'ai une question."],
    ifCorrect: "The apology is what makes a late question welcome instead of tiresome.",
  }),
  weaveSeed({
    id: "p-l7-repair-sorry-didnt-follow",
    operation: "repair", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-desole"],
    targets: ["chunk-desole"],
    weaveType: "mid",
    prompt: "Say it went past you, and soften it.",
    context: "They have explained it twice and you still have not got it.",
    answers: ["Je ne comprends pas. Désolé."],
    alternatives: ["Je ne comprends pas, désolé.", "Je ne comprends pas. Desole."],
    ifCorrect: "Putting désolé second turns an admission into an apology for the trouble.",
  }),

  // ── The whole counter, start to finish ────────────────────────────────────
  weaveSeed({
    id: "p-l7-apply-greet-order-thank",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-voudrais", "chunk-un-cafe", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Open it, order, and thank them when it comes.",
    context: "A quiet counter, nobody waiting behind you, and you have a minute.",
    answers: ["Bonjour. Je voudrais un café. Merci beaucoup !"],
    alternatives: ["Bonjour, je voudrais un café. Merci beaucoup !"],
    ifCorrect: "Three moves and the whole exchange is done, politely, in about four seconds.",
  }),
  weaveSeed({
    id: "p-l7-apply-polite-order-then-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Order the other one, then close when you have it.",
    context: "You are not staying, and there is a queue forming behind you.",
    answers: ["Je voudrais un thé. Merci, au revoir."],
    alternatives: ["Je voudrais un thé. Merci, au revoir !"],
    ifCorrect: "Closing the exchange yourself is what makes leaving quickly polite.",
  }),
  weaveSeed({
    id: "p-l7-apply-excuse-question-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-une-question", "chunk-merci-beaucoup"],
    targets: ["chunk-merci-beaucoup"],
    weaveType: "open",
    prompt: "Reach them, ask, and thank them for the answer.",
    context: "Somebody behind a desk, busy but not unfriendly.",
    answers: ["Excusez-moi, j'ai une question. Merci beaucoup !"],
    alternatives: ["Excusez-moi. J'ai une question. Merci beaucoup !"],
    ifCorrect: "Opening and closing the exchange is what a stranger is owed.",
  }),

  // ── Where you are going, when it is not home ──────────────────────────────
  weaveSeed({
    id: "p-l7-apply-decline-going-to-cafe",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-non-merci"],
    weaveType: "open",
    prompt: "Turn it down, and say where you are going instead.",
    context: "They offer to make you one here, but you had arranged to meet someone out.",
    answers: ["Non merci, je vais au café."],
    alternatives: ["Non merci. Je vais au café.", "Non, merci, je vais au café."],
    ifCorrect: "Naming somewhere else is a kinder refusal than naming nothing.",
  }),
  weaveSeed({
    id: "p-l7-apply-cafe-then-close",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe", "chunk-au-revoir"],
    targets: ["chunk-au-cafe"],
    weaveType: "open",
    prompt: "Say where you are going, then close.",
    context: "You are the first to leave and the others are still working.",
    answers: ["Je vais au café. Au revoir !"],
    alternatives: ["Je vais au café. Au revoir.", "Je vais au café, au revoir !"],
    ifCorrect: "Saying where you will be is what turns leaving into an arrangement.",
  }),
  weaveSeed({
    id: "p-l7-apply-yes-cafe-and-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-oui", "chunk-je-vais", "chunk-au-cafe", "chunk-au-revoir"],
    targets: ["chunk-oui"],
    weaveType: "open",
    prompt: "Confirm it, say where, and close.",
    context: "They have half stood up to see you off. « Vous partez ? »",
    answers: ["Oui, je vais au café. Au revoir !"],
    alternatives: ["Oui, je vais au café. Au revoir."],
    ifCorrect: "Three beats, and none of them leaves the other person guessing.",
  }),
  weaveSeed({
    id: "p-l7-apply-excuse-going-home",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Reach them first, then say where you are going.",
    context: "The room is loud and nobody has looked up in ten minutes.",
    answers: ["Excusez-moi, je vais à la maison."],
    alternatives: ["Excusez-moi. Je vais à la maison."],
    ifCorrect: "Telling them beats slipping out and being wondered about.",
  }),
  weaveSeed({
    id: "p-l7-apply-hungry-must-go",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    weaveType: "open",
    prompt: "Give the reason, then say you are going.",
    context: "It is three o'clock, the meeting has no end in sight, and you have not eaten.",
    answers: ["J'ai faim. Je dois partir."],
    alternatives: ["J ai faim. Je dois partir.", "J'ai faim, je dois partir."],
    ifCorrect: "A reason first makes dois sound like a fact rather than an excuse.",
  }),
  weaveSeed({
    id: "p-l7-retrieve-minimal-exit",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-desole", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Apologise and close, in as little as possible.",
    context: "You interrupted, it was the wrong room, and there is nothing to add.",
    answers: ["Désolé. Au revoir."],
    alternatives: ["Desole. Au revoir.", "Désolé, au revoir."],
    ifCorrect: "Sometimes the whole repair is two words and a door.",
  }),
  weaveSeed({
    id: "p-l7-apply-cafe-and-evening",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe", "chunk-bonne-soiree"],
    targets: ["chunk-bonne-soiree"],
    weaveType: "open",
    prompt: "Say where you are going, and leave them the evening.",
    context: "Seven o'clock. They are staying on and you are meeting someone.",
    answers: ["Je vais au café. Bonne soirée !"],
    alternatives: ["Je vais au café. Bonne soirée.", "Je vais au café, bonne soirée !"],
    ifCorrect: "The wish costs nothing and is the difference between leaving and disappearing.",
  }),

  // ── Choosing the right word ───────────────────────────────────────────────
  fillSeed({
    id: "p-l7-choice-sorry-or-excuse",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-desole", "chunk-excusez-moi", "chunk-je-dois-partir"],
    targets: ["chunk-desole"],
    prompt: "You are leaving something unfinished. Which word carries the regret?",
    correct: { id: "o-des", text: "Désolé, je dois partir." },
    traps: [
      { id: "o-exc", text: "Excusez-moi, je dois partir.", why: "Excusez-moi gets attention. It does not say you mind leaving.", tag: "wrong_register" },
      { id: "o-mer", text: "Merci, je dois partir.", why: "Thanks close a favour. Nothing here has been done for you.", tag: "meaning_shift" },
    ],
    short: "Désolé, je dois partir.",
    explanation: "Excusez-moi opens a channel; désolé apologises for what you are about to do.",
  }),
  fillSeed({
    id: "p-l7-choice-refuse-warmly",
    operation: "repair", difficulty: "easy", surface: "choice", lesson: L,
    required: ["chunk-non", "chunk-non-merci"],
    targets: ["chunk-non-merci"],
    prompt: "They offer you a coffee and you do not want one. What do you say?",
    correct: { id: "o-nm", text: "Non merci." },
    traps: [
      { id: "o-n", text: "Non.", why: "Bare non is an answer to a question, not a refusal of an offer. It lands hard.", tag: "wrong_register" },
      { id: "o-m", text: "Merci.", why: "On its own that reads as yes please, which is the opposite.", tag: "meaning_shift" },
    ],
    short: "Non merci.",
    explanation: "Merci is what turns a refusal into a polite one. Dropping it changes the tone entirely.",
  }),
  fillSeed({
    id: "p-l7-repair-home-shape",
    operation: "repair", difficulty: "easy", surface: "fill", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-cafe"],
    targets: ["chunk-a-la-maison"],
    prompt: "Home does not take the same shape as café. Which one?",
    before: "Je vais ",
    after: " maison.",
    correct: { id: "o-ala", text: "à la" },
    traps: [
      { id: "o-au", text: "au", why: "Au belongs to café and travail. Maison carries à la.", tag: "wrong_item" },
      { id: "o-a", text: "à", why: "The shape is à la here, not à on its own.", tag: "missing_word" },
    ],
    short: "à la",
    explanation: "Je vais à la maison. The shape is attached to the place, not chosen by you.",
  }),

  // ── Hearing the difference ────────────────────────────────────────────────
  fillSeed({
    id: "p-l7-listen-going-or-leaving",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-dois-partir", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-dois-partir"],
    audio: "Je dois partir.",
    prompt: "Listen. Are they naming a destination, or a necessity?",
    correct: { id: "o-must", text: "A necessity. They have to go." },
    traps: [
      { id: "o-dest", text: "A destination. They are going home.", why: "That would be je vais à la maison. Nothing here names a place.", tag: "meaning_shift" },
      { id: "o-refuse", text: "A refusal.", why: "Non merci refuses. This one explains a departure.", tag: "meaning_shift" },
    ],
    short: "Je dois partir.",
    explanation: "Je vais names where. Je dois partir names why.",
  }),
  fillSeed({
    id: "p-l7-listen-refusal-or-thanks",
    operation: "repair", difficulty: "easy", surface: "listen", lesson: L,
    required: ["chunk-non-merci", "chunk-merci"],
    targets: ["chunk-non-merci"],
    audio: "Non merci.",
    prompt: "Listen. Are they taking it or turning it down?",
    correct: { id: "o-no", text: "Turning it down, politely." },
    traps: [
      { id: "o-yes", text: "Taking it, gratefully.", why: "That is merci on its own. The non in front reverses it.", tag: "meaning_shift" },
      { id: "o-warm", text: "Thanking you very much.", why: "That would be merci beaucoup. This one begins with a refusal.", tag: "meaning_shift" },
    ],
    short: "Non merci.",
    explanation: "One small word ahead of merci flips the whole answer.",
  }),

  // ── Writing what you heard ────────────────────────────────────────────────
  weaveSeed({
    id: "p-l7-dictation-decline-and-home",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-non-merci"],
    audio: "Non merci, je vais à la maison.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Non merci, je vais à la maison."],
    alternatives: ["Non merci. Je vais à la maison.", "Non merci, je vais a la maison."],
    ifCorrect: "A refusal and its reason, in one line.",
  }),
  weaveSeed({
    id: "p-l7-dictation-cut-in-to-leave",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-dois-partir"],
    targets: ["chunk-je-dois-partir"],
    audio: "Excusez-moi, je dois partir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Excusez-moi, je dois partir."],
    alternatives: ["Excusez-moi. Je dois partir.", "Excusez moi, je dois partir."],
    ifCorrect: "The hyphen in excusez-moi is easy to lose and worth keeping.",
  }),
  weaveSeed({
    id: "p-l7-dictation-hungry-cafe",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    audio: "J'ai faim. Je vais au café.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["J'ai faim. Je vais au café."],
    alternatives: ["J ai faim. Je vais au café.", "J'ai faim. Je vais au cafe."],
    ifCorrect: "Two sentences, and the second one follows from the first.",
  }),
  weaveSeed({
    id: "p-l7-dictation-plain-close",
    operation: "produce", difficulty: "easy", surface: "dictation", lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    audio: "Merci, au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci, au revoir."],
    alternatives: ["Merci, au revoir !", "Merci au revoir"],
    ifCorrect: "The plainest close on the path, and the one you will hear most.",
  }),

  // ── Reconstruction ────────────────────────────────────────────────────────
  buildSeed({
    id: "p-l7-build-arrive-and-cafe",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-au-cafe"],
    prompt: "Put the whole visit together.",
    context: "You looked in as promised, they are busy, and you will be next door.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis-ici", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 2 },
      { itemId: "chunk-au-cafe", text: "au café.", answerIndex: 3 },
      { itemId: "chunk-non-merci", text: "Non merci." },
    ],
    target: "Bonjour. Je suis ici. Je vais au café.",
    ifCorrect: "Greet, announce, and say where you will be. Nothing left hanging.",
    ifWrong: "Right pieces. The greeting opens it and the destination closes it.",
  }),
  buildSeed({
    id: "p-l7-build-cut-in-and-leave",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-dois-partir", "chunk-au-revoir"],
    targets: ["chunk-je-dois-partir", "chunk-au-revoir"],
    prompt: "Assemble the interruption and the exit.",
    context: "Nobody has looked up, and you cannot wait any longer.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-je-dois-partir", text: "je dois partir.", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 2 },
      { itemId: "chunk-merci-beaucoup", text: "Merci beaucoup." },
    ],
    target: "Excusez-moi, je dois partir. Au revoir.",
    ifCorrect: "Attention, reason, close. Three beats and you are out.",
    ifWrong: "Right pieces. Get their attention before you announce anything.",
  }),
  buildSeed({
    id: "p-l7-build-decline-and-cafe",
    operation: "repair", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-non-merci"],
    prompt: "Build the refusal with its reason.",
    context: "They offer to make one here. You are meeting someone out.",
    tiles: [
      { itemId: "chunk-non-merci", text: "Non merci,", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "je vais", answerIndex: 1 },
      { itemId: "chunk-au-cafe", text: "au café.", answerIndex: 2 },
      { itemId: "chunk-a-la-maison", text: "à la maison." },
    ],
    target: "Non merci, je vais au café.",
    ifCorrect: "The refusal first, the reason second. That order is what softens it.",
    ifWrong: "Right pieces. Say no before you explain.",
  }),
  buildSeed({
    id: "p-l7-build-sorry-not-followed",
    operation: "repair", difficulty: "easy", surface: "build", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-desole"],
    targets: ["chunk-desole"],
    prompt: "Assemble the admission.",
    context: "Second explanation, still lost, and they are waiting for a reaction.",
    tiles: [
      { itemId: "chunk-je-ne-comprends-pas", text: "Je ne comprends pas.", answerIndex: 0 },
      { itemId: "chunk-desole", text: "Désolé.", answerIndex: 1 },
      { itemId: "chunk-merci", text: "Merci." },
    ],
    target: "Je ne comprends pas. Désolé.",
    ifCorrect: "The admission, then the apology for it. That order is the honest one.",
    ifWrong: "Right pieces. Say what happened before you apologise for it.",
  }),
];
