/**
 * L8 practice seeds — the three ways to talk about a place.
 *
 * This is the densest repair territory on the path. `C'est ici.` states,
 * `C'est où ?` asks where, and `Est-ce que c'est ici ?` checks whether — three
 * sentences built from nearly the same words, and telling them apart is the
 * lesson. Two contrast seeds carry `repairsTag` so a miss on any of them can
 * pull the other into the same session.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-008";

export const L8_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l8-retrieve-c-est-ou",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "mid",
    prompt: "Where is it?",
    answers: ["C'est où ?"],
    alternatives: ["C'est où?", "C'est où"],
    ifCorrect: "Two words that open almost any building.",
  }),
  weaveSeed({
    id: "p-l8-retrieve-c-est-ici",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "mid",
    prompt: "It's here.",
    answers: ["C'est ici."],
    alternatives: ["C'est ici"],
    ifCorrect: "The same small words, pointing the other way.",
  }),
  fillSeed({
    id: "p-l8-repair-statement-or-question",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-c-est-ou", "chunk-c-est"],
    targets: ["chunk-c-est-ou"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "You cannot see the room and you need someone to tell you. What do you say?",
    correct: { id: "o-cest-ou", text: "C'est où ?" },
    traps: [
      {
        id: "o-cest-ici-ask",
        text: "C'est ici.",
        why: "That ANSWERS the question. You are the one who does not know.",
        tag: "meaning_shift",
      },
      {
        id: "o-ce-nest-pas-ask",
        text: "Ce n'est pas ici.",
        why: "That says where it is not, which leaves you exactly as lost.",
        tag: "meaning_shift",
      },
    ],
    short: "C'est où ?",
    explanation: "Où turns the statement into a question. Everything else stays put.",
  }),
  fillSeed({
    id: "p-l8-repair-which-question",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est-ou"],
    targets: ["chunk-est-ce-que"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "You think this is the room, but you would rather check than walk in on strangers.",
    correct: { id: "o-est-ce-que", text: "Est-ce que c'est ici ?" },
    traps: [
      {
        id: "o-cest-ou-check",
        text: "C'est où ?",
        why: "That asks WHERE, as if you had no idea. You have a guess and want it confirmed.",
        tag: "meaning_shift",
      },
      {
        id: "o-cest-ici-check",
        text: "C'est ici.",
        why: "That tells them it is here. You are asking, not announcing.",
        tag: "meaning_shift",
      },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "Est-ce que turns a statement into a yes/no question without changing a word of it.",
  }),
  weaveSeed({
    id: "p-l8-produce-check-the-door",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-est-ce-que"],
    targets: ["chunk-est-ce-que"],
    weaveType: "context",
    prompt: "Check whether this is the place.",
    context: "You are outside a door you think is right, and you can hear people inside.",
    answers: ["Est-ce que c'est ici ?"],
    alternatives: ["Est-ce que c'est ici?"],
    ifCorrect: "You asked it back instead of guessing. That is what the form is for.",
  }),
  weaveSeed({
    id: "p-l8-apply-answer-the-asker",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-oui", "chunk-c-est"],
    targets: ["chunk-oui", "chunk-c-est"],
    weaveType: "context",
    prompt: "Answer them, then confirm the place.",
    context: "They stop beside you and ask « C'est où ? ». It is this room.",
    answers: ["Oui, c'est ici."],
    alternatives: ["Oui. C'est ici."],
    ifCorrect: "You were asked in French and you answered in French. Both sides are yours now.",
  }),
  weaveSeed({
    id: "p-l8-apply-wrong-door",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "context",
    prompt: "Tell them it isn't this one.",
    context: "Someone stops at your door and asks « C'est où ? ». The room they want is not this one.",
    answers: ["Ce n'est pas ici."],
    alternatives: ["Ce n'est pas ici"],
    ifCorrect: "Clear without being unhelpful. They will keep looking.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-politely",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "open",
    prompt: "Reach them, then ask.",
    context: "A corridor you do not know. Someone is walking past with their arms full.",
    answers: ["Excusez-moi, c'est où ?"],
    alternatives: ["Excusez-moi. C'est où ?", "Excusez-moi, c'est où?"],
    ifCorrect: "Attention first, then the question. The order never changes.",
    ifWrong: "Your meaning lands. Reach them before you ask.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "open",
    prompt: "Ask.",
    context: "First time in the building. The room you need is not where you were told it would be.",
    answers: ["C'est où ?"],
    alternatives: ["C'est où?"],
    ifCorrect: "Nothing was handed to you and it came back anyway.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l8-build-reach-and-ask",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    prompt: "Build the question.",
    context: "A corridor you do not know, and someone walking past with their arms full.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-c-est-ou", text: "c'est où ?", answerIndex: 1 },
      { itemId: "chunk-c-est", text: "c'est ici." },
    ],
    target: "Excusez-moi, c'est où ?",
    ifCorrect: "Attention first, question second. The order never changes.",
  }),
  fillSeed({
    id: "p-l8-listen-asking-or-telling",
    operation: "repair",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-c-est-ou", "chunk-c-est"],
    targets: ["chunk-c-est-ou"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    audio: "C'est où ?",
    prompt: "Listen. Are they asking or telling?",
    correct: { id: "o-asking", text: "Where is it?" },
    traps: [
      { id: "o-telling", text: "It's here.", why: "That answers. Listen for the rise at the end.", tag: "meaning_shift" },
      { id: "o-checking", text: "Is it here?", why: "Close, but that one checks a guess. This asks with no guess at all.", tag: "meaning_shift" },
    ],
    short: "C'est où ?",
    explanation: "Où is the whole difference between asking and answering.",
  }),
  fillSeed({
    id: "p-l8-listen-which-question",
    operation: "repair",
    difficulty: "hard",
    surface: "listen",
    lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est-ou"],
    targets: ["chunk-est-ce-que"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    audio: "Est-ce que c'est ici ?",
    prompt: "Listen. What kind of question is this?",
    correct: { id: "o-yesno", text: "Is it here?" },
    traps: [
      { id: "o-where-q", text: "Where is it?", why: "That asks for a place. This one only wants yes or no.", tag: "meaning_shift" },
      { id: "o-negative-q", text: "It's not here.", why: "That is a statement, and the opposite one at that.", tag: "meaning_shift" },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "Est-ce que turns a statement into a yes/no question without moving a word.",
  }),
  weaveSeed({
    id: "p-l8-dictation-where",
    operation: "produce",
    difficulty: "easy",
    surface: "dictation",
    lesson: L,
    required: ["chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou", "adverb-ou-where"],
    audio: "C'est où ?",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["C'est où ?"],
    alternatives: ["C'est où?", "c'est où ?", "C'est où"],
    ifCorrect: "Short, and every character of it matters.",
  }),
  weaveSeed({
    id: "p-l8-dictation-its-here",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    audio: "C'est ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["C'est ici."],
    alternatives: ["c'est ici.", "C'est ici"],
    ifCorrect: "The same two small words, pointing the other way.",
  }),
  weaveSeed({
    id: "p-l8-dictation-is-it-here",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-est-ce-que"],
    audio: "Est-ce que c'est ici ?",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Est-ce que c'est ici ?"],
    alternatives: ["Est-ce que c'est ici?", "est-ce que c'est ici ?"],
    ifCorrect: "Three hyphens and an apostrophe. Hearing it is one thing; writing it is another.",
    ifWrong: "The opening runs together as one sound, but it is written in three pieces.",
  }),
  weaveSeed({
    id: "p-l8-apply-greet-then-ask-where",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-c-est-ou"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Open it, then ask.",
    context: "Somebody behind a desk who has not seen you yet.",
    answers: ["Bonjour. C'est où ?"],
    alternatives: ["Bonjour, c'est où ?", "Bonjour ! C'est où ?"],
    ifCorrect: "A bare question at a stranger lands like a tap on the shoulder.",
  }),
  weaveSeed({
    id: "p-l8-apply-lost-then-ask",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say the directions went past you, then ask again.",
    context: "They pointed, said three things quickly, and walked off.",
    answers: ["Je ne comprends pas. C'est où ?"],
    alternatives: ["Je ne comprends pas, c'est où ?"],
    ifCorrect: "Naming the problem is what makes the second ask reasonable.",
  }),
  weaveSeed({
    id: "p-l8-apply-thank-for-directions",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est-ou", "chunk-merci-beaucoup"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask where it is, and thank them when they tell you.",
    context: "They stop, think, and give you a clear answer.",
    answers: ["C'est où ? Merci beaucoup !"],
    alternatives: ["C'est où ? Merci beaucoup.", "C'est où ! Merci beaucoup !"],
    ifCorrect: "Thanking for directions is what makes the next stranger help you too.",
  }),
  weaveSeed({
    id: "p-l8-apply-answer-and-point",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-oui", "chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Confirm it for them.",
    context: "Now you are the one who knows. Somebody asks at your door.",
    answers: ["Oui, c'est ici."],
    alternatives: ["Oui. C'est ici.", "Oui c'est ici"],
    ifCorrect: "Answering first and confirming second is the natural order.",
  }),
  weaveSeed({
    id: "p-l8-apply-not-this-one-try-again",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-excusez-moi", "chunk-c-est-ou"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Tell them it is not this one, and ask somebody else.",
    context: "You checked, it is the wrong door, and another person is walking past.",
    answers: ["Ce n'est pas ici. Excusez-moi, c'est où ?"],
    alternatives: ["Ce n est pas ici. Excusez-moi, c'est où ?"],
    ifCorrect: "Ruling one out and asking again is the whole method.",
  }),
  weaveSeed({
    id: "p-l8-apply-check-before-entering",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est", "chunk-excusez-moi"],
    targets: ["chunk-est-ce-que"],
    weaveType: "open",
    prompt: "Reach them, then check rather than walk in.",
    context: "A closed door with voices behind it, and somebody passing in the corridor.",
    answers: ["Excusez-moi, est-ce que c'est ici ?"],
    alternatives: ["Excusez-moi. Est-ce que c'est ici ?"],
    ifCorrect: "Est-ce que turns a statement into a question without changing the words after it.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-then-say-thanks-and-go",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-c-est-ou", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask, thank them, and close it.",
    context: "Ten seconds at a reception desk and a queue behind you.",
    answers: ["C'est où ? Merci, au revoir."],
    alternatives: ["C'est où ? Merci, au revoir !"],
    ifCorrect: "Ask, thank, close. The whole exchange, and nobody is delayed.",
  }),
  weaveSeed({
    id: "p-l8-repair-ask-not-tell",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est-ou", "chunk-c-est"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "You told them where it was. You meant to ask. Say it again.",
    context: "They are waiting for a question and you gave them a statement.",
    answers: ["C'est où ?"],
    alternatives: ["C'est où", "C est où ?"],
    ifCorrect: "Où at the end is what turns telling into asking.",
  }),
  fillSeed({
    id: "p-l8-choice-ask-or-check",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-c-est-ou", "chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-est-ce-que"],
    prompt: "You think you have found it and want to check before going in. Which one?",
    correct: { id: "o-est", text: "Est-ce que c'est ici ?" },
    traps: [
      { id: "o-ou", text: "C'est où ?", why: "That asks where it is, as if you had no idea. You have a guess to check.", tag: "meaning_shift" },
      { id: "o-ici", text: "C'est ici.", why: "That tells them. You are the one who needs telling.", tag: "meaning_shift" },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "Où asks an open question. Est-ce que checks a guess you already have.",
  }),
  fillSeed({
    id: "p-l8-choice-confirm-or-deny",
    operation: "repair", difficulty: "easy", surface: "choice", lesson: L,
    required: ["chunk-c-est", "chunk-ce-n-est-pas", "chunk-oui"],
    targets: ["chunk-ce-n-est-pas"],
    prompt: "They ask whether this is the room. It is not. What do you say?",
    correct: { id: "o-neg", text: "Non, ce n'est pas ici." },
    traps: [
      { id: "o-pos", text: "Oui, c'est ici.", why: "That confirms it, which is the opposite of what is true.", tag: "meaning_shift" },
      { id: "o-ou", text: "C'est où ?", why: "That asks them, and they were asking you.", tag: "meaning_shift" },
    ],
    short: "Non, ce n'est pas ici.",
    explanation: "The answer word first, then the correction.",
  }),
  fillSeed({
    id: "p-l8-listen-open-or-checking-question",
    operation: "repair", difficulty: "hard", surface: "listen", lesson: L,
    required: ["chunk-c-est-ou", "chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-est-ce-que"],
    audio: "Est-ce que c'est ici ?",
    prompt: "Listen. Do they have a guess, or none at all?",
    correct: { id: "o-guess", text: "A guess. They are checking this place." },
    traps: [
      { id: "o-none", text: "None. They are asking where it is.", why: "That would be c'est où. Est-ce que puts a guess on the table.", tag: "meaning_shift" },
      { id: "o-tell", text: "They are telling you it is here.", why: "The est-ce que in front makes it a question.", tag: "meaning_shift" },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "The two questions do different jobs and the opening words are the only clue.",
  }),
  fillSeed({
    id: "p-l8-listen-here-or-not-here",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-c-est", "chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    audio: "Ce n'est pas ici.",
    prompt: "Listen. Did they say it is the place, or that it is not?",
    correct: { id: "o-not", text: "It is not the place." },
    traps: [
      { id: "o-is", text: "It is the place.", why: "The ne and pas wrap the middle. Without them it would be c'est ici.", tag: "meaning_shift" },
      { id: "o-ask", text: "They asked where it is.", why: "Nothing here is a question.", tag: "meaning_shift" },
    ],
    short: "Ce n'est pas ici.",
    explanation: "The negative sits around the middle, and it is easy to hear past.",
  }),
  buildSeed({
    id: "p-l8-build-reach-ask-thank",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "chunk-merci"],
    targets: ["chunk-c-est-ou"],
    prompt: "Assemble the whole ask.",
    context: "A corridor you do not know, and somebody walking past with their arms full.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-c-est-ou", text: "c'est où ?", answerIndex: 1 },
      { itemId: "chunk-merci", text: "Merci !", answerIndex: 2 },
      { itemId: "chunk-ce-n-est-pas", text: "Ce n'est pas ici." },
    ],
    target: "Excusez-moi, c'est où ? Merci !",
    ifCorrect: "Reach, ask, thank. Three beats and you have your answer.",
    ifWrong: "Right pieces. Get their attention before the question.",
  }),
  // Was a second dictation of "Est-ce que c'est ici ?", which
  // p-l8-dictation-is-it-here already covers. The answering side of the same
  // exchange had no listening, and it is the harder one to hear: oui runs
  // straight into c'est.
  weaveSeed({
    id: "p-l8-dictation-yes-its-here",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-oui", "chunk-c-est"],
    targets: ["chunk-c-est"],
    audio: "Oui, c'est ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Oui, c'est ici."],
    alternatives: ["Oui. C'est ici.", "Oui, c est ici."],
    ifCorrect: "Three short words that arrive as one. The comma is yours to add.",
  }),
  weaveSeed({
    id: "p-l8-dictation-not-this-one",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    audio: "Ce n'est pas ici.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Ce n'est pas ici."],
    alternatives: ["Ce n est pas ici.", "Ce n'est pas ici"],
    ifCorrect: "The negative wrapping, written out.",
  }),
  weaveSeed({
    id: "p-l8-retrieve-confirm-here",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "mid",
    prompt: "Tell them this is the place.",
    context: "They have found it and are looking at you for confirmation.",
    answers: ["C'est ici."],
    alternatives: ["C est ici.", "C'est ici !"],
    ifCorrect: "Two words, and somebody stops being lost.",
  }),
  weaveSeed({
    id: "p-l8-retrieve-ask-where-cold",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-c-est-ou"],
    targets: ["chunk-c-est-ou"],
    weaveType: "mid",
    prompt: "Ask where it is.",
    context: "No idea at all, and somebody friendly in front of you.",
    answers: ["C'est où ?"],
    alternatives: ["C est où ?", "C'est où"],
    ifCorrect: "The everyday spoken shape, and the one you will actually hear.",
  }),
  weaveSeed({
    id: "p-l8-apply-greet-and-check",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-est-ce-que"],
    weaveType: "open",
    prompt: "Greet them, then check.",
    context: "A door with no sign and someone behind it.",
    answers: ["Bonjour. Est-ce que c'est ici ?"],
    alternatives: ["Bonjour, est-ce que c'est ici ?"],
    ifCorrect: "Greeting first is what makes the question a question rather than a demand.",
  }),
  weaveSeed({
    id: "p-l8-apply-name-place-ask-where",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["noun-cafe", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Name what you want, then ask where.",
    context: "You know what you are looking for, not where it is.",
    answers: ["Le café, c'est où ?"],
    alternatives: ["Le café c'est où ?"],
    ifCorrect: "The thing first, then where. That is the order French asks in.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-where-politely",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est-ou", "chunk-sil-vous-plait", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask, and soften it.",
    context: "A formal desk with a queue behind you.",
    answers: ["C'est où, s'il vous plaît ?"],
    alternatives: ["C est où, s il vous plaît ?"],
    ifCorrect: "The softener is what stops a short question sounding blunt.",
  }),
  weaveSeed({
    id: "p-l8-apply-reach-ask-politely",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "chunk-sil-vous-plait", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Reach them, ask, and soften it.",
    context: "They are busy and you need thirty seconds of their attention.",
    answers: ["Excusez-moi. C'est où, s'il vous plaît ?"],
    alternatives: ["Excusez-moi, c'est où, s'il vous plaît ?"],
    ifCorrect: "Three moves, one breath, and nobody is put out.",
  }),
  weaveSeed({
    id: "p-l8-apply-confirm-and-thank",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-c-est", "chunk-merci"],
    targets: ["chunk-oui"],
    weaveType: "open",
    prompt: "Confirm, and thank them.",
    context: "They walked you here to be sure.",
    answers: ["Oui, c'est ici. Merci."],
    alternatives: ["Oui c'est ici. Merci."],
    ifCorrect: "The thanks is for the walking, not for the answer.",
  }),
  weaveSeed({
    id: "p-l8-apply-confirm-good-evening",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-oui", "chunk-c-est", "chunk-bonne-soiree"],
    targets: ["chunk-oui"],
    weaveType: "open",
    prompt: "Confirm, and close warmly.",
    context: "They waited at the door to make sure you found it.",
    answers: ["Oui, c'est ici. Bonne soirée !"],
    alternatives: ["Oui c'est ici. Bonne soirée !"],
    ifCorrect: "Confirming lets them stop worrying and go home.",
  }),
  weaveSeed({
    id: "p-l8-apply-wrong-then-ask",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say it is wrong, and ask where it is.",
    context: "Second wrong door, and they are still trying.",
    answers: ["Ce n'est pas ici. C'est où ?"],
    alternatives: ["Ce n est pas ici. C'est où ?"],
    ifCorrect: "Correcting and asking together keeps them helping.",
  }),
  weaveSeed({
    id: "p-l8-apply-wrong-but-grateful",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-merci-beaucoup"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "open",
    prompt: "Say it is wrong, and thank them anyway.",
    context: "They walked you halfway and it was the wrong building.",
    answers: ["Ce n'est pas ici. Merci beaucoup !"],
    alternatives: ["Ce n est pas ici. Merci beaucoup !"],
    ifCorrect: "They tried. That is what the thanks is for.",
  }),
  weaveSeed({
    id: "p-l8-repair-again-and-thanks",
    operation: "repair", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-vous-pouvez-repeter", "chunk-merci-beaucoup"],
    targets: ["chunk-vous-pouvez-repeter"],
    weaveType: "open",
    prompt: "Ask for it again, and thank them properly.",
    context: "They have already repeated it twice.",
    answers: ["Vous pouvez répéter ? Merci beaucoup !"],
    alternatives: ["Vous pouvez répéter ? Merci beaucoup."],
    ifCorrect: "Beaucoup is for when you are asking more than your share.",
  }),
  weaveSeed({
    id: "p-l8-repair-ask-again-formally",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-est-ce-que", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-est-ce-que"],
    weaveType: "open",
    prompt: "Ask for the repeat, the full way.",
    context: "A formal room, and you missed the middle of it.",
    answers: ["Est-ce que vous pouvez répéter ?"],
    alternatives: ["Est ce que vous pouvez répéter ?"],
    ifCorrect: "The long form is the polite one, and worth its extra syllables here.",
  }),
  weaveSeed({
    id: "p-l8-apply-check-then-thank",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est", "chunk-merci"],
    targets: ["chunk-est-ce-que"],
    weaveType: "open",
    prompt: "Check, and thank them for answering.",
    context: "You would rather ask than push the wrong door.",
    answers: ["Est-ce que c'est ici ? Merci."],
    alternatives: ["Est ce que c'est ici ? Merci."],
    ifCorrect: "Thanking before the answer assumes goodwill, which usually produces it.",
  }),
  weaveSeed({
    id: "p-l8-apply-going-and-asking",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-vais", "chunk-au-cafe", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say where you are going, then ask where it is.",
    context: "You know the plan and not the route.",
    answers: ["Je vais au café. C'est où ?"],
    alternatives: ["Je vais au café, c'est où ?"],
    ifCorrect: "Saying the destination first tells them which where you mean.",
  }),
  weaveSeed({
    id: "p-l8-apply-order-then-where",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-cafe", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say what you want, then ask where to get it.",
    context: "A building you do not know, and one thing you do want.",
    answers: ["Je voudrais un café. C'est où ?"],
    alternatives: ["Je voudrais un café, c'est où ?"],
    ifCorrect: "The want explains the question, so they answer the right one.",
  }),
  weaveSeed({
    id: "p-l8-apply-question-then-where",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Flag the question, then ask it.",
    context: "They are mid-sentence with someone else.",
    answers: ["J'ai une question. C'est où ?"],
    alternatives: ["J ai une question. C'est où ?"],
    ifCorrect: "Flagging buys you the half second you need.",
  }),
  weaveSeed({
    id: "p-l8-repair-asked-and-lost",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-c-est-ou", "chunk-je-ne-comprends-pas", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask, then say the answer did not land.",
    context: "You asked, they answered fast, and you have nothing.",
    answers: ["C'est où ? Je ne comprends pas."],
    alternatives: ["C est où ? Je ne comprends pas."],
    ifCorrect: "Asking again immediately is easier than walking off and guessing.",
  }),
  weaveSeed({
    id: "p-l8-apply-greet-ask-thank",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-c-est-ou", "chunk-merci-beaucoup", "adverb-ou-where"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Greet, ask, and thank them properly.",
    context: "A stranger at a desk who owes you nothing.",
    answers: ["Bonjour. C'est où ? Merci beaucoup !"],
    alternatives: ["Bonjour, c'est où ? Merci beaucoup !"],
    ifCorrect: "The whole exchange, and not one new word in it.",
  }),
  // L8 had no slot-level question either. The est-ce que frame is the lesson's
  // whole point, and what goes after it is the thing learners get wrong.
  fillSeed({
    id: "p-l8-retrieve-what-follows-est-ce-que",
    operation: "retrieve",
    difficulty: "medium",
    surface: "fill",
    lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-c-est"],
    tags: ["natural-speech"],
    prompt: "Est-ce que goes in front of a statement. Which statement?",
    before: "Est-ce que ",
    after: " ici ?",
    correct: { id: "o-cest-here", text: "c'est" },
    traps: [
      {
        id: "o-ou-here",
        text: "où",
        why: "That asks where twice over. Est-ce que has already made it a question.",
        tag: "wrong_item",
      },
      {
        id: "o-oui-here",
        text: "oui",
        why: "Oui answers a question. It cannot be inside the one being asked.",
        tag: "wrong_item",
      },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "Est-ce que does the asking. Everything after it stays in the shape you already own: c'est ici.",
  }),
];
