/**
 * L8 practice seeds — the three ways to talk about a place.
 *
 * This is the densest repair territory on the path. `C'est ici.` states,
 * `C'est où ?` asks where, and `Est-ce que c'est ici ?` checks whether — three
 * sentences built from nearly the same words, and telling them apart is the
 * lesson. Two contrast seeds carry `repairsTag` so a miss on any of them can
 * pull the other into the same session.
 */
import { fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-008";

export const L8_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l8-retrieve-c-est-ou",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "mid",
    prompt: "Where is it?",
    answers: ["C'est où ?"],
    alternatives: ["C'est où?", "C'est où"],
    ifCorrect: "Two words that open almost any building.",
  }),
  weaveSeed({
    id: "p-l8-retrieve-c-est-ici",
    operation: "retrieve",
    difficulty: "easy",
    lesson: L,
    required: ["chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "mid",
    prompt: "It's here.",
    answers: ["C'est ici."],
    alternatives: ["C'est ici"],
    ifCorrect: "The same small words, pointing the other way.",
  }),
  fillSeed({
    id: "p-l8-repair-statement-or-question",
    operation: "repair",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-c-est-ou", "chunk-c-est"],
    targets: ["chunk-c-est-ou"],
    repairs: "natural-speech",
    prompt: "You cannot see the room and you need someone to tell you. What do you say?",
    correct: { id: "o-cest-ou", text: "C'est où ?" },
    traps: [
      {
        id: "o-cest-ici-ask",
        text: "C'est ici.",
        why: "That ANSWERS the question. You are the one who does not know.",
        tag: "meaning_shift",
      },
      {
        id: "o-ce-nest-pas-ask",
        text: "Ce n'est pas ici.",
        why: "That says where it is not, which leaves you exactly as lost.",
        tag: "meaning_shift",
      },
    ],
    short: "C'est où ?",
    explanation: "Où turns the statement into a question. Everything else stays put.",
  }),
  fillSeed({
    id: "p-l8-repair-which-question",
    operation: "repair",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est-ou"],
    targets: ["chunk-est-ce-que"],
    repairs: "natural-speech",
    prompt: "You think this is the room, but you would rather check than walk in on strangers.",
    correct: { id: "o-est-ce-que", text: "Est-ce que c'est ici ?" },
    traps: [
      {
        id: "o-cest-ou-check",
        text: "C'est où ?",
        why: "That asks WHERE, as if you had no idea. You have a guess and want it confirmed.",
        tag: "meaning_shift",
      },
      {
        id: "o-cest-ici-check",
        text: "C'est ici.",
        why: "That tells them it is here. You are asking, not announcing.",
        tag: "meaning_shift",
      },
    ],
    short: "Est-ce que c'est ici ?",
    explanation: "Est-ce que turns a statement into a yes/no question without changing a word of it.",
  }),
  weaveSeed({
    id: "p-l8-produce-check-the-door",
    operation: "produce",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-est-ce-que"],
    targets: ["chunk-est-ce-que"],
    weaveType: "context",
    prompt: "Check whether this is the place.",
    context: "You are outside a door you think is right, and you can hear people inside.",
    answers: ["Est-ce que c'est ici ?"],
    alternatives: ["Est-ce que c'est ici?"],
    ifCorrect: "You asked it back instead of guessing. That is what the form is for.",
  }),
  weaveSeed({
    id: "p-l8-apply-answer-the-asker",
    operation: "apply",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-oui", "chunk-c-est"],
    targets: ["chunk-oui", "chunk-c-est"],
    weaveType: "context",
    prompt: "Answer them, then confirm the place.",
    context: "They stop beside you and ask « C'est où ? ». It is this room.",
    answers: ["Oui, c'est ici."],
    alternatives: ["Oui. C'est ici."],
    ifCorrect: "You were asked in French and you answered in French. Both sides are yours now.",
  }),
  weaveSeed({
    id: "p-l8-apply-wrong-door",
    operation: "apply",
    difficulty: "medium",
    lesson: L,
    required: ["chunk-ce-n-est-pas"],
    targets: ["chunk-ce-n-est-pas"],
    weaveType: "context",
    prompt: "Tell them it isn't this one.",
    context: "Someone stops at your door and asks « C'est où ? ». The room they want is not this one.",
    answers: ["Ce n'est pas ici."],
    alternatives: ["Ce n'est pas ici"],
    ifCorrect: "Clear without being unhelpful. They will keep looking.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-politely",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "open",
    prompt: "Reach them, then ask.",
    context: "A corridor you do not know. Someone is walking past with their arms full.",
    answers: ["Excusez-moi, c'est où ?"],
    alternatives: ["Excusez-moi. C'est où ?", "Excusez-moi, c'est où?"],
    ifCorrect: "Attention first, then the question. The order never changes.",
    ifWrong: "Your meaning lands. Reach them before you ask.",
  }),
  weaveSeed({
    id: "p-l8-apply-ask-context-only",
    operation: "apply",
    difficulty: "hard",
    lesson: L,
    required: ["chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "open",
    prompt: "Ask.",
    context: "First time in the building. The room you need is not where you were told it would be.",
    answers: ["C'est où ?"],
    alternatives: ["C'est où?"],
    ifCorrect: "Nothing was handed to you and it came back anyway.",
  }),
];
