/**
 * L9 practice seeds — asking for something to happen.
 *
 * `noun-pause` is VIA_CARRIER: nobody says "pause" on its own, so every seed
 * targets `chunk-faire-une-pause`, the thing the learner actually asks for.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-009";

export const L9_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l9-retrieve-faire-une-pause",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "mid",
    prompt: "I would like to take a break.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause"],
    ifCorrect: "Je voudrais carries actions too, not just things.",
  }),
  fillSeed({
    id: "p-l9-repair-softener",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You are asking for something, not announcing it. Which piece softens the ask?",
    after: " faire une pause.",
    correct: { id: "o-je-voudrais-pause", text: "Je voudrais" },
    traps: [
      {
        id: "o-je-vais-pause",
        text: "Je vais",
        why: "That tells them you are taking one. You meant to ask, not to inform.",
        tag: "wrong_register",
      },
      {
        id: "o-jai-pause",
        text: "J'ai",
        why: "That says you HAVE a break, which is not the same as wanting one.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais is what turns a decision into a request.",
  }),
  fillSeed({
    id: "p-l9-retrieve-which-need",
    operation: "retrieve",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause"],
    prompt: "Two hours in. You are flagging, but you do not want the day to end. What do you ask for?",
    correct: { id: "o-pause", text: "Je voudrais faire une pause." },
    traps: [
      {
        id: "o-maison-need",
        text: "Je vais à la maison.",
        why: "That ends the day. You only wanted a few minutes.",
        tag: "meaning_shift",
      },
      {
        id: "o-question-need",
        text: "J'ai une question.",
        why: "That opens something new. You need to stop, not to ask.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "A break pauses the day. It does not close it.",
  }),
  weaveSeed({
    id: "p-l9-produce-ask-politely",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    weaveType: "context",
    prompt: "Ask for the break, politely.",
    context: "The room is busy and you would rather not sound like you are announcing it.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s'il vous plaît."],
    ifCorrect: "The tail does the work. Same ask, softer landing.",
  }),
  weaveSeed({
    id: "p-l9-apply-cut-in-and-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    weaveType: "context",
    prompt: "Reach them, then ask for what you need.",
    context: "The meeting is running and nobody is looking at you.",
    answers: ["Excusez-moi, je voudrais faire une pause."],
    alternatives: ["Excusez-moi. Je voudrais faire une pause."],
    ifCorrect: "Reaching them is half the request.",
  }),
  weaveSeed({
    id: "p-l9-apply-ask-and-say-why",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Ask for the break, then say what is behind it.",
    context: "Someone asks how you are doing, and it is well past lunch.",
    answers: ["Je voudrais faire une pause. J'ai faim."],
    alternatives: ["Je voudrais faire une pause, j'ai faim."],
    ifCorrect: "The ask, then the reason. That is what makes it easy to say yes to.",
    ifWrong: "Your meaning lands. Ask first, then say why.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Say what you need.",
    context: "You have been on your feet since you arrived, and there is a lull.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause, s'il vous plaît."],
    ifCorrect: "No prompt, no translation, and it still came out whole.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l9-build-ask-politely",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    tags: ["politeness"],
    prompt: "Build the request.",
    context: "The room is busy and you would rather not sound like you are announcing it.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause,", answerIndex: 1 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "j'ai faim." },
    ],
    target: "Je voudrais faire une pause, s'il vous plaît.",
    ifCorrect: "The softener goes at the end, after what you are asking for.",
    ifWrong: "Ask first; the polite tail closes it.",
  }),
  buildSeed({
    id: "p-l9-build-cut-in-and-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    prompt: "Reach them, then ask.",
    context: "The meeting is running and nobody is looking at you.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-je-voudrais", text: "je voudrais", answerIndex: 1 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 2 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît." },
    ],
    target: "Excusez-moi, je voudrais faire une pause.",
    ifCorrect: "Reaching them is half the request.",
  }),
  buildSeed({
    id: "p-l9-build-ask-and-say-why",
    operation: "apply",
    difficulty: "hard",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    prompt: "Ask, then give the reason.",
    context: "Someone asks how you are doing, and it is well past lunch.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 1 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 2 },
      { itemId: "chunk-excusez-moi", text: "Excusez-moi," },
    ],
    target: "Je voudrais faire une pause. J'ai faim.",
    ifCorrect: "The ask, then the reason. That is what makes it easy to say yes to.",
    ifWrong: "Ask first, then say why.",
  }),
  fillSeed({
    id: "p-l9-listen-the-ask",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-faire-une-pause"],
    audio: "Je voudrais faire une pause.",
    prompt: "Listen. What are they asking for?",
    correct: { id: "o-break", text: "I would like to take a break." },
    traps: [
      { id: "o-go-home-l9", text: "I would like to go home.", why: "That ends the day. A break only pauses it.", tag: "meaning_shift" },
      { id: "o-coffee-l9", text: "I would like a coffee.", why: "That asks for a thing. This one asks for an action.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais carries actions too, not only things.",
  }),
  weaveSeed({
    id: "p-l9-dictation-break",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    audio: "Je voudrais faire une pause.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["je voudrais faire une pause.", "Je voudrais faire une pause"],
    ifCorrect: "Five words, and the small one in the middle survived.",
    ifWrong: "Faire une pause travels as one piece.",
  }),
  weaveSeed({
    id: "p-l9-dictation-break-politely",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    audio: "Je voudrais faire une pause, s'il vous plaît.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s'il vous plaît."],
    ifCorrect: "A long request, caught whole, tail and all.",
  }),
  fillSeed({
    id: "p-l9-choice-pause-or-end",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause"],
    prompt: "You need ten minutes, not the rest of the day. What do you ask for?",
    correct: { id: "o-pause-only", text: "Je voudrais faire une pause." },
    traps: [
      { id: "o-hungry-only", text: "J'ai faim.", why: "That says why, without ever asking for anything.", tag: "meaning_shift" },
      { id: "o-question-only", text: "J'ai une question.", why: "That opens something new. You want to stop, not to ask.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "A break pauses the day. It does not close it.",
  }),
];
