/**
 * L9 practice seeds — asking for something to happen.
 *
 * `noun-pause` is VIA_CARRIER: nobody says "pause" on its own, so every seed
 * targets `chunk-faire-une-pause`, the thing the learner actually asks for.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-009";

export const L9_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l9-retrieve-faire-une-pause",
    operation: "retrieve",
    difficulty: "easy",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "mid",
    prompt: "I would like to take a break.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause"],
    ifCorrect: "Je voudrais carries actions too, not just things.",
  }),
  fillSeed({
    id: "p-l9-repair-softener",
    operation: "repair",
    difficulty: "easy",
    surface: "fill",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais"],
    tags: ["politeness"],
    repairs: "politeness",
    prompt: "You are asking for something, not announcing it. Which piece softens the ask?",
    after: " faire une pause.",
    correct: { id: "o-je-voudrais-pause", text: "Je voudrais" },
    traps: [
      {
        id: "o-je-vais-pause",
        text: "Je vais",
        why: "That tells them you are taking one. You meant to ask, not to inform.",
        tag: "wrong_register",
      },
      {
        id: "o-jai-pause",
        text: "J'ai",
        why: "That says you HAVE a break, which is not the same as wanting one.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais is what turns a decision into a request.",
  }),
  fillSeed({
    id: "p-l9-retrieve-which-need",
    operation: "retrieve",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause"],
    prompt: "Two hours in. You are flagging, but you do not want the day to end. What do you ask for?",
    correct: { id: "o-pause", text: "Je voudrais faire une pause." },
    traps: [
      {
        id: "o-maison-need",
        text: "Je vais à la maison.",
        why: "That ends the day. You only wanted a few minutes.",
        tag: "meaning_shift",
      },
      {
        id: "o-question-need",
        text: "J'ai une question.",
        why: "That opens something new. You need to stop, not to ask.",
        tag: "meaning_shift",
      },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "A break pauses the day. It does not close it.",
  }),
  weaveSeed({
    id: "p-l9-produce-ask-politely",
    operation: "produce",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    weaveType: "context",
    prompt: "Ask for the break, politely.",
    context: "The room is busy and you would rather not sound like you are announcing it.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s'il vous plaît."],
    ifCorrect: "The tail does the work. Same ask, softer landing.",
  }),
  weaveSeed({
    id: "p-l9-apply-cut-in-and-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    weaveType: "context",
    prompt: "Reach them, then ask for what you need.",
    context: "The meeting is running and nobody is looking at you.",
    answers: ["Excusez-moi, je voudrais faire une pause."],
    alternatives: ["Excusez-moi. Je voudrais faire une pause."],
    ifCorrect: "Reaching them is half the request.",
  }),
  weaveSeed({
    id: "p-l9-apply-ask-and-say-why",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Ask for the break, then say what is behind it.",
    context: "Someone asks how you are doing, and it is well past lunch.",
    answers: ["Je voudrais faire une pause. J'ai faim."],
    alternatives: ["Je voudrais faire une pause, j'ai faim."],
    ifCorrect: "The ask, then the reason. That is what makes it easy to say yes to.",
    ifWrong: "Your meaning lands. Ask first, then say why.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-context-only",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Say what you need.",
    context: "You have been on your feet since you arrived, and there is a lull.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause, s'il vous plaît."],
    ifCorrect: "No prompt, no translation, and it still came out whole.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l9-build-ask-politely",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    tags: ["politeness"],
    prompt: "Build the request.",
    context: "The room is busy and you would rather not sound like you are announcing it.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause,", answerIndex: 1 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "j'ai faim." },
    ],
    target: "Je voudrais faire une pause, s'il vous plaît.",
    ifCorrect: "The softener goes at the end, after what you are asking for.",
    ifWrong: "Ask first; the polite tail closes it.",
  }),
  buildSeed({
    id: "p-l9-build-cut-in-and-ask",
    operation: "apply",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    prompt: "Reach them, then ask.",
    context: "The meeting is running and nobody is looking at you.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-je-voudrais", text: "je voudrais", answerIndex: 1 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 2 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît." },
    ],
    target: "Excusez-moi, je voudrais faire une pause.",
    ifCorrect: "Reaching them is half the request.",
  }),
  buildSeed({
    id: "p-l9-build-ask-and-say-why",
    operation: "apply",
    difficulty: "hard",
    surface: "build",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    prompt: "Ask, then give the reason.",
    context: "Someone asks how you are doing, and it is well past lunch.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 1 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 2 },
      { itemId: "chunk-excusez-moi", text: "Excusez-moi," },
    ],
    target: "Je voudrais faire une pause. J'ai faim.",
    ifCorrect: "The ask, then the reason. That is what makes it easy to say yes to.",
    ifWrong: "Ask first, then say why.",
  }),
  fillSeed({
    id: "p-l9-listen-the-ask",
    operation: "retrieve",
    difficulty: "medium",
    surface: "listen",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-faire-une-pause"],
    audio: "Je voudrais faire une pause.",
    prompt: "Listen. What are they asking for?",
    correct: { id: "o-break", text: "I would like to take a break." },
    traps: [
      { id: "o-go-home-l9", text: "I would like to go home.", why: "That ends the day. A break only pauses it.", tag: "meaning_shift" },
      { id: "o-coffee-l9", text: "I would like a coffee.", why: "That asks for a thing. This one asks for an action.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais carries actions too, not only things.",
  }),
  weaveSeed({
    id: "p-l9-dictation-break",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    audio: "Je voudrais faire une pause.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["je voudrais faire une pause.", "Je voudrais faire une pause"],
    ifCorrect: "Five words, and the small one in the middle survived.",
    ifWrong: "Faire une pause travels as one piece.",
  }),
  weaveSeed({
    id: "p-l9-dictation-break-politely",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    audio: "Je voudrais faire une pause, s'il vous plaît.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s'il vous plaît."],
    ifCorrect: "A long request, caught whole, tail and all.",
  }),
  fillSeed({
    id: "p-l9-choice-pause-or-end",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause"],
    prompt: "You need ten minutes, not the rest of the day. What do you ask for?",
    correct: { id: "o-pause-only", text: "Je voudrais faire une pause." },
    traps: [
      { id: "o-hungry-only", text: "J'ai faim.", why: "That says why, without ever asking for anything.", tag: "meaning_shift" },
      { id: "o-question-only", text: "J'ai une question.", why: "That opens something new. You want to stop, not to ask.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "A break pauses the day. It does not close it.",
  }),
  // ── Asking, and giving the reason ─────────────────────────────────────────
  weaveSeed({
    id: "p-l9-apply-break-because-hungry",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-voudrais", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Ask for the break, then say what is behind it.",
    context: "Nobody has stopped since nine and it is nearly two.",
    answers: ["Je voudrais faire une pause. J'ai faim."],
    alternatives: ["Je voudrais faire une pause, j'ai faim."],
    ifCorrect: "The reason is what turns a request into something easy to say yes to.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-then-coffee",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Ask for the break, and say what you will do with it.",
    context: "You need ten minutes and there is a machine down the corridor.",
    answers: ["Je voudrais faire une pause. Je voudrais un café."],
    alternatives: ["Je voudrais faire une pause, je voudrais un café."],
    ifCorrect: "Je voudrais does both jobs: the break and the thing you want in it.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-i-dont-follow",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Say it stopped making sense, then ask for the break.",
    context: "An hour in, and the last twenty minutes went straight past you.",
    answers: ["Je ne comprends pas. Je voudrais faire une pause."],
    alternatives: ["Je ne comprends pas, je voudrais faire une pause."],
    ifCorrect: "Naming the reason first makes the break sound like a fix rather than a retreat.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-with-question",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and say you have something to raise afterwards.",
    context: "You need air, and there is one thing you want to bring up when you come back.",
    answers: ["Je voudrais faire une pause. J'ai une question."],
    alternatives: ["Je voudrais faire une pause, j'ai une question."],
    ifCorrect: "Flagging it now means the break does not look like an escape.",
  }),
  weaveSeed({
    id: "p-l9-apply-cut-in-and-ask-break",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, then ask.",
    context: "They are in full swing and nobody has looked up in twenty minutes.",
    answers: ["Excusez-moi, je voudrais faire une pause."],
    alternatives: ["Excusez-moi. Je voudrais faire une pause."],
    ifCorrect: "Interrupting well is what makes the request land instead of the interruption.",
  }),
  weaveSeed({
    id: "p-l9-apply-polite-full-request",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Ask as politely as the room deserves.",
    context: "A formal meeting, people you do not know, and you genuinely need to step out.",
    answers: ["Excusez-moi, je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Excusez-moi. Je voudrais faire une pause, s'il vous plaît."],
    ifCorrect: "Three politeness moves. In a room like that none of them is wasted.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-then-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-voudrais", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and say it is your last one.",
    context: "You will step out now and not come back afterwards.",
    answers: ["Je voudrais faire une pause. Je vais à la maison."],
    alternatives: ["Je voudrais faire une pause, je vais à la maison."],
    ifCorrect: "Saying so now is kinder than simply not returning.",
  }),
  weaveSeed({
    id: "p-l9-apply-greet-then-ask",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Open the moment, then ask.",
    context: "You have just come in and you already need five minutes.",
    answers: ["Bonjour. Je voudrais faire une pause."],
    alternatives: ["Bonjour, je voudrais faire une pause."],
    ifCorrect: "Even a request gets its greeting first.",
  }),

  // ── Being answered ────────────────────────────────────────────────────────
  weaveSeed({
    id: "p-l9-apply-thank-for-the-break",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-merci-beaucoup"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "They said yes. Thank them properly.",
    context: "They stopped the whole room for you without a word of complaint.",
    answers: ["Merci beaucoup !"],
    alternatives: ["Merci beaucoup.", "Merci beaucoup !!"],
    ifCorrect: "A break granted is a favour, and favours take beaucoup.",
  }),
  weaveSeed({
    id: "p-l9-apply-accept-a-coffee-in-the-break",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-oui", "chunk-merci", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Accept, and thank them.",
    context: "The break started and somebody is holding the pot out. « Un café ? »",
    answers: ["Oui, merci."],
    alternatives: ["Oui, merci !", "Oui merci"],
    ifCorrect: "Two words, and the break becomes sociable rather than solitary.",
  }),
  weaveSeed({
    id: "p-l9-repair-decline-in-the-break",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-non-merci"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Turn the drink down, and say what you actually need.",
    context: "A coffee is not the problem. You have not eaten since seven.",
    answers: ["Non merci. J'ai faim."],
    alternatives: ["Non merci, j'ai faim."],
    ifCorrect: "The reason redirects the offer instead of just refusing it.",
  }),
  weaveSeed({
    id: "p-l9-apply-back-from-the-break",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-je-suis-ici", "chunk-merci"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Announce that you are back, and thank them for waiting.",
    context: "Ten minutes later, and they held the room for you.",
    answers: ["Je suis ici. Merci !"],
    alternatives: ["Je suis ici, merci !", "Je suis ici. Merci."],
    ifCorrect: "Coming back audibly is what makes the break a pause rather than a disappearance.",
  }),

  // ── Choosing the right move ───────────────────────────────────────────────
  fillSeed({
    id: "p-l9-choice-ask-or-announce",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-je-vais"],
    targets: ["chunk-je-voudrais"],
    prompt: "You are asking permission, not announcing a decision. Which one?",
    correct: { id: "o-ask", text: "Je voudrais faire une pause." },
    traps: [
      { id: "o-go", text: "Je vais à la maison.", why: "That announces a departure and asks nobody anything.", tag: "meaning_shift" },
      { id: "o-here", text: "Je suis ici.", why: "That places you here. It makes no request at all.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais is what makes it a request rather than a statement.",
  }),
  fillSeed({
    id: "p-l9-choice-which-reason",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-j-ai-une-question", "chunk-faire-une-pause"],
    targets: ["chunk-j-ai-faim"],
    prompt: "It is two o'clock and nobody has eaten. Which reason fits?",
    correct: { id: "o-faim", text: "J'ai faim." },
    traps: [
      { id: "o-q", text: "J'ai une question.", why: "That raises something. It does not explain needing to stop.", tag: "meaning_shift" },
      { id: "o-nc", text: "Je ne comprends pas.", why: "True sometimes, but it is not the reason at two o'clock.", tag: "meaning_shift" },
    ],
    short: "J'ai faim.",
    explanation: "The reason should be the real one. It is what the other person is weighing.",
  }),
  fillSeed({
    id: "p-l9-fill-the-request-engine",
    operation: "repair", difficulty: "easy", surface: "fill", lesson: L,
    required: ["chunk-je-voudrais", "chunk-j-ai", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais"],
    prompt: "You are asking for something, not describing what you have. Which piece?",
    before: "",
    after: " faire une pause.",
    correct: { id: "o-vou", text: "Je voudrais" },
    traps: [
      { id: "o-jai", text: "J'ai", why: "J'ai says what you have. A break is something you are asking for.", tag: "wrong_item" },
      { id: "o-suis", text: "Je suis", why: "Je suis places you somewhere. It cannot carry a request.", tag: "wrong_item" },
    ],
    short: "Je voudrais",
    explanation: "Je voudrais faire une pause. The engine is what makes it polite.",
  }),
  fillSeed({
    id: "p-l9-fill-politeness-tail",
    operation: "repair", difficulty: "easy", surface: "fill", lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-merci", "chunk-faire-une-pause"],
    targets: ["chunk-sil-vous-plait"],
    prompt: "The room is formal. What goes on the end?",
    before: "Je voudrais faire une pause, ",
    after: ".",
    correct: { id: "o-svp", text: "s'il vous plaît" },
    traps: [
      { id: "o-mer", text: "merci", why: "Merci thanks them for something already done. The break has not been granted yet.", tag: "wrong_register" },
      { id: "o-non", text: "non merci", why: "That refuses an offer, and you are the one asking.", tag: "meaning_shift" },
    ],
    short: "s'il vous plaît",
    explanation: "Please comes before the answer; thanks comes after it.",
  }),

  // ── Hearing it ────────────────────────────────────────────────────────────
  fillSeed({
    id: "p-l9-listen-request-or-statement",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-je-vais"],
    targets: ["chunk-faire-une-pause"],
    audio: "Je voudrais faire une pause.",
    prompt: "Listen. Are they asking, or telling you?",
    correct: { id: "o-ask", text: "Asking. They would like a break." },
    traps: [
      { id: "o-tell", text: "Telling you they are leaving.", why: "That would be je vais. Je voudrais asks rather than announces.", tag: "meaning_shift" },
      { id: "o-refuse", text: "Refusing something.", why: "Nothing here is a refusal.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause.",
    explanation: "Je voudrais leaves the decision with the other person, which is what makes it a request.",
  }),
  fillSeed({
    id: "p-l9-listen-which-reason-given",
    operation: "repair", difficulty: "hard", surface: "listen", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim", "chunk-j-ai-une-question"],
    targets: ["chunk-j-ai-faim"],
    audio: "Je voudrais faire une pause. J'ai faim.",
    prompt: "Listen. Why do they want to stop?",
    correct: { id: "o-hungry", text: "They are hungry." },
    traps: [
      { id: "o-question", text: "They have a question.", why: "That would be j'ai une question. The word after j'ai is the whole reason.", tag: "meaning_shift" },
      { id: "o-lost", text: "They did not follow.", why: "That would be je ne comprends pas.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause. J'ai faim.",
    explanation: "The request comes first and the reason follows it.",
  }),
  fillSeed({
    id: "p-l9-listen-polite-or-plain",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-sil-vous-plait", "chunk-faire-une-pause", "chunk-je-voudrais"],
    targets: ["chunk-sil-vous-plait"],
    audio: "Je voudrais faire une pause, s'il vous plaît.",
    prompt: "Listen. Was there a politeness tail on it?",
    correct: { id: "o-yes", text: "Yes, they said please." },
    traps: [
      { id: "o-no", text: "No, it was the plain request.", why: "The tail is there at the end. It is short and easy to miss.", tag: "wrong_register" },
      { id: "o-thanks", text: "They thanked them.", why: "Merci would come after the answer. This is s'il vous plaît, before it.", tag: "meaning_shift" },
    ],
    short: "Je voudrais faire une pause, s'il vous plaît.",
    explanation: "The tail is what a formal room expects, and it is the first thing dropped when rushing.",
  }),

  // ── Reconstruction ────────────────────────────────────────────────────────
  buildSeed({
    id: "p-l9-build-cut-in-and-request",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    prompt: "Assemble the interruption and the request.",
    context: "They are in full swing and you need to stop for ten minutes.",
    tiles: [
      { itemId: "chunk-excusez-moi", text: "Excusez-moi,", answerIndex: 0 },
      { itemId: "chunk-je-voudrais", text: "je voudrais", answerIndex: 1 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 2 },
      { itemId: "chunk-j-ai-faim", text: "j'ai faim." },
    ],
    target: "Excusez-moi, je voudrais faire une pause.",
    ifCorrect: "Attention first, request second. The order is what stops it being rude.",
    ifWrong: "Right pieces. Reach them before you ask them for anything.",
  }),
  buildSeed({
    id: "p-l9-build-request-and-reason",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    prompt: "Put the whole request together.",
    context: "Two o'clock, nobody has stopped, and you are running out of patience.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause.", answerIndex: 1 },
      { itemId: "chunk-j-ai-faim", text: "J'ai faim.", answerIndex: 2 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît." },
    ],
    target: "Je voudrais faire une pause. J'ai faim.",
    ifCorrect: "Ask, then explain. The reason lands better after the request than before it.",
    ifWrong: "Right pieces. The request opens it.",
  }),
  buildSeed({
    id: "p-l9-build-polite-request",
    operation: "retrieve", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-sil-vous-plait"],
    prompt: "Assemble the formal version.",
    context: "People you do not know, and you would rather not sound abrupt.",
    tiles: [
      { itemId: "chunk-je-voudrais", text: "Je voudrais", answerIndex: 0 },
      { itemId: "chunk-faire-une-pause", text: "faire une pause,", answerIndex: 1 },
      { itemId: "chunk-sil-vous-plait", text: "s'il vous plaît.", answerIndex: 2 },
      { itemId: "chunk-merci", text: "merci." },
    ],
    target: "Je voudrais faire une pause, s'il vous plaît.",
    ifCorrect: "The tail goes at the end, after what you want.",
    ifWrong: "Right pieces. Please comes last.",
  }),

  // ── Writing what you heard ────────────────────────────────────────────────
  weaveSeed({
    id: "p-l9-dictation-request-and-reason",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    audio: "Je voudrais faire une pause. J'ai faim.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause. J'ai faim."],
    alternatives: ["Je voudrais faire une pause. J ai faim."],
    ifCorrect: "The request and the reason, written as two sentences.",
  }),
  weaveSeed({
    id: "p-l9-dictation-cut-in-request",
    operation: "produce", difficulty: "medium", surface: "dictation", lesson: L,
    required: ["chunk-excusez-moi", "chunk-faire-une-pause"],
    targets: ["chunk-excusez-moi"],
    audio: "Excusez-moi, je voudrais faire une pause.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Excusez-moi, je voudrais faire une pause."],
    alternatives: ["Excusez-moi. Je voudrais faire une pause.", "Excusez moi, je voudrais faire une pause."],
    ifCorrect: "The hyphen in excusez-moi is the easy thing to lose.",
  }),
  weaveSeed({
    id: "p-l9-dictation-polite-request",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-sil-vous-plait"],
    audio: "Je voudrais faire une pause, s'il vous plaît.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s'il vous plaît."],
    ifCorrect: "Three words in the tail, and every one of them is heard.",
  }),

  // ── Cold retrieval ────────────────────────────────────────────────────────
  weaveSeed({
    id: "p-l9-retrieve-plain-request",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "mid",
    prompt: "Ask for a break.",
    context: "Informal, people you know, and you simply need ten minutes.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause", "Je voudrais faire une pause !"],
    ifCorrect: "The plain version. The tail is for rooms that need it.",
  }),
  weaveSeed({
    id: "p-l9-retrieve-say-hungry",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-j-ai-faim"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "mid",
    prompt: "Say how you are, the French way.",
    context: "Somebody asks why you keep looking at the clock.",
    answers: ["J'ai faim."],
    alternatives: ["J ai faim.", "J'ai faim !"],
    ifCorrect: "French HAS hunger where English IS hungry.",
  }),
  weaveSeed({
    id: "p-l9-repair-not-je-suis-faim",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-suis"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "You reached for je suis and it was the wrong engine. Say it properly.",
    context: "You are trying to explain why you want to stop.",
    answers: ["J'ai faim."],
    alternatives: ["J ai faim.", "J'ai faim !"],
    ifCorrect: "Hunger is something you HAVE in French. Je suis faim is the commonest early slip there is.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-merci"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and close it.",
    context: "They have said yes to everything today.",
    answers: ["Je voudrais faire une pause. Merci."],
    alternatives: ["Je voudrais faire une pause, merci."],
    ifCorrect: "Thanking before the answer assumes goodwill, which usually produces it.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-warm-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-merci-beaucoup"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask, and thank them properly.",
    context: "It is the third time today you have asked for something.",
    answers: ["Je voudrais faire une pause. Merci beaucoup !"],
    alternatives: ["Je voudrais faire une pause. Merci beaucoup."],
    ifCorrect: "Beaucoup is for when you are asking more than your share.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-then-close",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-au-revoir"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and close.",
    context: "You are not coming back after it.",
    answers: ["Je voudrais faire une pause. Au revoir."],
    alternatives: ["Je voudrais faire une pause. Au revoir !"],
    ifCorrect: "Saying you are going is what makes the break honest.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-where",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-c-est-ou"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Say what you want, then ask where.",
    context: "They said there is somewhere to sit, not where.",
    answers: ["Je voudrais faire une pause. C'est où ?"],
    alternatives: ["Je voudrais faire une pause, c'est où ?"],
    ifCorrect: "The want and the location are two questions, and both are yours.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-and-cafe",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-je-vais", "chunk-au-cafe"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and say where you are taking it.",
    context: "Ten minutes, and you intend to spend them outside.",
    answers: ["Je voudrais faire une pause. Je vais au café."],
    alternatives: ["Je voudrais faire une pause, je vais au café."],
    ifCorrect: "Naming the destination is an invitation without having to ask.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-apologetic",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-desole", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Apologise, and ask anyway.",
    context: "You are the only one who needs to stop, and you know it.",
    answers: ["Désolé. Je voudrais faire une pause."],
    alternatives: ["Désolé, je voudrais faire une pause."],
    ifCorrect: "The apology does not weaken the ask. It just makes it easier to hear.",
  }),
  weaveSeed({
    id: "p-l9-apply-hungry-order-tea",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-voudrais", "chunk-un-the"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Say how you are, then order.",
    context: "You want something warm more than you want coffee.",
    answers: ["J'ai faim. Je voudrais un thé."],
    alternatives: ["J ai faim. Je voudrais un thé."],
    ifCorrect: "The state explains the order, which is why it goes first.",
  }),
  weaveSeed({
    id: "p-l9-apply-hungry-order-polite",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-voudrais", "chunk-un-cafe", "chunk-sil-vous-plait"],
    targets: ["chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Say how you are, order, and soften it.",
    context: "Nothing since breakfast, and a formal counter.",
    answers: ["J'ai faim. Je voudrais un café, s'il vous plaît."],
    alternatives: ["J ai faim. Je voudrais un café s il vous plaît."],
    ifCorrect: "State, request, softener. Each one earns the next.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-good-evening",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-bonne-soiree"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and wish them the evening.",
    context: "It is late and you are not coming back after it.",
    answers: ["Je voudrais faire une pause. Bonne soirée !"],
    alternatives: ["Je voudrais faire une pause, bonne soirée !"],
    ifCorrect: "The evening wish is what turns a break into a goodbye.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-must-go",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-je-dois-partir"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, and say you will not be back.",
    context: "You need ten minutes and then a train.",
    answers: ["Je voudrais faire une pause. Je dois partir."],
    alternatives: ["Je voudrais faire une pause, je dois partir."],
    ifCorrect: "Saying so now is kinder than simply not returning.",
  }),
  weaveSeed({
    id: "p-l9-apply-yes-and-break",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-oui", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Agree, and say what you want.",
    context: "They ask whether anyone needs to stop. You do.",
    answers: ["Oui. Je voudrais faire une pause."],
    alternatives: ["Oui, je voudrais faire une pause."],
    ifCorrect: "Saying yes first makes the request everyone's rather than yours.",
  }),
  weaveSeed({
    id: "p-l9-apply-reach-hungry-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-j-ai-faim", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Reach them, say how you are, and ask.",
    context: "Nobody has looked up in forty minutes and you have not eaten.",
    answers: ["Excusez-moi. J'ai faim. Je voudrais faire une pause."],
    alternatives: ["Excusez-moi, j'ai faim. Je voudrais faire une pause."],
    ifCorrect: "Reach, explain, ask. The explanation is what gets the yes.",
  }),
  weaveSeed({
    id: "p-l9-apply-greet-hungry-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-faim", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-j-ai-faim"],
    weaveType: "open",
    prompt: "Greet them, say how you are, and ask.",
    context: "First thing, and you skipped breakfast to get here.",
    answers: ["Bonjour. J'ai faim. Je voudrais faire une pause."],
    alternatives: ["Bonjour, j'ai faim. Je voudrais faire une pause."],
    ifCorrect: "Starting the day by asking is allowed.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-thank-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, thank them, and close.",
    context: "You are stepping out and not coming back today.",
    answers: ["Je voudrais faire une pause. Merci, au revoir."],
    alternatives: ["Je voudrais faire une pause. Merci, au revoir !"],
    ifCorrect: "Ask, thank, close. Nobody is left wondering.",
  }),
  weaveSeed({
    id: "p-l9-apply-break-polite-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait", "chunk-merci"],
    targets: ["chunk-sil-vous-plait"],
    weaveType: "open",
    prompt: "Ask politely, and thank them.",
    context: "A formal session where you are the one who needs to stop.",
    answers: ["Je voudrais faire une pause, s'il vous plaît. Merci."],
    alternatives: ["Je voudrais faire une pause s il vous plaît. Merci."],
    ifCorrect: "Please before the answer, thanks after it. Both, in that order.",
  }),
  weaveSeed({
    id: "p-l9-apply-reach-break-thanks",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause", "chunk-merci"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Reach them, ask, and thank them.",
    context: "Interrupting to ask is less disruptive than fading out.",
    answers: ["Excusez-moi. Je voudrais faire une pause. Merci."],
    alternatives: ["Excusez-moi, je voudrais faire une pause. Merci."],
    ifCorrect: "Three moves, and none of them needs a new word.",
  }),
  weaveSeed({
    id: "p-l9-apply-reach-break-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause", "chunk-au-revoir"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Reach them, ask, and close.",
    context: "You are going now and saying so on the way out.",
    answers: ["Excusez-moi. Je voudrais faire une pause. Au revoir."],
    alternatives: ["Excusez-moi, je voudrais faire une pause. Au revoir."],
    ifCorrect: "Announcing the exit costs one word and saves a search.",
  }),
  weaveSeed({
    id: "p-l9-apply-reach-order-tea-polite-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-un-the", "chunk-sil-vous-plait", "chunk-merci"],
    targets: ["chunk-excusez-moi"],
    weaveType: "open",
    prompt: "Reach them, order the other one politely, and close.",
    context: "A quiet place, an unhurried person, and time to say it properly.",
    answers: ["Excusez-moi. Je voudrais un thé, s'il vous plaît. Merci."],
    alternatives: ["Excusez-moi, je voudrais un thé, s'il vous plaît. Merci."],
    ifCorrect: "The full polite frame, and it still fits in one breath.",
  }),
];
