/**
 * L10 practice seeds — a whole small day.
 *
 * NOT included here, deliberately: `chunk-vous-pouvez` and `chunk-m-aider`.
 * L10 declares them `supported`, but it only ever PREVIEWS them on a "Just
 * listen." card — the production that owns them lives in L11. An L1-L10 learner
 * has therefore not lawfully reached them, and demanding them would be exactly
 * the future-language failure the eligibility rule exists to prevent.
 */
import { buildSeed, fillSeed, weaveSeed } from "./build";
import type { PracticeSeed } from "../practiceTypes";

const L = "v1-lesson-010";

export const L10_SEEDS: PracticeSeed[] = [
  weaveSeed({
    id: "p-l10-apply-morning-arrival",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-bonjour", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-bonjour", "chunk-c-est-ou", "adverb-ou-where"],
    weaveType: "context",
    prompt: "Open politely, then ask where it is.",
    context: "Morning. First time in this building, and the room you need is not where you expected.",
    answers: ["Bonjour. C'est où ?"],
    alternatives: ["Bonjour, c'est où ?"],
    ifCorrect: "The day starts the way every day here starts.",
  }),
  fillSeed({
    id: "p-l10-repair-lost-the-thread",
    operation: "repair",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    targets: ["chunk-je-ne-comprends-pas"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "They answer you warmly, at speed, with three details you did not catch.",
    correct: { id: "o-jncp-day", text: "Je ne comprends pas." },
    traps: [
      {
        id: "o-merci-day",
        text: "Merci.",
        why: "That closes it politely and leaves you exactly as lost.",
        tag: "meaning_shift",
      },
      {
        id: "o-cest-ici-day",
        text: "C'est ici.",
        why: "That answers the question you asked, as if you were the one who knew.",
        tag: "meaning_shift",
      },
    ],
    short: "Je ne comprends pas.",
    explanation: "Naming the problem is what keeps the day moving.",
  }),
  weaveSeed({
    id: "p-l10-repair-say-so-and-ask-again",
    operation: "repair",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    weaveType: "open",
    prompt: "Say you did not follow, then put the question back.",
    context: "They have paused, willing to go again. You get one clean try at this.",
    answers: ["Je ne comprends pas. C'est où ?"],
    alternatives: ["Je ne comprends pas, c'est où ?"],
    ifCorrect: "That is the whole repair: name the problem, then ask again.",
    ifWrong: "Your meaning lands. Say you did not follow first, then ask the question again.",
  }),
  weaveSeed({
    id: "p-l10-apply-midday-break",
    operation: "apply",
    difficulty: "medium",
    surface: "typed",
    lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais", "chunk-faire-une-pause"],
    weaveType: "context",
    prompt: "Say you'd like to take a break.",
    context: "Midday. You have been on your feet since you arrived, and someone asks how you are doing.",
    answers: ["Je voudrais faire une pause."],
    alternatives: ["Je voudrais faire une pause, s'il vous plaît."],
    ifCorrect: "Middle of the day, and you can still ask for what you need.",
  }),
  weaveSeed({
    id: "p-l10-apply-close-the-day",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say you're going home, then say goodbye.",
    context: "Evening. The day at the new place is done and people are still talking.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir."],
    ifCorrect: "You opened the day in French and you closed it in French.",
  }),
  weaveSeed({
    id: "p-l10-apply-here-and-lost",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: ["chunk-je-suis", "chunk-c-est-ou"],
    targets: ["chunk-je-suis", "chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say you have arrived, then ask where to go.",
    context: "You are through the front door and expected, but nobody said which room.",
    answers: ["Je suis ici. C'est où ?"],
    alternatives: ["Je suis ici, c'est où ?"],
    ifCorrect: "Two things you own, doing a job neither could do alone.",
    ifWrong: "Your meaning lands. Say you are here, then ask where to go.",
  }),
  weaveSeed({
    id: "p-l10-apply-whole-day",
    operation: "apply",
    difficulty: "hard",
    surface: "context",
    lesson: L,
    required: [
      "chunk-bonjour",
      "chunk-c-est-ou",
      "chunk-faire-une-pause",
      "chunk-je-vais",
      "chunk-au-revoir",
    ],
    targets: ["chunk-c-est-ou", "chunk-faire-une-pause", "chunk-au-revoir"],
    weaveType: "open",
    prompt: "Take the whole day, from arriving to leaving.",
    context: "Arrive, find the room, ask for your break, and go home at the end of it.",
    answers: [
      "Bonjour. C'est où ? Je voudrais faire une pause. Je vais à la maison. Au revoir.",
    ],
    alternatives: [
      "Bonjour, c'est où ? Je voudrais faire une pause. Je vais à la maison. Au revoir.",
    ],
    ifCorrect: "A whole day in French, out of pieces you already had.",
    ifWrong: "Your meaning lands. Arrive, ask, request your break, then leave.",
  }),

  // ── V1.5: reconstruction, listening, dictation ────────────────────────────
  buildSeed({
    id: "p-l10-build-the-repair",
    operation: "repair",
    difficulty: "medium",
    surface: "build",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    prompt: "Build the repair.",
    context: "They answered warmly, at speed, and they have paused to let you back in.",
    tiles: [
      { itemId: "chunk-je-ne-comprends-pas", text: "Je ne comprends pas.", answerIndex: 0 },
      { itemId: "chunk-c-est-ou", text: "C'est où ?", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir." },
    ],
    target: "Je ne comprends pas. C'est où ?",
    ifCorrect: "Name the problem, then ask again. The day carries on.",
    ifWrong: "Say you did not follow before you ask the question again.",
  }),
  buildSeed({
    id: "p-l10-build-the-morning",
    operation: "retrieve",
    difficulty: "easy",
    surface: "build",
    lesson: L,
    required: ["chunk-bonjour", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-bonjour", "chunk-c-est-ou"],
    prompt: "Build the way the day starts.",
    context: "Morning, first time in the building, and the room is not where you expected.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-c-est-ou", text: "C'est où ?", answerIndex: 1 },
      { itemId: "chunk-au-revoir", text: "Au revoir." },
    ],
    target: "Bonjour. C'est où ?",
    ifCorrect: "Open politely, then ask. Every day here starts like this.",
  }),
  fillSeed({
    id: "p-l10-listen-the-repair",
    operation: "repair",
    difficulty: "hard",
    surface: "listen",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    targets: ["chunk-je-ne-comprends-pas"],
    tags: ["natural-speech"],
    repairs: "natural-speech",
    audio: "Je ne comprends pas. C'est où ?",
    prompt: "Listen. What is this person doing?",
    correct: { id: "o-repairing", text: "Saying they didn't follow, and asking again." },
    traps: [
      { id: "o-just-lost", text: "Saying they didn't follow, and giving up.", why: "There is a second sentence, and it is a question.", tag: "meaning_shift" },
      { id: "o-just-asking", text: "Only asking where something is.", why: "Something comes first: the reason they are asking again.", tag: "meaning_shift" },
    ],
    short: "Je ne comprends pas. C'est où ?",
    explanation: "Two sentences you own, doing one job together.",
  }),
  weaveSeed({
    id: "p-l10-dictation-the-repair",
    operation: "produce",
    difficulty: "hard",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    targets: ["chunk-je-ne-comprends-pas", "chunk-c-est-ou"],
    audio: "Je ne comprends pas. C'est où ?",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je ne comprends pas. C'est où ?"],
    alternatives: ["Je ne comprends pas, c'est où ?", "je ne comprends pas. c'est où ?"],
    ifCorrect: "The whole repair, heard once and written back.",
    ifWrong: "Two sentences: what went wrong, then the question again.",
  }),
  weaveSeed({
    id: "p-l10-dictation-close-the-day",
    operation: "produce",
    difficulty: "medium",
    surface: "dictation",
    lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    audio: "Je vais à la maison. Au revoir.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison, au revoir."],
    ifCorrect: "The end of the day, written the way it sounds.",
  }),
  fillSeed({
    id: "p-l10-choice-what-does-the-day-need",
    operation: "apply",
    difficulty: "medium",
    surface: "choice",
    lesson: L,
    required: ["chunk-c-est-ou", "chunk-faire-une-pause", "chunk-je-vais"],
    targets: ["chunk-c-est-ou"],
    prompt: "You have just arrived and you cannot find the room. What do you need first?",
    correct: { id: "o-need-where", text: "C'est où ?" },
    traps: [
      { id: "o-need-pause", text: "Je voudrais faire une pause.", why: "That is for later in the day. You have not started yet.", tag: "meaning_shift" },
      { id: "o-need-home", text: "Je vais à la maison.", why: "That ends the day before it begins.", tag: "meaning_shift" },
    ],
    short: "C'est où ?",
    explanation: "The day has an order, and this is the question it opens with.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-then-ask-the-room",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis", "chunk-c-est-ou"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Open the day, then ask for the room.",
    context: "First morning, a building you have never been in, nobody expecting you yet.",
    answers: ["Bonjour. C'est où ?"],
    alternatives: ["Bonjour, c'est où ?"],
    ifCorrect: "Greeting first is not optional in France, even when you are lost.",
  }),
  weaveSeed({
    id: "p-l10-apply-lost-and-hungry",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say it went past you, then ask to stop.",
    context: "Midday, an hour of explanation, and you stopped following it a while ago.",
    answers: ["Je ne comprends pas. Je voudrais faire une pause."],
    alternatives: ["Je ne comprends pas, je voudrais faire une pause."],
    ifCorrect: "The break is the fix for the problem you just named.",
  }),
  weaveSeed({
    id: "p-l10-apply-confirm-then-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-c-est", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Confirm you are in the right place, then ask for the break.",
    context: "You found it at last, and you have been on your feet for two hours.",
    answers: ["C'est ici. Je voudrais faire une pause."],
    alternatives: ["C est ici. Je voudrais faire une pause."],
    ifCorrect: "Arriving and asking are two separate moves, and both are yours to make.",
  }),
  weaveSeed({
    id: "p-l10-apply-thank-and-head-home",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    weaveType: "open",
    prompt: "Thank them, then say where you are going.",
    context: "The day is done, they helped all afternoon, and it is dark outside.",
    answers: ["Merci beaucoup. Je vais à la maison."],
    alternatives: ["Merci beaucoup, je vais à la maison."],
    ifCorrect: "The thanks belongs before the departure, not shouted from the door.",
  }),
  weaveSeed({
    id: "p-l10-apply-ask-check-then-thank",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-c-est-ou", "chunk-merci-beaucoup", "chunk-au-revoir"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask, thank them, and close it.",
    context: "One stranger, one question, and you will not see them again.",
    answers: ["C'est où ? Merci beaucoup, au revoir !"],
    alternatives: ["C'est où ? Merci beaucoup, au revoir."],
    ifCorrect: "The whole encounter, opened and closed by you.",
  }),
  weaveSeed({
    id: "p-l10-apply-whole-morning",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis", "chunk-j-ai-une-question"],
    targets: ["chunk-je-suis"],
    weaveType: "open",
    prompt: "Greet them, say you have arrived, and say what you came for.",
    context: "They were told to expect you and are half looking up.",
    answers: ["Bonjour. Je suis ici. J'ai une question."],
    alternatives: ["Bonjour, je suis ici. J'ai une question."],
    ifCorrect: "Three short sentences and the whole arrival is done.",
  }),
  weaveSeed({
    id: "p-l10-repair-wrong-room-then-ask",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-c-est-ou", "chunk-excusez-moi"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say it is not the place, apologise for the interruption, and ask.",
    context: "You opened the wrong door and eight people are looking at you.",
    answers: ["Ce n'est pas ici. Excusez-moi, c'est où ?"],
    alternatives: ["Ce n est pas ici. Excusez-moi, c'est où ?"],
    ifCorrect: "The recovery is worth more than the mistake cost you.",
  }),
  weaveSeed({
    id: "p-l10-apply-decline-and-close-the-day",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Turn it down, say where you are going, and close.",
    context: "They offer one more coffee at seven and you have had enough of the day.",
    answers: ["Non merci. Je vais à la maison. Au revoir !"],
    alternatives: ["Non merci, je vais à la maison. Au revoir !"],
    ifCorrect: "Three moves, and every one of them was learned in a different lesson.",
  }),
  fillSeed({
    id: "p-l10-choice-which-part-of-the-day",
    operation: "repair", difficulty: "medium", surface: "choice", lesson: L,
    required: ["chunk-bonjour", "chunk-au-revoir", "chunk-je-vais"],
    targets: ["chunk-au-revoir"],
    prompt: "The day is finished and you are the one leaving. Which word?",
    correct: { id: "o-bye", text: "Au revoir." },
    traps: [
      { id: "o-hi", text: "Bonjour.", why: "That opens a day. You are closing one.", tag: "meaning_shift" },
      { id: "o-here", text: "Je suis ici.", why: "That announces an arrival, which is the wrong end of the day.", tag: "meaning_shift" },
    ],
    short: "Au revoir.",
    explanation: "The same building needs a different word coming in and going out.",
  }),
  fillSeed({
    id: "p-l10-listen-which-stage-of-the-day",
    operation: "repair", difficulty: "hard", surface: "listen", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-a-la-maison"],
    audio: "Je vais à la maison. Au revoir.",
    prompt: "Listen. Where in the day are they?",
    correct: { id: "o-end", text: "At the end of it, on their way out." },
    traps: [
      { id: "o-start", text: "At the start, just arriving.", why: "Au revoir closes. Bonjour would open.", tag: "meaning_shift" },
      { id: "o-mid", text: "In the middle, taking a break.", why: "A break is faire une pause, and they would be coming back.", tag: "meaning_shift" },
    ],
    short: "Je vais à la maison. Au revoir.",
    explanation: "Destination plus closing is the shape a departure always takes.",
  }),
  fillSeed({
    id: "p-l10-listen-asking-or-arriving",
    operation: "repair", difficulty: "medium", surface: "listen", lesson: L,
    required: ["chunk-je-suis", "chunk-c-est-ou"],
    targets: ["chunk-je-suis"],
    audio: "Bonjour. Je suis ici.",
    prompt: "Listen. Are they announcing themselves, or asking for something?",
    correct: { id: "o-arrive", text: "Announcing that they have arrived." },
    traps: [
      { id: "o-ask", text: "Asking where something is.", why: "That would end in où. This one places them.", tag: "meaning_shift" },
      { id: "o-leave", text: "Saying they are leaving.", why: "Nothing here names a departure.", tag: "meaning_shift" },
    ],
    short: "Bonjour. Je suis ici.",
    explanation: "Je suis ici is the arrival sentence, and it opens rather than closes.",
  }),
  buildSeed({
    id: "p-l10-build-the-whole-arrival",
    operation: "apply", difficulty: "hard", surface: "build", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis", "chunk-j-ai-une-question"],
    targets: ["chunk-je-suis"],
    prompt: "Put the arrival together.",
    context: "Expected, on time, and with one thing to ask.",
    tiles: [
      { itemId: "chunk-bonjour", text: "Bonjour.", answerIndex: 0 },
      { itemId: "chunk-je-suis", text: "Je suis ici.", answerIndex: 1 },
      { itemId: "chunk-j-ai-une-question", text: "J'ai une question.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir." },
    ],
    target: "Bonjour. Je suis ici. J'ai une question.",
    ifCorrect: "Greet, announce, ask. The order never changes.",
    ifWrong: "Right pieces. The greeting opens it.",
  }),
  buildSeed({
    id: "p-l10-build-close-the-day",
    operation: "apply", difficulty: "medium", surface: "build", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-je-vais", "chunk-au-revoir"],
    prompt: "Assemble the end of the day.",
    context: "They helped all afternoon and it is dark outside.",
    tiles: [
      { itemId: "chunk-merci-beaucoup", text: "Merci beaucoup.", answerIndex: 0 },
      { itemId: "chunk-je-vais", text: "Je vais", answerIndex: 1 },
      { itemId: "chunk-a-la-maison", text: "à la maison.", answerIndex: 2 },
      { itemId: "chunk-au-revoir", text: "Au revoir.", answerIndex: 3 },
      { itemId: "chunk-c-est-ou", text: "C'est où ?" },
    ],
    target: "Merci beaucoup. Je vais à la maison. Au revoir.",
    ifCorrect: "Thanks, destination, close. Three lessons in one sentence.",
    ifWrong: "Right pieces. The thanks comes before the leaving.",
  }),
  weaveSeed({
    id: "p-l10-dictation-whole-departure",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-merci-beaucoup", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-je-vais"],
    audio: "Merci beaucoup. Je vais à la maison.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Merci beaucoup. Je vais à la maison."],
    alternatives: ["Merci beaucoup, je vais à la maison."],
    ifCorrect: "Two sentences from two different lessons, heard as one departure.",
  }),
  weaveSeed({
    id: "p-l10-dictation-arrival-question",
    operation: "produce", difficulty: "hard", surface: "dictation", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis", "chunk-j-ai-une-question"],
    targets: ["chunk-je-suis"],
    audio: "Bonjour. Je suis ici. J'ai une question.",
    weaveType: "open",
    prompt: "Write what you hear.",
    answers: ["Bonjour. Je suis ici. J'ai une question."],
    alternatives: ["Bonjour, je suis ici. J'ai une question."],
    ifCorrect: "Three sentences, three lessons, one arrival.",
  }),
  weaveSeed({
    id: "p-l10-retrieve-going-home-close",
    operation: "retrieve", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Say where you are going, and close.",
    context: "The end of an ordinary day.",
    answers: ["Je vais à la maison. Au revoir."],
    alternatives: ["Je vais à la maison. Au revoir !"],
    ifCorrect: "The shape a French departure almost always takes.",
  }),
  weaveSeed({
    id: "p-l10-apply-reach-then-ask",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Reach them first, then ask.",
    context: "They are walking past and have not seen you.",
    answers: ["Excusez-moi. C'est où ?"],
    alternatives: ["Excusez-moi, c'est où ?"],
    ifCorrect: "Reaching first is what turns a question into a conversation.",
  }),
  weaveSeed({
    id: "p-l10-apply-ask-politely",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-c-est-ou", "chunk-sil-vous-plait", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Ask, and soften it.",
    context: "A formal reception desk, and there is a queue behind you.",
    answers: ["C'est où, s'il vous plaît ?"],
    alternatives: ["C est où, s il vous plaît ?"],
    ifCorrect: "S'il vous plaît after a question is what keeps it from sounding like a demand.",
  }),
  weaveSeed({
    id: "p-l10-apply-name-the-place-then-ask",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["noun-cafe", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Name the place, then ask where it is.",
    context: "You know what you are looking for and not where it is.",
    answers: ["Le café, c'est où ?"],
    alternatives: ["Le café c'est où ?"],
    ifCorrect: "Naming it first is how French asks: the thing, then where.",
  }),
  weaveSeed({
    id: "p-l10-apply-question-then-where",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Flag the question, then ask it.",
    context: "They are mid-sentence with someone else and will turn to you next.",
    answers: ["J'ai une question. C'est où ?"],
    alternatives: ["J ai une question. C'est où ?"],
    ifCorrect: "Flagging first buys you the half second you need.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-reach-ask",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-excusez-moi", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Greet, reach, and ask.",
    context: "First thing in the morning, and you are already lost.",
    answers: ["Bonjour. Excusez-moi, c'est où ?"],
    alternatives: ["Bonjour, excusez-moi, c'est où ?"],
    ifCorrect: "Three moves that cost one breath and buy you the whole day.",
  }),
  weaveSeed({
    id: "p-l10-apply-is-this-it",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Ask whether this is the place.",
    context: "A door with no sign, and you would rather ask than walk in.",
    answers: ["Est-ce que c'est ici ?"],
    alternatives: ["Est ce que c'est ici ?"],
    ifCorrect: "Est-ce que turns a statement into a question without touching the rest.",
  }),
  weaveSeed({
    id: "p-l10-apply-check-before-committing",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-j-ai-une-question", "chunk-est-ce-que", "chunk-c-est"],
    targets: ["chunk-c-est"],
    weaveType: "open",
    prompt: "Flag it, then check.",
    context: "You are about to sit down in what may be the wrong room.",
    answers: ["J'ai une question. Est-ce que c'est ici ?"],
    alternatives: ["J ai une question. Est ce que c'est ici ?"],
    ifCorrect: "Checking costs one sentence. Not checking costs the afternoon.",
  }),
  weaveSeed({
    id: "p-l10-apply-hungry-so-break",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Say how you are, then ask.",
    context: "Two hours in, and you have not eaten since seven.",
    answers: ["J'ai faim. Je voudrais faire une pause."],
    alternatives: ["J ai faim. Je voudrais faire une pause."],
    ifCorrect: "The reason first makes the request easy to say yes to.",
  }),
  weaveSeed({
    id: "p-l10-apply-break-politely",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-sil-vous-plait"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask for the break, politely.",
    context: "A long formal session and you are the one who needs to stop.",
    answers: ["Je voudrais faire une pause, s'il vous plaît."],
    alternatives: ["Je voudrais faire une pause s il vous plaît."],
    ifCorrect: "Politeness is what makes a personal need sound reasonable.",
  }),
  weaveSeed({
    id: "p-l10-apply-reach-then-break",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-excusez-moi", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Reach them, then ask for the break.",
    context: "Nobody has looked up in forty minutes.",
    answers: ["Excusez-moi. Je voudrais faire une pause."],
    alternatives: ["Excusez-moi, je voudrais faire une pause."],
    ifCorrect: "Interrupting to ask for a break is still less disruptive than fading out.",
  }),
  weaveSeed({
    id: "p-l10-apply-break-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-merci"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Ask, and close it.",
    context: "They have already said yes to everything today.",
    answers: ["Je voudrais faire une pause. Merci."],
    alternatives: ["Je voudrais faire une pause, merci."],
    ifCorrect: "Thanking before the answer assumes goodwill, which usually produces it.",
  }),
  weaveSeed({
    id: "p-l10-apply-break-where",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-faire-une-pause", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say what you want, then ask where.",
    context: "They said there is somewhere to sit. They did not say where.",
    answers: ["Je voudrais faire une pause. C'est où ?"],
    alternatives: ["Je voudrais faire une pause, c'est où ?"],
    ifCorrect: "The want and the location are two questions, and both are yours to ask.",
  }),
  weaveSeed({
    id: "p-l10-apply-decline-then-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-non-merci", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Turn down what is offered, and say what you want instead.",
    context: "They offer another coffee. You want ten minutes outside.",
    answers: ["Non merci. Je voudrais faire une pause."],
    alternatives: ["Non merci, je voudrais faire une pause."],
    ifCorrect: "A refusal lands better with the real want attached.",
  }),
  weaveSeed({
    id: "p-l10-apply-hungry-where",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say how you are, then ask where.",
    context: "Lunchtime in a building you do not know.",
    answers: ["J'ai faim. C'est où ?"],
    alternatives: ["J ai faim. C'est où ?"],
    ifCorrect: "Two short sentences do the work of one long explanation.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-and-hungry",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-faim"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Greet them, and say how you are.",
    context: "You arrive at the counter and they ask how you are.",
    answers: ["Bonjour. J'ai faim."],
    alternatives: ["Bonjour, j'ai faim."],
    ifCorrect: "Answering honestly is faster than answering politely.",
  }),
  weaveSeed({
    id: "p-l10-apply-hungry-order",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Say how you are, then order.",
    context: "The counter is free and you have ten minutes.",
    answers: ["J'ai faim. Je voudrais un café."],
    alternatives: ["J ai faim. Je voudrais un café."],
    ifCorrect: "The state explains the order, which is why it goes first.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-question-thanks",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-j-ai-une-question", "chunk-merci"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Greet, ask, thank.",
    context: "A stranger at a desk who owes you nothing.",
    answers: ["Bonjour. J'ai une question. Merci."],
    alternatives: ["Bonjour, j'ai une question. Merci."],
    ifCorrect: "The whole exchange, and you have not needed a single new word.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-and-arrive",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici"],
    targets: ["chunk-bonjour"],
    weaveType: "open",
    prompt: "Greet them, and announce yourself.",
    context: "You are expected, and nobody has looked up.",
    answers: ["Bonjour. Je suis ici."],
    alternatives: ["Bonjour, je suis ici."],
    ifCorrect: "Announcing yourself is not rude. Waiting to be noticed is just slower.",
  }),
  weaveSeed({
    id: "p-l10-apply-arrived-and-hungry",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-j-ai-faim", "chunk-je-suis"],
    targets: ["chunk-je-suis"],
    weaveType: "open",
    prompt: "Say you are here, and how you are.",
    context: "You arrive for lunch and they have not ordered.",
    answers: ["Je suis ici. J'ai faim."],
    alternatives: ["Je suis ici, j'ai faim."],
    ifCorrect: "Two facts, no connective needed between them.",
  }),
  weaveSeed({
    id: "p-l10-apply-arrived-want-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-je-voudrais", "chunk-faire-une-pause"],
    targets: ["chunk-faire-une-pause"],
    weaveType: "open",
    prompt: "Announce yourself, then say what you need.",
    context: "You arrive straight from a three-hour train.",
    answers: ["Je suis ici. Je voudrais faire une pause."],
    alternatives: ["Je suis ici, je voudrais faire une pause."],
    ifCorrect: "Arriving and needing a moment are allowed to be the same sentence.",
  }),
  weaveSeed({
    id: "p-l10-apply-arrive-and-leave",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-suis-ici", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say you came, and that you are not staying.",
    context: "You promised to look in. They are on a call.",
    answers: ["Je suis ici. Au revoir."],
    alternatives: ["Je suis ici, au revoir.", "Je suis ici. Au revoir !"],
    ifCorrect: "Showing up counts even when it lasts four seconds.",
  }),
  weaveSeed({
    id: "p-l10-apply-wrong-place-then-ask",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-c-est-ou", "adverb-ou-where"],
    targets: ["chunk-c-est-ou"],
    weaveType: "open",
    prompt: "Say it is wrong, and ask where it is.",
    context: "Second wrong door, and they are still trying to help.",
    answers: ["Ce n'est pas ici. C'est où ?"],
    alternatives: ["Ce n est pas ici. C'est où ?"],
    ifCorrect: "Correcting and asking in one breath keeps them helping.",
  }),
  weaveSeed({
    id: "p-l10-repair-wrong-and-lost",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say it is wrong, and that you are lost.",
    context: "The directions were confident and none of them worked.",
    answers: ["Ce n'est pas ici. Je ne comprends pas."],
    alternatives: ["Ce n est pas ici. Je ne comprends pas."],
    ifCorrect: "Admitting both at once is faster than pretending to one.",
  }),
  weaveSeed({
    id: "p-l10-apply-wrong-and-go",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-ce-n-est-pas", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say it is wrong, and close it.",
    context: "You are out of time to keep looking today.",
    answers: ["Ce n'est pas ici. Au revoir."],
    alternatives: ["Ce n est pas ici. Au revoir !"],
    ifCorrect: "Stopping out loud is kinder than drifting away.",
  }),
  weaveSeed({
    id: "p-l10-repair-lost-ask-again",
    operation: "repair", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-vous-pouvez-repeter"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Say you did not follow, and ask for it again.",
    context: "Full speed, and you caught the first three words.",
    answers: ["Je ne comprends pas. Vous pouvez répéter ?"],
    alternatives: ["Je ne comprends pas, vous pouvez répéter ?"],
    ifCorrect: "Saying you are lost is half of it. The ask is the other half.",
  }),
  weaveSeed({
    id: "p-l10-repair-lost-and-reach",
    operation: "repair", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-excusez-moi"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "open",
    prompt: "Interrupt, and say you are lost.",
    context: "They are three sentences past where you stopped following.",
    answers: ["Excusez-moi. Je ne comprends pas."],
    alternatives: ["Excusez-moi, je ne comprends pas."],
    ifCorrect: "Interrupting early costs less than nodding through the rest.",
  }),
  weaveSeed({
    id: "p-l10-repair-sorry-lost",
    operation: "repair", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-desole", "chunk-je-ne-comprends-pas"],
    targets: ["chunk-je-ne-comprends-pas"],
    weaveType: "mid",
    prompt: "Apologise, and say you did not follow.",
    context: "A loud room, and it is nobody's fault.",
    answers: ["Désolé. Je ne comprends pas."],
    alternatives: ["Désolé, je ne comprends pas."],
    ifCorrect: "Désolé here is not guilt. It is the sound of asking for a moment.",
  }),
  weaveSeed({
    id: "p-l10-repair-give-up-kindly",
    operation: "repair", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-ne-comprends-pas", "chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say it never landed, thank them, and close.",
    context: "Third try, and neither of you has more time for it.",
    answers: ["Je ne comprends pas. Merci, au revoir."],
    alternatives: ["Je ne comprends pas. Merci, au revoir !"],
    ifCorrect: "Thanking for a failed attempt keeps the door open for the next one.",
  }),
  weaveSeed({
    id: "p-l10-apply-home-good-evening",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-bonne-soiree"],
    targets: ["chunk-je-vais"],
    weaveType: "open",
    prompt: "Say where you are going, and wish them the evening.",
    context: "Coats on, and the light has gone.",
    answers: ["Je vais à la maison. Bonne soirée !"],
    alternatives: ["Je vais à la maison, bonne soirée !"],
    ifCorrect: "The evening wish is what turns leaving into a goodbye.",
  }),
  weaveSeed({
    id: "p-l10-apply-hungry-going-home",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-j-ai-faim", "chunk-je-vais", "chunk-a-la-maison"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Say how you are, and where you are going.",
    context: "Nothing since lunch, and dinner is at home.",
    answers: ["J'ai faim. Je vais à la maison."],
    alternatives: ["J ai faim. Je vais à la maison."],
    ifCorrect: "The reason makes the leaving read as ordinary rather than abrupt.",
  }),
  weaveSeed({
    id: "p-l10-apply-home-and-thanks",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-merci"],
    targets: ["chunk-a-la-maison"],
    weaveType: "open",
    prompt: "Say where you are going, and thank them.",
    context: "A good day, and they made most of it work.",
    answers: ["Je vais à la maison. Merci."],
    alternatives: ["Je vais à la maison, merci."],
    ifCorrect: "Two ordinary sentences that end a day properly.",
  }),
  weaveSeed({
    id: "p-l10-apply-full-close",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-vais", "chunk-a-la-maison", "chunk-au-revoir", "chunk-bonne-soiree"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Say where you are going, close, and wish them the evening.",
    context: "The long version, at a door, with nobody in a hurry.",
    answers: ["Je vais à la maison. Au revoir, bonne soirée !"],
    alternatives: ["Je vais à la maison. Au revoir, bonne soirée."],
    ifCorrect: "Three beats. Use them when there is time for them.",
  }),
  weaveSeed({
    id: "p-l10-apply-decline-and-go",
    operation: "apply", difficulty: "medium", surface: "typed", lesson: L,
    required: ["chunk-non-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "open",
    prompt: "Turn it down, and close.",
    context: "A last offer at the door you do not owe a reason for.",
    answers: ["Non merci. Au revoir."],
    alternatives: ["Non merci, au revoir.", "Non merci. Au revoir !"],
    ifCorrect: "Merci is doing the work a reason would otherwise have to.",
  }),
  weaveSeed({
    id: "p-l10-apply-thanks-and-close",
    operation: "apply", difficulty: "easy", surface: "typed", lesson: L,
    required: ["chunk-merci", "chunk-au-revoir"],
    targets: ["chunk-au-revoir"],
    weaveType: "mid",
    prompt: "Thank them, and close.",
    context: "The shortest complete ending there is.",
    answers: ["Merci. Au revoir."],
    alternatives: ["Merci, au revoir.", "Merci. Au revoir !"],
    ifCorrect: "Two words each, and the day is finished cleanly.",
  }),
  weaveSeed({
    id: "p-l10-apply-greet-and-order",
    operation: "apply", difficulty: "medium", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Greet them, and order.",
    context: "The queue moved and it is suddenly your turn.",
    answers: ["Bonjour. Je voudrais un café."],
    alternatives: ["Bonjour, je voudrais un café."],
    ifCorrect: "Greeting before ordering is not optional here. It is the order.",
  }),
  weaveSeed({
    id: "p-l10-apply-order-tea-break",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-je-voudrais", "chunk-un-the", "chunk-faire-une-pause"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Order, and say what it is for.",
    context: "Ten minutes to yourself and you intend to use them.",
    answers: ["Je voudrais un thé. Je voudrais faire une pause."],
    alternatives: ["Je voudrais un thé, je voudrais faire une pause."],
    ifCorrect: "The same opener twice, doing two different jobs.",
  }),
  weaveSeed({
    id: "p-l10-apply-arrive-greet-order",
    operation: "apply", difficulty: "hard", surface: "context", lesson: L,
    required: ["chunk-bonjour", "chunk-je-suis-ici", "chunk-je-voudrais", "chunk-un-cafe"],
    targets: ["chunk-je-voudrais"],
    weaveType: "open",
    prompt: "Greet, announce yourself, and order.",
    context: "You are meeting someone here and you are first.",
    answers: ["Bonjour. Je suis ici. Je voudrais un café."],
    alternatives: ["Bonjour, je suis ici. Je voudrais un café."],
    ifCorrect: "A whole arrival in three short sentences.",
  }),
];
